### ISSUE TITLE
Add Valo 2 to the BOM

### ISSUE THREAD

**Issue by heruan** [vaadin/platform#10]
The BOM should include the Webjar of `vaadin-valo-theme` in a version compatible with the already included Vaadin Elements Webjar (currently `v2.0.0-alpha3`).

**Comment by heruan** [comment]
Possibly related to #9. Also, I see two different Webjar artifacts for Valo:

- vaadin-valo-theme
- github-com-vaadin-vaadin-valo-theme

**Comment by SomeoneToIgnore** [comment]
PR: https://github.com/vaadin/platform/pull/27

**Comment by heruan** [comment]
Had forgot about this, since Valo is already pinned in `webjars-bom` (currently still at alpha4).

**Comment by SomeoneToIgnore** [comment]
Will do it either.
This ticket allowed to put the actual dependency into the jar, so the users don't have to add it into project's dependencies manually.

Btw, the PR is merged, so the ticket can be closed.

**Comment by SomeoneToIgnore** [comment]
https://github.com/vaadin/flow/pull/3100

The other bom PR.
