### ISSUE TITLE
Latest vaadin-list-box-flow in V14

### ISSUE THREAD

**Issue by heruan** [vaadin/platform#1046]
Will `vaadin-list-box-flow` 2.1.0 land in 14.1.x? It has been released 20 days ago, but the BOM still pins 2.0.0 (not sure if it's safe to just override to 2.1.0).

**Comment by ZheSun88** [comment]
Hi @heruan , 

according to the `pom.xml`, the `vaadin-list-box-flow` should be using `2.1.0` in 14.1.2 and same with previous 14.1.X. 
https://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/14.1.2/vaadin-spring-bom-14.1.2.pom

**Comment by heruan** [comment]
You are right @ZheSun88! My bad, sorry. Keeping an eye on 14.0, 14.1, 14.2 and 15 I mixed things up 😅
