### ISSUE TITLE
Drop bower for 15.x from vaadin-core and vaadin

### ISSUE THREAD

**Issue by web-padawan** [vaadin/platform#1056]
Currently `vaadin-core` package contains `vaadin-router` which is not published to bower.
This causes the CI builds on master branch to fail with the following error:

```
bower ENOTFOUND     Package vaadin-router not found
The command "bower install" failed and exited with 1 during .
```

There was already an issue #904 but apparently it did not cover this.
There should be no more `bower.json` for V15.

**Comment by ZheSun88** [comment]
probably just remove this line is enough https://github.com/vaadin/vaadin-core/blob/master/.travis.yml#L17? how do you think?

**Comment by web-padawan** [comment]
Agreed. It should be removed from `master` for sure.

**Comment by web-padawan** [comment]
Another thing that needs to be removed is `bower.json` itself (and the script that updates it).

**Comment by web-padawan** [comment]
Submitted https://github.com/vaadin/vaadin-core/pull/231

**Comment by ZheSun88** [comment]
merged.

**Comment by web-padawan** [comment]
@ZheSun88 please also this one https://github.com/vaadin/vaadin/pull/60
