### ISSUE TITLE
Broken image in Vaadin Button Java example

### ISSUE THREAD

**Issue by Peppe** [vaadin/platform#117]
I'm not sure to which repo or team the Java API, and their examples are, so I write this generally to the platform. 

On https://vaadin.com/components/vaadin-button/java-examples, there is a broken image which looks bad. 

![screen shot 2018-03-27 at 11 21 53](https://user-images.githubusercontent.com/525503/37955365-17070268-31b1-11e8-91e8-4ae406e02753.png)

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-button-flow #49](https://github.com/vaadin/vaadin-button-flow/issues/49) via [**ZenHub**](https://www.zenhub.com/)
