### ISSUE TITLE
Vaadin 15: 'Error loading frontend://dndConnector.js'

### ISSUE THREAD

**Issue by Tonne-TM** [vaadin/platform#1258]
I get the following error after each page load (after initial page load and after pressing F5 each time).

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
FlowClient.js?2d7e:203 Error loading frontend://dndConnector.js
UB @ FlowClient.js?2d7e:203
FlowClient.js?2d7e:203 'frontend://dndConnector.js' could not be loaded.
UB @ FlowClient.js?2d7e:203
```

When compiled to production the error is also shown (but just in the console).

System: Windows 10
Vaadin: 15.0.3 (with maven plugin) - (also is 15.0.0)
Spring Boot: 2.2.4
JDK: 11

What could be the cause of this error?

**Comment by haijian-vaadin** [comment]
Hi @Tonne-TM, thank you for reporting, it's a known issue https://github.com/vaadin/flow/issues/7753, which has already been fixed. But unfortunately, the fix slipped from the current release. You can expect it from the next release, hopefully, next week.

**Comment by Tonne-TM** [comment]
Thanks for the fast reply!
