### ISSUE TITLE
Platform tests on JDK 14 and 15

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#1259]
- update the current JDK tests to once per week
- ask SD for Java 14 and early access 15 test on one agent.

**Comment by ZheSun88** [comment]
now JDK(8, 11, 13)  test has been set to run once per week, Friday morning, as we normally have some time on Friday.

**Comment by manolo** [comment]
We need either
- depend on SD installing early access version of Java each time it changes
- download docker images with the JDK installed and run tests inside them. (CircleCI ?) 
  - it could help us to understand this CI provider, the paying plans, etc
- Create a new TC process able to download java and use it for running the project

**Comment by manolo** [comment]
We cannot use flow build since it does not compile in these versions https://github.com/vaadin/flow/issues/8661

**Comment by ZheSun88** [comment]
JDK 14 and 15(EA) has been added to all agents on TeamCity.
