### ISSUE TITLE
Could not download vaadin-spring-boot-starter-15.0.4.jar (com.vaadin:vaadin-spring-boot-starter:15.0.4)

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/platform#1292]
Gradle can not download 15.0.4 (see. below).  15.0.3 - no problem.
```
Could not download vaadin-spring-boot-starter-15.0.4.jar (com.vaadin:vaadin-spring-boot-starter:15.0.4)
Could not get resource 'https://jcenter.bintray.com/com/vaadin/vaadin-spring-boot-starter/15.0.4/vaadin-spring-boot-starter-15.0.4.jar'.
Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/com/vaadin/vaadin-spring-boot-starter/15.0.4/vaadin-spring-boot-starter-15.0.4.jar?referrer'.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
unable to find valid certification path to requested target
```

**Comment by ZheSun88** [comment]
Hi @vlipovetskii 

Thanks for using Vaadin 15.  Do you mind to provide us a sample project to reproduce the issue you have mentioned here?  It looks i can find the artifacts by clicking just the links in the log.

**Comment by vlipovetskii** [comment]
By default, Maven will get project dependencies from Maven Local Repository, if it is not found, Maven will get it from the Maven Central Repository

Maven Central Repository URL – https://repo.maven.apache.org/maven2

Here you will find 15.0.4, 15.0.5.

I have found today 15.0.5 and there is no a problem with it. Please close the issue.
