### ISSUE TITLE
build with checksums enforced fails

### ISSUE THREAD

**Issue by mvysny** [vaadin/platform#1333]
To reproduce:
1. rm -rf ~/.m2
2. git clone https://github.com/vaadin/platform && cd platform && git checkout 14.1
3. scripts/generateBoms.sh
4. mvn -C clean install -DskipTests

The build will eventually fail with:

```
[ERROR] Failed to execute goal on project vaadin-spring-boot-starter: Could not resolve dependencies for project com.vaadin:vaadin-spring-boot-starter:jar:14.1-SNAPSHOT: Failed to collect dependencies at com.vaadin:vaadin-core:jar:14.1-SNAPSHOT -> com.vaadin:vaadin-accordion-flow:jar:2.0.0 -> com.vaadin:vaadin-details-flow:jar:2.0.0 -> org.webjars.bowergithub.vaadin:vaadin-details:jar:1.0.1 -> org.webjars.bowergithub.vaadin:vaadin-material-styles:jar:1.2.1: Failed to read artifact descriptor for org.webjars.bowergithub.vaadin:vaadin-material-styles:jar:1.2.1: Could not transfer artifact org.webjars.bowergithub.vaadin:vaadin-material-styles:pom:1.2.1 from/to central (https://repo.maven.apache.org/maven2): Checksum validation failed, no checksums available -> [Help 1]
```

**Comment by mvysny** [comment]
The reason is probably because https://repo.maven.apache.org/maven2/org/webjars/bowergithub/vaadin/vaadin-material-styles/1.2.1/ is missing .md5 and .sha checksum files. The folder also seem to be missing a lot of files (jars) compared to e.g. https://repo.maven.apache.org/maven2/org/webjars/bowergithub/vaadin/vaadin-material-styles/1.2.2

**Comment by ZheSun88** [comment]
Yes, as those artifacts are deployed by [webjars.org](https://www.webjars.org/), what we can do from our side is quite limited.

**Comment by ZheSun88** [comment]
This is a webjar issue instead of a vaadin issue.
