### ISSUE TITLE
Error in generated tsconfig.json

### ISSUE THREAD

**Issue by TGit911iger** [vaadin/platform#1342]
<img width="981" alt="tsconfig" src="https://user-images.githubusercontent.com/9194576/82183251-eaa78000-98e5-11ea-87ca-991604cee4b9.png">

Vaadin 16.0.0.beta2

Generating tsconfig -> error.

**Comment by web-padawan** [comment]
Hello, looks like you have strict JSON checker enabled in your IDE which results in this error.

While JSON syntax does not support comments, `tsconfig.json` is a special case and there is a support for comments there implemented by https://github.com/microsoft/TypeScript/pull/5450.

So far we haven't had any problems with this. You can safely remove the comment on top of the file and then commit it, as the comment suggests. Then the error should go away.
