### ISSUE TITLE
Scan the full platform build for known vulnerabilities

### ISSUE THREAD

**Issue by Legioth** [vaadin/platform#1349]
Scan the full transitive dependency tree of the whole Vaadin platform for known vulnerabilities as part of each platform release. In this way, we would notice any cases when we're accidentally introducing transitive dependencies to third-party library versions with known dependencies.

For the Maven parts, https://search.maven.org/artifact/org.owasp/dependency-check-maven/5.3.2/maven-plugin could be used. For the npm parts, the built-in `npm audit` command could be used.

**Comment by ZheSun88** [comment]
Add first try to integrate the plugin into platform. 
https://github.com/vaadin/platform/pull/1350

**Comment by manolo** [comment]
Closing so as we can track the same in #1386
