### ISSUE TITLE
14.2.0 creates many duplicate dependencies in package.json

### ISSUE THREAD

**Issue by epricer** [vaadin/platform#1367]
### Description of the bug
Duplicate dependencies are created in the build after upgrading to Vaadin 14.2.0. Downgrading to 14.1.28, removing the package.json files, rebuilding rectifies the problem. This results in `Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry'` when running in production mode.
### Minimal reproducible example
Create a 14.2.0 project through Spring Initializr
Create a superficial view with route (might not be necessary)
Build with `mvnw package`
Run `npx find-duplicate-dependencies`
### Expected behavior
No duplicate dependencies
### Actual behavior
Over 10 duplicate dependencies.
### Versions:
    - Vaadin / Flow version: 14.2.0
    - Java version: 11.0.7 openjdk
    - OS version: Ubuntu 20.04
    - Browser version (if applicable): NA
    - Application Server (if applicable): Embedded spring boot
    - IDE (if applicable): NA

**Comment by manolo** [comment]
Seems not happening anymore. @epricer  feel free to reopen it if you still experiment the problem.

**Comment by masbaehr** [comment]
Getting this with 14.6.1 , trying for hours to resolve the issue :(

Everything builds fine, but UI messed up

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry

**Comment by manolo** [comment]
what happens if you do a full clean or your project?, I meant remove node_modules, package*, pnpm*, webpack*, target

**Comment by masbaehr** [comment]
Thanks for answering, i did so multiple times tried everything, pnpm -v is 6.6.2 . I think maybe some version bug.. Anyway what helped at the end was to get rid of the files as you said, but then instead of rebuilding with pnpm i set   pnpmEnable = false in build.gradle and vaadin.pnpm.enabled: false in application.properties  - and just with using NPM everything works fine!

**Comment by manolo** [comment]
yes, it's safe to use `npm` since performance has improved a lot since we implemented `pnpm`
