### ISSUE TITLE
stable releases to maven central fail to close staging repository with timeout with sonatype

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/platform#1425]
Default timeout (5 mins) is not enough more often than not and builds fail.
Depending on the step it's possible to close or release the staging repository via the web UI.
None of the following build steps are executed.
The last two points require more manual steps in different systems to finish releases.

**Comment by manolo** [comment]
Not an issue anymore since we added to platform &&  flow-components build the `-DstagingProgressTimeoutMinutes=20`   parameter
