### ISSUE TITLE
typescript modules inadvertently generated from java code 

### ISSUE THREAD

**Issue by jzelenka** [vaadin/platform#1449]
Vaadin version 16.0.1

According to https://vaadin.com/docs/v16/flow/typescript/accessing-backend.html  typescript modules should be generated to `{project.basedir}/frontend/generated` for java classes anotated with @Endpoint annotation.

I presume it should be `com.vaadin.flow.server.connect.Endpoint`, however, they are generated also for "other" @Endpoint annotations, for example for `org.springframework.ws.server.endpoint.annotation.Endpoint`

Looks like only simple string "Endpoint" is taken into account.

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by manolo** [comment]
Issue moved to [vaadin/flow #8743](https://github.com/vaadin/flow/issues/8743) via [**ZenHub**](https://www.zenhub.com/)
