### ISSUE TITLE
Run checking for snapshot versions used in parent project before releases 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#1491]
Snapshot versions should not be used in platform release. so that we should check those before releases.

for example in 17.0.0.beta2, some components are using snapshot version of flow-component-base

**Comment by ZheSun88** [comment]
we have the `no-snapshot` profile in the **vaadin** module and it has been enabled in the release build.. but this only checks the direct dependencies in platform , not the transitive dependencies

**Comment by manolo** [comment]
not valid anymore since we have monorepo
