### ISSUE TITLE
Produce .csv files with contribution information

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#1515]
**Data sets for the sentiment analysis study**

- We need to process `flow` and web components:
  - https://github.com/vaadin/flow
  - https://github.com/vaadin/vaadin-accordion
  - https://github.com/vaadin/vaadin-app-layout
  - https://github.com/vaadin/vaadin-button
  - https://github.com/vaadin/vaadin-checkbox
  - https://github.com/vaadin/vaadin-combo-box
  - https://github.com/vaadin/vaadin-context-menu
  - https://github.com/vaadin/vaadin-control-state-mixin
  - https://github.com/vaadin/vaadin-custom-field
  - https://github.com/vaadin/vaadin-date-picker
  - https://github.com/vaadin/vaadin-date-time-picker
  - https://github.com/vaadin/vaadin-details
  - https://github.com/vaadin/vaadin-development-mode-detector
  - https://github.com/vaadin/vaadin-dialog
  - https://github.com/vaadin/vaadin-element-mixin
  - https://github.com/vaadin/vaadin-form-layout
  - https://github.com/vaadin/vaadin-grid
  - https://github.com/vaadin/vaadin-icons
  - https://github.com/vaadin/vaadin-item
  - https://github.com/vaadin/vaadin-list-box
  - https://github.com/vaadin/vaadin-list-mixin
  - https://github.com/vaadin/vaadin-login
  - https://github.com/vaadin/vaadin-lumo-styles
  - https://github.com/vaadin/vaadin-material-styles
  - https://github.com/vaadin/vaadin-menu-bar
  - https://github.com/vaadin/vaadin-notification
  - https://github.com/vaadin/vaadin-ordered-layout
  - https://github.com/vaadin/vaadin-overlay
  - https://github.com/vaadin/vaadin-progress-bar
  - https://github.com/vaadin/vaadin-radio-button
  - https://github.com/vaadin/vaadin-select
  - https://github.com/vaadin/vaadin-split-layout
  - https://github.com/vaadin/vaadin-tabs
  - https://github.com/vaadin/vaadin-text-field
  - https://github.com/vaadin/vaadin-themable-mixin
  - https://github.com/vaadin/vaadin-time-picker
  - https://github.com/vaadin/vaadin-upload
  - https://github.com/vaadin/vaadin-usage-statistics
  - https://github.com/vaadin/vaadin-board
  - https://github.com/vaadin/vaadin-charts
  - https://github.com/vaadin/vaadin-confirm-dialog
  - https://github.com/vaadin/vaadin-cookie-consent
  - https://github.com/vaadin/vaadin-crud
  - https://github.com/vaadin/vaadin-grid-pro
  - https://github.com/vaadin/vaadin-rich-text-editor
  - https://github.com/vaadin/vaadin-router

- The output of each report should be
  - a `.csv` file able to import in excel
  - a field per commit with the following fields
     - committer id (anonymous - no email)
     - external/internal contribution flag
     - commit message
     - commit stats (files, insertions, deletions)
     - affected tickets comments
     - PR discussion

open questions:
  - when the PR was merged instead of squashed, do we create a unique record?

We have 2-3 weeks max to deliver the `.csv` files

Tasks
- [ ] write the script to be run (Zhe)

**Comment by ZheSun88** [comment]
some updates:
general info has been ported in this file => [info.zip](https://github.com/vaadin/platform/files/5266763/info.zip)

github APIs for:

- pull request comment: https://api.github.com/repos/vaadin/{repo-name}/pulls/comments
- normal comments in PR (comments from reviewable or just normal comment): https://api.github.com/repos/vaadin/{repo-name}/issues/comments

**Comment by ZheSun88** [comment]
extracted comments from Flow repo. 

There are around 14K comments from flow repo, after filter out bot comments. 
As Github doesn't provide commit ID for issues comments, i keep the pull request number for all.  
[flow_repo_comments.zip](https://github.com/vaadin/platform/files/5309822/flow_repo_comments.zip)

**Comment by ZheSun88** [comment]
updated extracted message based on user request
[github_info_flow.zip](https://github.com/vaadin/platform/files/5399536/github_info_flow.zip)
