### ISSUE TITLE
Rename Checkbox to CheckBox in Vaadin 10 flow

### ISSUE THREAD

**Issue by esommars** [vaadin/platform#156]
Use same CamelCase as other components like ComboBox or ListBox

**Comment by Artur-** [comment]
This is related to the naming of `vaadin-checkbox` vs `vaadin-combo-box`

**Comment by jouni** [comment]
Yeah, that does seem inconsistent. We based the naming on how Wikipedia lists them (which is probably an odd choice as well):

- https://en.wikipedia.org/wiki/Checkbox
- https://en.wikipedia.org/wiki/Combo_box
- https://en.wikipedia.org/wiki/List_box

More from: https://en.wikipedia.org/wiki/Widget_(GUI)#List_of_common_generic_widgets

**Comment by tomivirkki** [comment]
The `<vaadin-checkbox>` web component isn't going to be renamed (stable released already). Also, the platform has reached beta so the Java counterpart will likely not be renamed either. I'm in favour of closing this (can be reconsidered for future major releases).

**Comment by pleku** [comment]
I agree, checkbox is a known concept and a complete word, that should not be hyphenated (JS) or made camel case (Java). It is different from `ComboBox` or `ListBox`.

Closing as won't fix.
