### ISSUE TITLE
Improved theming support

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#1571]
As a developer
I want to create a theme that can be packed in a depdency
So that I can reuse it in any Vaadin application

## Acceptance criteria
- [x] All stylesheets (global and Vaadin component specific) can be placed in the same folder.
- [x] Vaadin component styles are automatically injected into the component's shadow dom based on the stylesheet's filename.
- [x] Non-css assets like fonts and images can be placed in the same folder, for use via css and code.
- [x] The entire theme can be applied to a Vaadin application with a single annotation.
- [x] The theme can be defined as part of a Vaadin application project for use in that project.
- [x] The theme can be packaged as a dependency that can be used in any Vaadin application project.
- [x] The theme can be used both for Java and TS-based UIs.
- [x] Css can be imported to the theme from npm dependencies via definitions in the theme folder.
- [x] Non-css assets from npm dependencies can be made available via definitions in the theme folder.
- [x] Changes to the theme folder's contents are picked up automatically, so that live reload or a manual browser refresh is sufficient to see the changes in a running application in devmode.
- [x] The theme's global css can be applied to the shadow dom of custom web components such as application views built with TS+Lit, and java components exported using the WebComponentExporter feature.
- [x] @font-face rules and other css features that may not work when defined inside a shadow root and must be in document root can be placed in a special file whose contents are always loaded only into the document root, so that these features also work for web components embedded into non-Vaadin-app pages where the theme is only applied to the embedded component(s).
- [x] The theme can extend another theme by specifying the parent theme in the theme's metadata (and ensuring its dependency is loaded).
- [x] start.vaadin.com is updated to use the new mechanism for projects based on platform version with the feature.
- [x] Theme project can be run as a normal Vaadin app with sample views for developing the theme.

## General criteria

- [x] APIs reviewed 
https://docs.google.com/document/d/1j70mIzv2IeeKM9B9Efyk6PIIGvvQ31yaMeJvHLG3ISk/edit?usp=sharing

- [x] UX/DX tests in Alpha 
https://docs.google.com/document/d/1ZBcoY4TbryBplisArgLechJ07Dat0uPb8ACS1LSO5-A/edit?usp=sharing

- [x] Documentation: 
https://vaadin.com/docs-beta/latest/ds/customization/custom-theme/

- [x] How to test? 
https://docs.google.com/document/d/1ZBcoY4TbryBplisArgLechJ07Dat0uPb8ACS1LSO5-A/edit?usp=sharing

- [x] Limitations: 
https://github.com/vaadin/flow/issues?q=is%3Aissue+milestone%3A%22Custom+Theme+Feature%22+is%3Aopen
https://github.com/vaadin/flow/issues/9767

## Description
A simpler, language-agnostic way to define a custom theme that can be packaged and reused as a dependency.

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by knoobie** [comment]
@rolfsmeds I know of quite a lot of legacy applications that heavily rely on swapping themes on the fly like in `UI::init` - is this use case supported with this new theming approach?

**Comment by rolfsmeds** [comment]
Hi @knoobie, the first iteration of this feature will not support runtime switching of themes, just like the current V14 @Theme annotation also doesn't support it -- we might add that possibility later, but it's not entirely trivial due to bundling of frontend resources etc. There's some discussion on the topic in this old ticket: https://github.com/vaadin/flow/issues/5163.

The least hacky way to do this today, as well as with the new mechanism, is to either implement each of the "sub themes" as css variable presets, just like the light and dark variants of Lumo (https://github.com/vaadin/vaadin-lumo-styles/blob/2a8cd8f432b36e78c29ee8b8974c2b2130bd099d/color.html#L120) or the compact preset (https://github.com/vaadin/vaadin-lumo-styles/blob/master/presets/compact.html) are implemented.

Either each preset is always loaded, but scoped to different attribute or classname on the `<body>` element that you can set runtime (like with Lumo light/dark), or the presets are in stylesheets that you load selectively runtime (as you can do with the compact preset).

**Comment by knoobie** [comment]
@rolfsmeds thanks for your feedback! Let me change my question a little bit; one of your acceptance criteria specifes that `The theme can be packaged as a dependency that can be used in any Vaadin application project.` - meaning I could create the following infrastructure:

- theme-1
- theme-2
- web-application (depending on theme-1 and theme-2) 

Now, my expectation as developer are:
- inside `theme-1` I define the vaadin-maven-plugin with configuration `build-theme`
- inside `theme-2` I define the vaadin-maven-plugin with configuration `build-theme`
- Inside `web-application` I can specify with `setTheme("theme-1")` or `setTheme("theme-2")` which themes should be applied 
- Inside `web-application` I expect that all created resources of `theme-1` can be found below `/VAADIN/theme/theme-1` so there is no clash on client side or duplicate resources

**Comment by rolfsmeds** [comment]
Well, it's a bit different compared to e.g. V8, in that there's no theme-specific maven config, but instead the project containing the reusable theme is simply packaged as a JAR, and, when included in the `web-application` project and applied with the `@Theme("theme-1")` annotation in the project's `Application` class, Flow picks up the stylesheets in the folder with that name and applies them to the app UI.

So, in the initial version, while you can include dependencies with multiple different themes, you can only apply one of them. The non-applied theme's resources will simply not be loaded to the client at all.

How this would work with runtime theme switching is still undefined.

**Comment by knoobie** [comment]
@rolfsmeds Thanks for the clarification! Let's say - I'm more than happy to get the possibility of "real" theming back.. having this was just the icing on the cake. It's still possible to archive with your "hacky" solutions like it's done within lumo or material.
