### ISSUE TITLE
[BUG] Plaform is missing the flow-dev-deps dependency

### ISSUE THREAD

**Issue by caalador** [vaadin/platform#1633]
Since V17 the vaadin-core bom should contain `flow-dev-deps` which defined development
time dependency versions for given flow/platform release.

For more details see [9251](https://github.com/vaadin/flow/issues/9251)

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by ZheSun88** [comment]
I added the module into vaadin-core pom, and tested the issue mentioned in the original ticket, it worked. :-)

**Comment by ZheSun88** [comment]
this issue has been fixed from flow level by https://github.com/vaadin/flow/pull/9476. 
we will consider adding this module to platform later
