### ISSUE TITLE
Add flow-osgi back to the platform for 19 

### ISSUE THREAD

**Issue by pleku** [vaadin/platform#1669]
It should go to https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-bom.xml like with CDI even though for 14 it was in https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-spring-bom.xml.

Also the integration tests for all the components for OSGi compatibility should be added back (exists in 14 still).

**Comment by denis-anisimov** [comment]
One more question:
should osgi have it's own entry in https://github.com/vaadin/platform/blob/master/versions.json like Spring/CDI ?
Or this is exactly the same question ?

Please note: `flow-osgi` is not anymore in the Flow repo. It's a module in https://github.com/vaadin/osgi repo.

**Comment by pleku** [comment]
>should osgi have it's own entry in https://github.com/vaadin/platform/blob/master/versions.json like Spring/CDI ?

I think not since then it would be added as a dependency to `vaadin-core` which we don't want. The version should be just managed by the `vaadin-bom`. 

But @manolo and @ZheSun88 promised to take a look at this @denis-anisimov , so if need it ASAP just agree with them what to do.

**Comment by denis-anisimov** [comment]
OK.

I don't need this at all.
This is a pure Platform issue which doesn't block me anyhow.

OSGi verification for Platform can be a bit complicated. That could be done by me at some point. But this is not urgent.

**Comment by ZheSun88** [comment]
module has been added to platform V19 with this PR. https://github.com/vaadin/platform/pull/1677

**Comment by ZheSun88** [comment]
adding OSGi test to platform has been moved to #1698
