### ISSUE TITLE
[BUG] Release Notes Links return 404 (component flow repos)

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#1695]
**Describe the bug**
 * Given https://github.com/vaadin/platform/releases/tag/14.4.4
 * I click on Vaadin Accordion ([Flow integration 2.2.2](https://github.com/vaadin/vaadin-accordion-flow/releases/tag/2.2.2)) 
 * I get a 404

**Expected behavior**
 * I get the release notes of Vaadin Accordion's flow integration 2.2.2

Additional question:
 * Did really so much change between 14.4.3 and 14.4.4?

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by ZheSun88** [comment]
Thanks for letting us know, i have updated the release note. will soon update the release note template. 

and to answer the additional question:

as stated in the release note, 
![image](https://user-images.githubusercontent.com/31067185/100704020-68783800-33ad-11eb-9049-96102be8f12d.png)

there is a fix in this release affecting quite a lot of components. same with internal dependency updates.

**Comment by knoobie** [comment]
@ZheSun88 thanks! The amount of changes make sense, once I saw the missing patch notes :)
