### ISSUE TITLE
TypeScript type definitions for Vaadin component events (part 1: 20 of 35 components)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/platform#1745]
When using Vaadin components in TypeScript code, for each component I want to see the available events and their TypeScript types in IDE auto-completion so that I do not have to look this up in the docs or rely on my memory. I also want the TypeScript compiler to automatically verify that I use the correct types when accessing event details in event handlers in TypeScript.

Included components: [19 out of 35](https://docs.google.com/spreadsheets/d/1kqG4aug713612cbho08GwCBVLmR94BT70gHuJOFuha8/edit#gid=660325664&range=A2:A20).

## Acceptance criteria
- **[IDE auto-completion in lit-html templates]**
  - [ ] when adding an event handler to a Vaadin component, after I enter `@` IDE auto-suggests the same events as are listed in the API docs for the component (e.g. for `vaadin-combo-box` the IDE should auto-suggest `change`, `custom-value-set`, `selected-item-changed`, `value-changed`, as listed in [the API docs](https://vaadin.com/docs-beta/latest/ds/components/combo-box/api/))
  - (known limitation) ~when defining an inline event handler for an event, the correct type of the `event` argument is inferred automatically~
     - [ ] ~for non-generic event types (e.g. the type of the `invalid-changed` event on `vaadin-text-field`)~
     - [ ] ~for generic event types (e.g. the type of the `selected-item-changed` event on `vaadin-combo-box`)~
 - **[IDE auto-completion in imperative TypeScript code]**
   - [ ] when adding an event handler to a Vaadin component, after I type `.addEventListener('` IDE auto-suggests the same events as are listed in the API docs for the component (e.g. for `vaadin-combo-box` the IDE should auto-suggest `change`, `custom-value-set`, `selected-item-changed`, `value-changed`, as listed in [the API docs](https://vaadin.com/docs-beta/latest/ds/components/combo-box/api/))
   - when defining an event handler for an event, the correct type of the `event` argument is inferred automatically
     - [ ] for non-generic event types (e.g. the type of the `invalid-changed` event on `vaadin-text-field`)
     - [ ] for generic event types (e.g. the type of the `selected-item-changed` event on `vaadin-combo-box`)
 - **[build-time type checking in imperative TypeScript code]**
   - [ ] using a wrong event name in `addEventListener` is a compilation error (e.g. `selected-item-changed` on `vaadin-text-field`)
   - [ ] explicitly using a wrong the event type in `addEventListener` is a compilation error (e.g. declaring the event type as `{detail: {value: string}}` in `invalid-changed` on `vaadin-text-field`)
   - [ ] implicitly using a wrong the event type in `addEventListener` is a compilation error (e.g. assigning `event.detail.value` to a string variable in `invalid-changed` on `vaadin-text-field`)

## General criteria
- [ ] UX/DX tests in Alpha [here link(s) to issue(s) with the description of UX/DX tests, if any]
- [ ] Documentation (all cases where the docs include TS / LitElement code samples with Vaadin components should use typed events): [here link to the documentation]
- [ ] How to test? [here link to the GH issue or some external document with the test scenario]
- [ ] Limitations: [automatic TS type inference does not work in lit-html templates, build-time type checking does not work in lit-html templates]

**Comment by web-padawan** [comment]
We also need to convert `vaadin-avatar` to avoid duplicate dependencies. Updated the [status sheet](https://docs.google.com/spreadsheets/d/1kqG4aug713612cbho08GwCBVLmR94BT70gHuJOFuha8/edit#gid=660325664&range=A2:A21) accordingly.
