### ISSUE TITLE
DocBuilder

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#1746]
As a developer
I want to set up a documentation website for my company's design system
So that I can publish all relevant info and examples for the DS for my team

## Acceptance criteria
- [ ] DocBuilder can be installed locally
- [ ] Default content (clone of Vaadin "baseline" DS documentation) is available in the local installation
- [ ] Can be run locally (on development server)
- [ ] Can make production build (for deployment of site)
- [ ] Startup: initial build in <5min, subsequent builds in <1min
- [ ] Can plug in JAR with custom components to be used in the UI samples
- [ ] Can plug in JAR with custom theme and apply it to the UI samples
- [ ] ...

## General criteria
- [ ] Performance [here link to the requirement or tests, if any]
- [ ] UX/DX tests in Alpha [here link(s) to issue(s) with the description of UX/DX tests, if any]

**Comment by jouni** [comment]
This one can probably be closed as completed.

**Comment by web-padawan** [comment]
Closing per above comment.
