### ISSUE TITLE
Add tests for wrong import identifying

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#1755]
https://vaadin.slack.com/archives/CACKS4075/p1609747834255100

the `stats.json` can be generated by webpack when running production build 

need some investigation

**Comment by manolo** [comment]
Probably run some `.js`  script that parses the `target/..../stats.json` file generated during `vaadin:frontend-build`  the script can be run before `verify` using some maven `exec` plugin

**Comment by manolo** [comment]
stats.json is only available in webpack, what happens with vite ?

**Comment by manolo** [comment]
Does not happen anymore
