### ISSUE TITLE
[BUG] About SplitLayout component 

### ISSUE THREAD

**Issue by yuan199696** [vaadin/platform#1779]
[BUG]When i used SplitLayout component for Grid and Form ,the upload component of Form can not available!

`SplitLayout splitLayout = new SplitLayout(grid, form);`

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by ZheSun88** [comment]
Hi @yuan199696, 
Could you provide us some example codes to reproduce the issue you mentioned here? And which version of vaadin platform do you use?

BR

**Comment by manolo** [comment]
Please can you provide code for reproducing it, otherwise we have to close the issue.
Thanks
