### ISSUE TITLE
Why Bump 14.4 to Spring Boot 2.4.0 #1678 ?

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/platform#1789]
As it is expected that 14 is LTS version so why it is jump from 2.2.0 version even in subminor?
Isn't a typo due to merge with non-lts?

As 2.4.0 and even to 2.3.0 contains so much possible breakable changes.

1. use complex application with such 2.2.x dependency
2. run complex application with such 2.4.x dependency without change of licensing and extra fees and without breaking anything and refactoring

**Expected behavior**
Do not upgrade complex dependencies (like a spring is) especially in LTS version.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version:  14.4.4+
 - Vaadin platform version: 14.4.4+

https://github.com/vaadin/platform/pull/1678

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by mstahv** [comment]
Hi,

We want to keep supporting latest Spring Boot version also with our LTS version. When we upgrade the version, as done in the PR you referred, we get our tests executed against that Spring Boot and we can keep the latest Vaadin LTS release offered for new projects, when you for example create a new project using the Spring Initializr. 

That doesn't mean that you have to always update your Spring Boot version in your own project. If you find a compatibility issue with an older Spring Boot version and Vaadin, let us know and we'll try to find a workaround. The changes we have needed to do so far for Vaadin has been backwards compatible with older versions of Spring Boot.

cheers,
matti

**Comment by netbeansuser2019** [comment]
Well, then you could specify lower level of Spring Boot and it will be resolved even higher version for that they are needed. But setting higher version you send a signal that your project it is dependent on new features. Of course other solution is using BOM.
BTW: version 2.3.8 and 2.4.2 is badly broken about gradle projects in Netbeans.
