### ISSUE TITLE
Use cherry-pick script in other repos

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#1807]
- ~platform~
- ~flow-components~
- ~Flow~
- Flow addons (~spring~, osgi, cdi, ~mpr~ ... ) 
  - osgi and cdi have only one branch, no sense to have it
- ~WCs~
- skeletons used in wizard
- ask to ~CE~ and designer

**Comment by ZheSun88** [comment]
spring： https://github.com/vaadin/spring/pull/814

**Comment by ZheSun88** [comment]
MPR: https://github.com/vaadin/multiplatform-runtime-internal/pull/527

**Comment by ZheSun88** [comment]
CE: https://github.com/vaadin/collaboration-engine-internal/pull/668
