### ISSUE TITLE
Platform 19.0-SNAPSHOT is not OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/platform#1816]
`vaadin`. module has collaboration engine `3.0-SNAPSHOT`.
This version has no OSGi compatible manifest.
Here is the manifest:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: root
Created-By: Apache Maven 3.5.3
Build-Jdk: 1.8.0_201
```

I don't know whether this is a problem of CE or Platform.
There is `3.1.0`  CE version and I remember the efforts of CE team to make it OSGi compatible.
So either Platform 19.0 uses wrong CE version or it's an issue in CE itself.

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by manolo** [comment]
`CE-3.0-SNAPSHOT` is in place now with the appropriate bundle info in manifest.
