### ISSUE TITLE
Support for Apache Karaf / Karaf Feature

### ISSUE THREAD

**Issue by JulianFeinauer** [vaadin/platform#1826]
Just posting this here as there may be another community here. Description is copied over from https://vaadin.com/forum/thread/17845647/apache-karaf-osgi-integration-for-vaadin-flow

we are currently investigating the migration of a Vaadin Flow (currently 13.x) Application from Spring to OSGi, Apache Karaf in more detail. There is somme documentation on the Vaadin site https://vaadin.com/docs/v14/flow/osgi/tutorial-osgi-basic.html. Furthermore, I found this example App in Github https://github.com/vaadin/base-starter-flow-osgi.

The first one I dont really get but the second one (the Github Example) I am able to run. But it starts an "internal" felix server. As we like Karaf I would like to see a Karaf feature for that, but I'm not able to extract that from the Felix example. I already raised an issue on the Karaf list here: https://lists.apache.org/thread.html/ddf62343a566e0e5066c5492df8354a1229e0e09a3c76c3e1edb0e7d@%3Cuser.karaf.apache.org%3E

It would be really nice to get Vaadin and Karaf folks to cooperate on this and help each other out. Has anybody any experience with Vaadin (Flow) on Karaf?

Thanks! Julian

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by denis-anisimov** [comment]
Flow features have been added.

Now features should be added in the Platform and this is done:

https://github.com/vaadin/vaadin-flow-components/pull/602
https://github.com/vaadin/platform/pull/1818

Platform team should review and merge this.

This is not Flow issue anymore.
