### ISSUE TITLE
Have offline integration tests in the platform repo 

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/platform#1844]
The testing application in the platform repo is currently Flow-based and doesn't have the offline feature, so incidents like [9977](https://github.com/vaadin/flow/issues/9977) could happen. We need to make the testing application in the platform to be Fusion based and have offline integration tests.

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.
