### ISSUE TITLE
Add one more step in platform release so as it creates PR for doc

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#1856]
The goal is that doc is never outdated, there are certain places where they are using the version number, pom files, and probably some doc.

**Comment by ZheSun88** [comment]
Add step 18 to the starter update list. https://bender.vaadin.com/admin/editBuildRunners.html?id=buildType:VaadinPlatform_UpdateMavenStarters

**Comment by manolo** [comment]
We should move this to a new step instead to be nested into the starters one

**Comment by ZheSun88** [comment]
a new build has been added here https://bender.vaadin.com/admin/editBuild.html?id=buildType:VaadinPlatform_UpdateDocsToUseTheLatestPlatform
