### ISSUE TITLE
[BUG] Anit-CSRF Token; X-Content-Type-Options Header missing on /VAADIN/build/...cache.js etc.

### ISSUE THREAD

**Issue by gdenn** [vaadin/platform#1860]
**Describe the bug**

I am using Vaadin 14 .4.7 with spring-boot-starter-parent2.3.4.RELEASE.

To set up my Application I followed a blog post from vaadin.com:
~> https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/setting-up-spring-security

(I am aware that the first version of the blog post had a security vulnerability and double-checked my code if I comply with the updated blog post)

Furthermore, I made the following additional configurations on my Spring Boot app and (Jetty) servlet:
1) I configured the HttpOnly mode in the Set-Cookie header (through the application.properties config param `server.servlet.session.cookie.http-only=true`)
2) I configured `X-Frame-Options: SAMEORIGIN`  in my `WebSecurityConfigurerAdapter` configure method (`http.headers().frameOptions().sameOrigin()`)
3) I configured the SameSite=Strict mode in the Set-Cookie header in my (Jetty) servlet configuration.

I ran an OWASP ZAP scan to confirm that my application is secure. The scan result showed that important headers are missing on some URLs:

**Missing `X-Frame-Options: SAMEORIGIN` on:**
* GET: http://localhost:8085/robots.txt

**Missing `X-XSS-Protection: 1; mode=block` on:**
* GET: http://localhost:8085/VAADIN/build/vaadin-bundle-9adccc74c0274fac9cea.cache.js
* GET: http://localhost:8085/VAADIN/build/vaadin-bundle.es5-49d2639ed2f12c70b1ed.cache.js

**Missing `X-Content-Type-Options: nosniff` on:**
* GET: http://localhost:8085/robots.txt
* GET: http://localhost:8085/VAADIN/build/vaadin-bundle-9adccc74c0274fac9cea.cache.js
* GET: http://localhost:8085/VAADIN/build/vaadin-bundle.es5-49d2639ed2f12c70b1ed.cache.js
* GET: http://localhost:8085/VAADIN/build/webcomponentsjs/webcomponents-loader.js
* GET: http://localhost:8085/VAADIN/static/client/client-5C40CA4B9D1F93A241DF9189632E0919.cache.js
* GET: http://localhost:8085/VAADIN/static/push/vaadinPush.js?v=2.4.6

I am not familiar how the Vaadin platform operates in detail. My understanding was that I have control over the HTTP response headers when I run Vaadin with spring boot.

The scan result show that this seems to work for the most part of my application. I made a http request to the landing page to demonstrate this:

```shell
curl -sSL -D - http://localhost:8085 -o /dev/null

HTTP/1.1 200 OK
Date: Thu, 11 Feb 2021 12:46:24 GMT
Set-Cookie: JSESSIONID=<redacted>.node0; Path=/; HttpOnly; SameSite=Strict
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Length: 1373
```

The HTTP response of the landing page contains all important HTTP headers and Set-Cookie header options.

But a couple of other URLs such as `VAADIN/build/...`, `VAADIN/static/...` and `/robots.txt` do not contain any of the configured HTTP response headers.

**To Reproduce**
1. Create a Vaadin Spring Boot Application
2. Follow the instructions of https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/setting-up-spring-security 
3. Perform the configration adjustments mentioned in the section above
4. Install the OWASP ZAP scanning tool
5. Start your Vaadin UI (in my case on http://localhost:8085)
6. Open the OWASP ZAP tool; Run a "Quick Start" scan on "http://localhost:8085" 

**Expected behavior**

The OWAS ZAP scan should only show three informational alerts:
* "Information Disclosure ..."
* "Loosely Scoped Cookie"
* "Timestamp Disclosure..."

There should be **no alerts** with **risk Low or higher**

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Tested with Chrome and Firefox
 - Vaadin platform version 14 .4.7

**Comment by ZheSun88** [comment]
Thanks for using Vaadin Platform, we appreciate your help and are going to take care of this as soon as possible.

**Comment by TatuLund** [comment]
> Missing X-Frame-Options: SAMEORIGIN on:

For this we have documentation here:

https://vaadin.com/docs/v14/flow/advanced/framework-security.html#enabling-x-frame-options

The X-Frame-Options are a way for web pages or apps to tell the browser that they should not be run inside frames (inside another page). This is done to try to ensure that these sites are not wrapped in malicious pages where attackers can intercept user actions.

Vaadin does not automatically set the X-Frame-Options HTTP header, because many times apps should run inside frames. Developers can set this header either in their server options or by using the Java Servlet API (using e.g. the Vaadin BootstrapListener or creating a Servlet Filter).

**Comment by gdenn** [comment]
@TatuLund thank you, I will try to add the missing headers with the Servlet Filters.
