### ISSUE TITLE
vaadin-spring-bom for post 14 versions mentions flow-server-compatibility-mode artifact, which does not exists

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/platform#1953]
Vaadin 14.x is the latest version which can run in compatibility mode.

https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-spring-bom.xml#L105-L109

**Comment by ZheSun88** [comment]
issue has been fixed with #1982 (CP: #1985 )
