### ISSUE TITLE
[BUG] Platform 20.0 should use 7.0 osgi

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/platform#2000]
https://github.com/vaadin/platform/blob/master/versions.json has osgi version `6.0.0`.
I'm not sure what 6.0.0 means but it's wrong.
Is this a correct version ?
Then I don't know why it's not `6.0.1` .

There is no OSGi `7.0.0`  released version. There is just a SNAPSHOT.
I don't see any SNAPSHOT versions in the json so I'm not sure what should be set there.
Anyway: 20.0 should use 7.0 OSGi somehow.

**Comment by ZheSun88** [comment]
if there is no osgi 7.0.0, we will update it to 6.0.1. 

6.0.1 has been used in V19 branch, and we didn't pick that change to master branch. 
https://vaadin.slack.com/archives/C6RAXJATF/p1618204204189800

**Comment by ZheSun88** [comment]
osgi has been updated to 7.0.0.alpha1 https://github.com/vaadin/platform/blob/master/versions.json#L354
