### ISSUE TITLE
Lumo utility classes

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2029]
## Description
A set of utility css classes for common styling needs.

## Use cases
As a developer
I want to apply predefined css classes to custom html structures
So that I can create a good looking UIs easily

## Acceptance criteria
- [x] Utility classes can be loaded as a Lumo style module (same way as e.g. lumo-badges).
- [x] Developers can opt out from using the module.
- [x] Utility classes use existing Lumo variables where applicable.

## General criteria
- [x] Documentation: https://vaadin.com/docs/latest/ds/foundation/utility-classes
- [x] How to test? https://docs.google.com/document/d/1-jU0mJfRGFeITlAdFYOWGh_77nGgVPm3bcCha271szk
- [x] Limitations:  Material theme is not supported. No dedicated Flow API at this point (use `.addClassName()` to apply).

**Comment by vlukashov** [comment]
how to test: https://docs.google.com/document/d/1-jU0mJfRGFeITlAdFYOWGh_77nGgVPm3bcCha271szk
