### ISSUE TITLE
Stateless Fusion

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/platform#2038]
## Description

By "stateless" it means that Fusion would not create or store information into server sessions. The server would be stateless, allowing easier horizontal scaling of instances and high availability of services.

## Use cases
Classic use cases related to horizontal scaling (up and down) can be used here, such as:

- By only using the smallest and cheapest instances available from a cloud provider (such as AWS), run a stress test with hundreds of clients, and have the server infrastructure accommodate the load without noticeable latency for the users.
- In the same way, when the load goes down to a minimum amount, all extra instances are terminated.

Also in the realm of high availability:

- Have a client connecting to a cloud service with two instances. Detect which instance is receiving the requests from that client, and forcefully terminate it. The client should notice any latency or downtime while making the next request, since the remaining server should handle it.

## Acceptance criteria

- [ ] APIs reviewed 
[Vaadin Stateless Authentication](https://docs.google.com/document/d/1jmIEHyijaP6wUAhOnTDmGSz3fWDUjKXC0cMIVZoSa2I/edit?ts=60a4b734#heading=h.kl7bsxem2n89)

- [ ] [UX/DX tests in Alpha](https://docs.google.com/document/d/1G8WJKcKqjndcGFQyPAMBxIlQFeEX4o6T_R_pWOLbhio/edit) 

- [ ] [Documentation](https://vaadin.com/docs/latest/fusion/security/spring-stateless)

- [ ] How to test? 
Testing app: Bank of Vaadin app in the spring security for Fusion test module in the Spring repo.
The server statelessness of an application can be checked locally by:

1. Run an application with some login state.
2. Get the user logged in.
3. Terminate the server.
4. Run the server again.
5. Make a request from the application that would require special authorization.

The request should succeed, without refreshes or having to login again.

- [ ] Limitations:

**Comment by Artur-** [comment]
As the implementation is based on JWT, some additional clarifications about supported use cases would be nice.

Is this use case supported and if so how?

"As an administrator of our critical business application, I need to be able to lock out the employee who was just fired. Management suspects he wants to harm the business in any way he can"
