### ISSUE TITLE
[Epic] Split between Flow and Hilla (aka. Flow and Hilla modularization)

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/platform#2039]
## Description

Currently, parts that are shared between Flow and Hilla live in the same repository (https://github.com/vaadin/flow). This is confusing for users of both frameworks:

- For Hilla users, it's not clear where to find the framework in GitHub, where to report tickets and how to contribute code to it. Also some dependencies used in the code have "flow" in the package name, which doesn't help clarifying in which framework they are;
- For Flow users, there is a build overhead associated with Hilla dependencies and packaging needs, and having a second framework inside it gives the false sensation that Flow is mutating into Hilla (or Hilla is something the user would need to migrate to).

From the internal point of view, having both frameworks mixed together causes lots of overheads for both teams, and opens discussions about who maintains which part.

The vision on how the frameworks can be modularized and then split from each other is discussed in this [document](https://docs.google.com/document/d/1b7Cn4PGn4gWnMw_OOLI8puoLFKQsCfWtU5M0Fb6-UFU) (internal).

The breakdown of the tasks needed to reach the vision is described in this [document](https://docs.google.com/document/d/1UC-H6J1VmXOdzACWIwenFhP4yOEfjCpMeMiY3UL_Od4) (internal). The target module structure would be this:

![image](https://user-images.githubusercontent.com/7464735/122756679-6620f100-d29f-11eb-8200-64ab2c2ae41d.png)

The overall project is divided in 2 main phases:

1. Make Flow independent from Hilla internals
2. Make Hilla only dependent on the base (not Flow)

This Epic-level ticket aggregates the overall information for the project, but smaller, more specific tickets will be linked to this one over time. The overall task of modularizing both frameworks is expected to take several platform releases to be complete. 

Note: this ticket has been labeled as `hilla` just because it's been conducted by the Hilla team, but it will impact both frameworks.

## Acceptance criteria
- All modes of operation currently supported in the platform should still be supported after the split. This means Flow, Hilla, Hybrid (Flow and Hilla), Embeddable Flow, Flow with legacy bootstrap.

**Comment by Haprog** [comment]
It's not clear from this issue if the split would practically mean splitting to another repository or just splitting to more logical modules inside the current repository (possibly renaming the current repo to something else so it would be considered kind of like a monorepo). Refactoring the modules inside the flow repo might be a good first step in any case, but still the final goal is not really clear here.
