### ISSUE TITLE
Vaadin Figma Library

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2045]
## Description
A library of pixel-perfect representations of Vaadin components for use with the Figma UI design tool.

## Use cases
As a designer
I want to use pre-made representations of Vaadin components in my designs
So that I can make UI mockups and prototypes quickly and easily

**Comment by vlukashov** [comment]
Release in https://www.figma.com/community/file/843042473942860131/Vaadin-Design-System
