### ISSUE TITLE
Grid performance improvements

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2046]
## Description
Performance improvements to Grid, Grid Pro, TreeGrid and CRUD

## Use cases
As an end-user
I want data grids with good performance
So that I can view tabular data without UI lag

**Comment by uwe72** [comment]
I just can vote for this bugfix! The performance is horrible.

**Comment by tarekoraby** [comment]
@rolfsmeds, should this ticket be closed after the performance improvements introduced with [lazy-column rendering](https://github.com/vaadin/platform/issues/3909) and the other [several enhancements](https://github.com/vaadin/web-components/pulls?q=is%3Apr+is%3Aclosed+label%3Aperformance) released with Vaadin 24.1?

**Comment by tarekoraby** [comment]
@rolfsmeds, should this ticket be closed after the performance improvements introduced with [lazy-column rendering](https://github.com/vaadin/platform/issues/3909) and the other [several enhancements](https://github.com/vaadin/web-components/pulls?q=is%3Apr+is%3Aclosed+label%3Aperformance) released with Vaadin 24.1?

**Comment by rolfsmeds** [comment]
I suppose we could. There might be other performance improvements we could do, but without knowing what those would be, it's not very meaningful to keep this open. We can open new tickets once we have new, actionable ideas of how to further improve performance.
