### ISSUE TITLE
create 14.7 and 20.0 branch. 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#2053]

**Comment by manolo** [comment]
Let's wait until flow-components needs a new platform release or flow has the corresponding branches

**Comment by ZheSun88** [comment]
20.0 branch is needed. otherwise, the npm update script doesn't work, as there is no 20.0 branch in platform 

https://bender.vaadin.com/viewLog.html?buildId=226639&buildTypeId=VaadinFlowComponents_FlowComponentsUpdateNpmPackagesWebjarsVersions&tab=buildLog&_focus=75#_state=75
