### ISSUE TITLE
The start.vaadin.com Dockerfile is not Java 16 compliant

### ISSUE THREAD

**Issue by markhm** [vaadin/platform#2074]
**Describe the bug**
When starting a new project via start.java.com with Java 16, the `Dockerfile` that is supplied is based on Java 11 (see the images `maven:3-jdk-11` and `openjdk:11` in the file). Project that are built with Java 16 need at least Java 16 to run, so failure is expected. I have been able to confirm the failure. 

**To Reproduce**
1. Create a project via start.vaadin.com
2. Select Java 16 and Dockerfile. Download the project.
3. Build and create the docker image with `mvn install`, `docker build .`

The following error is shown.
<img width="1138" alt="Screenshot 2021-05-01 at 08 44 03" src="https://user-images.githubusercontent.com/1430451/116773996-9d221580-aa59-11eb-926f-d930f5700ba2.png">

**Expected behavior**
A correctly built Docker image is provided. 

**Desktop (please complete the following information):**
 - Vaadin platform version 19.0.6
 - Java 16

**Comment by Artur-** [comment]
Thanks, this has been fixed so that it uses JDK 16. Also running "mvn install" first is no more necessary
