### ISSUE TITLE
ConfirmDialog class not found

### ISSUE THREAD

**Issue by fgrazi** [vaadin/platform#2076]
I noticed I can't use the ConfirmDialog class. See attached screenshot for more detail. The project is also attached, but I had to remove the node_modules directory.

[vaadin-test.zip](https://github.com/vaadin/framework/files/6411785/vaadin-test.zip)

![2021-05-02_18-07](https://user-images.githubusercontent.com/28322826/116819889-8c18f780-ab72-11eb-9945-6811baa864a4.png)

Hey, **no hurry**: It just for your information. I had anyway written my own version, before getting stuck with the other issue (#12284).

**Comment by caalador** [comment]
The ConfirmDialog is part of the commercial components as noted in the banner (`This component is included in Vaadin Pro and Prime subscriptions. There is a free 14-day trial available.`) on https://vaadin.com/components/vaadin-confirm-dialog 
To get the import to show you would need to add to Maven pom the dependency 
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin</artifactId>
        </dependency>
```
Which will bring in all the commercial components also.
`vaadin-spring-boot-starter` only depends on `vaadin-core` which only contains non commercial components.
