### ISSUE TITLE
AC: RouteScope for Flow Spring integration

### ISSUE THREAD

**Issue by mstahv** [vaadin/platform#2095]
## Description

Spring integration for Flow don't provide a replacement for ViewScope that we had the Vaadin 8. In CDI integration we have had a RouteScoped annotation and we should bring the functionality in Spring integration to the same level.

Issue in Spring integration repository: https://github.com/vaadin/spring/issues/263

## Use cases

As a Flow developer
I want to share beans/component-state inside a route between different UI subparts/fragments
So that I can use DI to inject the beans to my route classes and control when state is shared and when cleaned up

As a developer using PreserveOnRefresh functionality
I want my RouteScoped beans to be the same after refresh 

As a Vaadin 7/8 developer migrating my application to Flow
I want to have an easy way to migrate my ViewScoped Vaadin 8 views to Flow 
So that I can I use MPR or migrate manually

## Acceptance criteria
- [x] Users are can scope the beans in the application to follow the lifecycle of any routing component
- [x] Users can make beans preserved when the end-user refreshes the page
- [x] Spring documentation has an example how to use RouteScoped bean that is shared by different fragments in the UI that are in same route
- [x] Multiplatform Runtime documentation has clear steps how to migrate ViewScoped parts of Vaadin 8 to Flow

## General criteria

- [x] Design/API reviewed
  * Verify the current design in CDI version has no major flaws. Fix those if need.
  * Prepare use case examples and share those with the interest group.

- [x] Performance 
Ensure the RouteScoped beans are garbage collected when navigating out of the owning view.

- [x] UX/DX tests in Alpha 
If major differences in the implementation compared to CDI counterpart.
https://drive.google.com/drive/u/1/folders/1UCFSUe_kgl8AVxynPu0CLbxPFT1rGgK8

- [x] Documentation: https://vaadin.com/docs/latest/flow/integrations/spring/scopes

- [x] PiT test

Using a Vaadin Spring Boot project 
 * Test that you can tie a bean's lifecycle to the lifecycle of a view
 * Test that you can configure the view and bean to preserve when the browser is refreshed

Optionally
* Given you have used `@ViewScope` in V7/V8, you know how to migrate that to V21

- [x] Limitations:

**Comment by pleku** [comment]
https://github.com/vaadin/spring/issues/263
