### ISSUE TITLE
Consider adding minimum Maven and Gradle versions to the release notes

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2119]
The release notes could benefit from clarifying the minimum Maven and Gradle versions needed to run a Vaadin project. This information is already available internally in the Technology Strategy [document](https://docs.google.com/document/d/174rhIJimwG1fZ7oLzEXqLIUG7A9CWkzXlcUMvT5WgAc/edit#) but it would be good to have as public.

**Comment by ZheSun88** [comment]
good point, we need revisit the release note template and keep the info being updated according to  https://sites.google.com/a/vaadin.com/aslak2-0/processes/technology

**Comment by martaolszewskatusiek** [comment]
Please also check (or update) the corresponding page on vaadin.com ([FAQ](https://vaadin.com/faq#what-technologies-does-vaadin-support)). At the moment, there is no owner for FAQ.

**Comment by ZheSun88** [comment]
Gradle version, together with maven version, has been added to release note template. 
#2144 #2166
