### ISSUE TITLE
Checkbox to boolean binding no longer seems to work in rc5

### ISSUE THREAD

**Issue by davidm76** [vaadin/platform#212]
In our in-house project, binding of a Checkbox to a boolean bean property no longer seems to work.

I have an old copy of the bakery starter project based on 10.0.0.beta3.

I added a boolean field called `archived` to the `User` entity:

```
  public boolean isArchived() { 
    return archived; 
  } 
 
  public void setArchived(boolean archived) { 
    this.archived = archived; 
  } 
 
  private boolean archived; 
```

I added a checkbox to user-form.html:

```
  <vaadin-checkbox id="archived">Archived</vaadin-checkbox> 
```

Then in UserForm.java I added the checkbox and a binding:

```
  @Id("archived")
  private Checkbox archived; 
```
and in `setBinder()` I added a new binding for the new field:

```
binder.bind(archived, "archived");
```

This works as expected and I can edit a user and set and Unser the `archived` property.
See below:
![binder_working_beta2](https://user-images.githubusercontent.com/6536626/41725707-642cdde2-7568-11e8-8003-ee35f47df3cd.gif)

Now, if I do the same with the latest starter, based on rc5, you'll notice that the `archived` checkbox is not being set when the dialog is re-opened:
![binding_not_working_rc5](https://user-images.githubusercontent.com/6536626/41726562-5616ed9a-756a-11e8-91eb-068646f2eebb.gif)

I've attached the projects referenced above:
[vaadin-bakery-app_beta3_working.zip](https://github.com/vaadin/platform/files/2124132/vaadin-bakery-app_beta3_working.zip)

[my-starter-project_rc5_not_working.zip](https://github.com/vaadin/platform/files/2124124/my-starter-project_rc5_not_working.zip)

Thanks.

David.

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-checkbox-flow #60](https://github.com/vaadin/vaadin-checkbox-flow/issues/60) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pleku** [comment]
Thanks for the report, I've moved the issue to the Java integration repository of the web component. You can follow it from there.
