### ISSUE TITLE
vaadin-bom references artifacts not available in Maven central

### ISSUE THREAD

**Issue by mstahv** [vaadin/platform#216]
It would be [a good habit](https://maven.apache.org/repository/guide-central-repository-upload.html) for all artifacts published in maven central to reference only artifacts that are available in maven central. 

This causes issue like these:
https://github.com/spring-io/initializr/pull/694

**Comment by wilkinsona** [comment]
`vaadin-platform-parent` also contains some repository definitions. [Maven's documentation](https://maven.apache.org/repository/guide-central-repository-upload.html) strongly encourages you not to do that.
