### ISSUE TITLE
[BUG] Gradle is listed with the wrong version and linked artifact

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#2163]
**Describe the bug**
Currently (20.0.0) the patch notes mention "Gradle plugin for Flow (1.2)" with a link to https://github.com/devsoap/gradle-vaadin-flow/releases/tag/1.2 - this looks wrong now that gradle is official supported and has the same version as the platform.

Release Notes: https://github.com/vaadin/platform/releases/tag/20.0.0

**Comment by manolo** [comment]
gradle plugin is already in gradle repo https://plugins.gradle.org/plugin/com.vaadin , I updated the release notes, and also the template for it. 
Thanks for reporting
