### ISSUE TITLE
Generate 11.0-SNAPSHOT with actual platform dependencies' snapshots

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/platform#218]
Currently platform build generates `10.0` snapshot with old Flow version (and potentially some other dependencies' snapshots are also outdated).

This makes it impossible to verify starters against the newest Flow snapshot.

We need to: 
* create protected `10.0` branch from the current `master` so that we can release fixes for the `10.0` version
* bump all the versions (in pom.xml, templates and versions.json) in `master` branch to use the latest snapshots and have `11.0` platform version there
* update `flow-starters` to use that version
* update all Bender jobs affected

**Comment by heruan** [comment]
It would also be useful to have 11-alpha releases to start developing with Flow 1.1.0-alpha1 and also components alphas.

**Comment by ripla** [comment]
Let's do this starting from the V11 release (by generating V12 snapshots). @SomeoneToIgnore if possible, it would be great to have the actual targeted versions in master and not just the latest snapshots. We could still have a separate snapshot build, but keep the master clean.

**Comment by ripla** [comment]
Currently platform snapshots are created with the snapshot versions of targeted product versions. Platform alpha versions have pre-release versions of the products.
