### ISSUE TITLE
Tell explicitly that mobile firefox is not supported in release notes

### ISSUE THREAD

**Issue by mhosio** [vaadin/platform#219]
Currently the release notes don't list mobile firefox as a supported browser. Would be better to explicitly tell that it is not supported as long as we have no plans in supporting it.

**Comment by Legioth** [comment]
Devil's advocate wonders why mobile Firefox should have a different position than all the other non-supported browsers such as Samsung Internet, the legacy Android stock browser, UC Browser, Opera mobile and IEMobile (all which are more popular according to statcounter).

**Comment by ripla** [comment]
Agree with @Legioth. We are pretty clear on what browsers we support. We can always improve the current wording in other ways.
