### ISSUE TITLE
Define a version for the vaadin-item webjar in the bom

### ISSUE THREAD

**Issue by Legioth** [vaadin/platform#220]
When doing `mvn dependency:tree` for a project using Vaadin `10.0.1`, the output contains `org.webjars.bowergithub.vaadin:vaadin-item:jar:2.0.0:compile (version selected from constraint [2.0.0,3))`, indicating that the bom does not define a vaadin version for the `vaadin-item` webjar even though it is a transitive dependency of `vaadin-combo-box`.

Could be a good idea to avoid similar situations in the future by adding a test that verifies that the output of `dependency:tree` doesn't contain the string `version selected from constraint`.

**Comment by ripla** [comment]
V11 https://github.com/vaadin/platform/pull/246
V10 https://github.com/vaadin/platform/pull/250
