### ISSUE TITLE
LitElement-friendly TypeScript APIs for components

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2213]
## Description
Convenient Lit-native template rendering in grid, combo-box, select, dialog and notification allows using Lit syntax for data binding.

## Use cases
As a TS-developer
I want convenient Lit-native, Polymer-free rendering APIs in Grid, Combo Box, Select, Dialog and Notification
So that I can use LitElement data binding and not have to learn Polymer

**Comment by web-padawan** [comment]
Lit renderer directives are released in Vaadin 23.1 and the documentation is updated in https://github.com/vaadin/docs/pull/1534. Closing this as done.
