### ISSUE TITLE
Improved configurability of CRUD

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2311]
## Description
API features providing better configurability of the CRUD component.

## Use cases
As a developer
I want access to the buttons in the editor
So that I can disabled them, change their properties, apply my own clicklisteners, etc.

As a developer
I want to toggle the editor toolbar's visibility
So that I can hide it in cases where no actions are to be displayed

As a developer
I want to be able to modify the item initialized when adding a new item
So that I can pre-populate it with default values

## Acceptance criteria
- [x] Getter APIs for editor buttons: `getSaveButton()`, `getCancelButton()`, `getDeleteButton()`
- [x] Setter (and getter) for editor toolbar visibility: `setToolbarVisible(boolean)`, `getToolbarVisible()`
- [x] When hidden, toolbar must be hidden also from screen readers
- [x] NewEvent.getItem() returns the new item
- [x] Documentation for all these improvements added to https://vaadin.com/docs/latest/ds/components/crud

## Related issues
- Access to editor buttons: https://github.com/vaadin/flow-components/issues/1112
- Toolbar visibility toggle: https://github.com/vaadin/flow-components/issues/1592
- New Event: https://github.com/vaadin/flow-components/issues/1105

## General criteria
- [x] [APIs reviewed](https://docs.google.com/spreadsheets/d/1As-OwgUszvvrCzCThsxvC743pcpvwU-bERq8btBD5tM/edit#gid=0)
- [x] UX/DX tests in Alpha; [DX test document](https://docs.google.com/document/d/1-xI2HzU13FMww9VnSG017lK54L9IA36wCHjU8XNOHWQ/edit#heading=h.g1ttyink242t)
- [x] Documentation:  https://vaadin.com/docs/latest/ds/components/crud/
- [x] [How to test?](https://docs.google.com/document/d/1-xI2HzU13FMww9VnSG017lK54L9IA36wCHjU8XNOHWQ/edit#bookmark=kix.zf307kj7njhp)
- [ ] Limitations:

**Comment by mickoyuh** [comment]
Closed by sticky fingers mistake.
