### ISSUE TITLE
Convenience `show` method for NotificationElement

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/platform#2316]
## Description
Providing a static `show` method to `NotificationElement`.

## Use cases
As a developer
I want to use a single method for showing basic notification
So that I can achieve without explicitly setting `renderer`, updating `opened` state, and setting additional properties or parameters.

## Acceptance criteria
- [x] Static `show` method is available on `NotificationElement`
- [x] Method accepts two parameters: `contents` and an `options` object (optional), where options allows to specify additional settings like `duration` and `position`
- [x] `contents` to be of type `string` or a `Lit template`
- [x] Documentation is updated accordingly and simplified on https://vaadin.com/docs/latest/ds/components/notification

## Related issue
- https://github.com/vaadin/web-components/issues/914

## General criteria
- [x] [APIs reviewed ](https://github.com/vaadin/web-components/issues/914)
- [x] UX/DX tests in Alpha; [DX test document](https://docs.google.com/document/d/1-xI2HzU13FMww9VnSG017lK54L9IA36wCHjU8XNOHWQ/edit#heading=h.lsc8jpwnq1r5)
- [x] Documentation:  https://vaadin.com/docs/latest/ds/components/notification/
- [x] [How to test? ](https://docs.google.com/document/d/1-xI2HzU13FMww9VnSG017lK54L9IA36wCHjU8XNOHWQ/edit#heading=h.xgqy0siwb60q)
- [ ] Limitations:

**Comment by tomivirkki** [comment]
The current API suggestion only supports 1. text 2. Lit templates

Would it make sense to also support a renderer function so non-Lit Web Component users could also use the API for creating rich content notifications?

```js
Notification.show(root => {
  // Renderer function
});
```

**Comment by rolfsmeds** [comment]
That's a good idea, but if it can be done later without breaking anything, we could leave it out of this scope and create a new ticket for it instead.
