### ISSUE TITLE
Docs' Maven archetype should be based on stable

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2340]
Vaadin-bot updates the Maven archetype version in the v14 docs with the latest prerelease: https://vaadin.com/docs/v14/guide/start/maven.

This however produces an error as prerelease archetype does not exist (com.vaadin:vaadin-archetype-application:14.7.0.beta1). Vaadin bot should thus only update this page to stable v14 releases.

**Comment by ZheSun88** [comment]
i will fix it in the script..

**Comment by ZheSun88** [comment]
it looks i can push directly to the doc branches. so i fix the script by accident
now here is a PR to overwrite the hardcoded versions: https://github.com/vaadin/docs/pull/710
