### ISSUE TITLE
Improve the frontend build times for Vaadin projects during development

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/platform#2448]
## Description
The build times associated with frontend have been increasing drastically since V14, and it's getting to a point that it's hurting significantly the productivity of the developers using Vaadin (especially Vaadin Flow).

We need to take a step back and reevaluate our build structure and tooling, in order to reduce the waiting time significantly for the developers.

To limit the scope, this issue is about improving the time spent by developers when creating/updating their application in development mode. It doesn't cover production builds.

The project dashboard with specific details can be found at https://github.com/vaadin/flow/projects/3

- [ ] Documentation: 
To be done.

- [ ] How to test? 
Precise instructions on how to enable the new build chain will be added later.

In terms of what needs to be tested: first and foremost, the new build system should not break existing applications, and all use cases supported by the platform during development time should still be supported. In case of exceptions, those exceptions need to be listed explicitly and proper alternative solutions should be investigated.

The builds need to be tested for both Flow and Fusion-based applications.

Once the builds are correct, then the main purpose of this issue (performance) should be evaluated. It needs to be visibly and significantly faster for developers to incrementally create or update their applications, compared to the current build times in V21-based projects.

As a benchmark, the CRM tutorial application ([Flow](https://github.com/vaadin/flow-crm-tutorial), [Fusion](https://github.com/vaadin/fusion-crm-tutorial)) can be used for both QA and developers during the project, in addition to projects generated by [Vaadin Start](https://start.vaadin.com/). 

- [ ] Limitations: 
The initial version of the new build tool chain will be available to existing Vaadin versions, behind either a feature flag or as an external dependency. This will be done to get feedback from the community as soon as possible. Once the new tool chain has matured, it will be included as an official part of the platform - currently aiming for Vaadin 23.

**Comment by Legioth** [comment]
The initial part was delivered behind a feature flag in Vaadin 22. More parts will follow.
