### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2611]
## Description
A "slippy-map" component for displaying interactive maps (based on OpenLayers)

## Use cases
As a developer
I want to embed an interactive map in my app
So that I can show stuff on a map

## Acceptance criteria
(API below refers to Flow API only for now)

### General component API
- [ ] Web Component element `<vaadin-map>`
- [ ] Flow component class `Map`

### Base map layer data API
- [ ] Generic API for TMS / WMS / WMTS (whatever makes the most sense)
- [ ] Defaults to using OpenStreetMap data from OSM's own servers (tile.openstreetmap.org)
- [ ] API for specifying a custom url for OSM data ([OL API](https://openlayers.org/en/latest/apidoc/module-ol_source_OSM-OSM.html))
- [ ] **(nice to have)** API for specifying Bing maps data ([OL API](https://openlayers.org/en/latest/apidoc/module-ol_source_BingMaps-BingMaps.html))

### Map position and zoom
- [ ] API: Setting map position (Long/Lat) and zoom level

### Events
- [ ] API: Map click events from UI
- [ ] API: Map pan and zoom events from UI

### Geometry
- [ ] API: Add points
- [ ] API: Click events from points
- [ ] API: Make points draggable
- [ ] **(nice to have)** API: Add lines and polygons
- [ ] **(nice to have)** API: Click events form lines and polygons

### Markers (really just points with an icon in OpenLayers API)
- [ ] API: Add marker (point styled with a predefined marker symbol)
- [ ] **(nice to have)** API: Provide custom marker image

### Misc
- [ ] API: Disabled state (all interaction disabled)
- [ ] API: Set attribution
- [ ] Tab-index (for keyboard accessibility)
- [ ] **(nice to have)** API: Disable panning, zooming
- [ ] **(nice to have)** API: Toggle visibility of UI control (zoom, rotate)
- [ ] License check

## General criteria
- [ ] APIs reviewed 
- [ ] Design (zoom controls) 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: (add new page to Design System components documentation) 
- [ ] How to test? 
- [ ] Limitations:

**Comment by jojule** [comment]
"Learn more" link in development mode UI links to this ticket. How about linking instead to the documentation?

**Comment by rolfsmeds** [comment]
Good catch @jojule – a leftover from development before we had documentation for it, we'll change it to point to docs.
