### ISSUE TITLE
Auto update hardcoded versions in docs' upgrade tool

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2626]
### Describe your motivation

The docs has now an [upgrading tool](https://github.com/vaadin/docs/blob/latest/frontend/demo/upgrade-tool/upgrade-tool.ts) that includes some hardcoded Vaadin versions starting from [L16](https://github.com/vaadin/docs/blob/570b466221837e7f0176a7b3cc2937c9f7b1d897/frontend/demo/upgrade-tool/upgrade-tool.ts#L16):
```
const VAADIN_VERSIONS: Record<string, string> = {
  14: '14.8.1',
  15: '15.0.6',
  16: '16.0.5',
  17: '17.0.11',
  18: '18.0.7',
  19: '19.0.9',
  20: '20.0.8',
  21: '21.0.9',
  22: '22.0.2',
};
```

Those versions need to be updated automatically both when a new minor is released (e.g. 14.8.1 should be changed to 14.8.2) as well as when a new major is released (e.g. a new entry should be added for v23 is out).

**Comment by ZheSun88** [comment]
this has been add now. 
example PR -> https://github.com/vaadin/docs/pull/1122
