### ISSUE TITLE
Vaadin 23 for Java 8

### ISSUE THREAD

**Issue by dgrec** [vaadin/platform#2636]
### Describe your motivation

Java 8 still are very popular in productions. 

Please, can you keep support for Java 8 in Vaadin 23?

**Comment by Artur-** [comment]
Hi

we will keep supporting Java 8 through Vaadin 14 for many years to come, first for free and then through commercial options. For Vaadin 23 we will move forward with the rest of the Java ecosystem, see https://github.com/vaadin/flow/issues/12260
