### ISSUE TITLE
Use npm as the default frontend package manager

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/platform#2637]
### Why are we using pnpm?
Currently, Vaadin uses pnpm (also known as performant npm) as the default frontend package manager. `pnpm` gives 2 benefits: performance and the ability to lock the transitive dependency versions. 

### Why should we switch to npm?

- Now npm performance is on par with pnpm (see [details](https://github.com/vaadin/flow/issues/9835)). 
- The version locking feature relies on the `--shamefully-hoist` flag which is highly discouraged.
- npm 8  also delivers an `overrides` [feature](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) that allows locking the versions.

## Use cases
As a developer, I can install frontend dependencies with `npm i xyz`.

## Acceptance criteria
- [x] A new project is using npm by default.
- [x] A user can still switch between npm and pnpm with `pnpm.enable` flag.
- [x] A user can install client-side dependencies with `npm i xyz`.
- [x] Upgrade guide is provided.

## General criteria

- [x] Performance: Performance has been tested and deemed acceptable. Performance degradation due to removal of lockfile [has been addressed](https://github.com/vaadin/flow/issues/12825).

- [x] UX/DX tests in Alpha: Has been tested and multiple issues [here](https://github.com/vaadin/platform/issues/2681) uncovered and fixed.

- [x] Documentation: https://vaadin.com/docs/latest/flow/configuration/npm-pnpm; Upgrade guide in docs: https://github.com/vaadin/docs/pull/1067

- [x] How to test? Change tested by upgrading many existing projects. See issues in https://github.com/vaadin/docs/pull/1067

- [x] Limitations: Larger project size due to `node_modules` not containing symlinks.

**Comment by Avec112** [comment]
While performance is one thing what about the fact that npm created large module packages inside each and every project while pnpm only linked them. This is/was the biggest advantage with pnpm over npm in my opinion. Have this changed so npm also just linkes all dependencies now? I hope we are not going back to project sizes of over 100Mb because npm is not symlinking dependencies like pnpm does.
https://pnpm.io/pnpm-vs-npm
https://pnpm.io/symlinked-node-modules-structure

**Comment by joheriks** [comment]
The decision to change the default package manager was also influenced by the `overrides` feature (which allows a clean solution for pinning platform dependencies in contrast to pnpm). Note that it is still possible to use `pnpm` for cases where desired.
