### ISSUE TITLE
Release 10.0.3

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#271]
Once all of https://github.com/vaadin/platform/labels/v10 are done, release platform 10.0.3. Remember to update vaadin.com as well.

**Comment by alvarezguille** [comment]
https://github.com/vaadin/platform/releases/tag/10.0.3 released
vaadin.com not updated as latest version of some component still don't have demo artifact deployed (for instance: https://repo.maven.apache.org/maven2/com/vaadin/vaadin-text-field-flow/1.0.3/ )
