### ISSUE TITLE
We are migrating our Code base from vaadin 7.2.6 to vaadin 14.8.1. We are experiencing many issues.

### ISSUE THREAD

**Issue by swatijain20** [vaadin/platform#2712]
### Describe the bug

Error Screenshot are attached, as we were facing while starting the server with vaadin 14.

### Reproduction

We are migrating our Code base from vaadin 7.2.6 to vaadin 14.8.1. We are experiencing many issues. We started jetty server and facing the issue.

### System Info

vaadin version: 14.8.1
jsoup version: 1.14.3

**Comment by TatuLund** [comment]
This issue tracker is not the best place to post generic questions. You probably will face lot of questions during your migration process, I would recommend to reach for help in our Discord channel here: https://discord.com/channels/732335336448852018/774366825756229632
