### ISSUE TITLE
Generate javadoc for the vaadin artifact

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#275]
Generate and deploy javadoc for the vaadin artifact in addition to vaadin-core. The whole platform javadoc should be made available in vaadin.com/api. Related to #153 and #105.

**Comment by alvarezguille** [comment]
what about testbench? 
vaadin artifact will not include javadoc for testbench (vaadin-testbench-core and vaadin-components-testbench) as it's not a dependency

**Comment by ripla** [comment]
@alvarezguille good point, TB should be included. The end goal is to get the whole platform api available in one package so it can be consumed by vaadin.com/api. I think the actual mechanism on how to get that doesn't matter.

**Comment by Legioth** [comment]
I guess we could define an internal meta module that depends on `vaadin` and `testbench` and generate javadocs based on that, assumed that we find a good way of getting javadocs for transitive dependencies.
