### ISSUE TITLE
Auto update use-case demos

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2750]
### Describe your motivation

vaadin-bot should update the v14 and v23 branches of the following repos:
https://github.com/vaadin/bookstore-example
https://github.com/vaadin/vaadin-form-example
https://github.com/vaadin/layout-examples
https://github.com/vaadin/vaadin-leaflet-example
https://github.com/vaadin/vaadin-localization-example
https://github.com/vaadin/vaadin-rest-example
https://github.com/vaadin/vaadin-database-example
https://github.com/vaadin/addon-starter-flow

The master branch should be updated to the latest stable (today, that's 22.0.6).

Note also, that the bookstore-example repo has one extra branch, the `rtl-demo` branch, that should also be updated regularly (in addition to the v14 and master branches of the repo).

**Comment by ZheSun88** [comment]
added to the build.

**Comment by tarekoraby** [comment]
For the bookstore-example, the bot is correctly updating the v14 and rtl-demo branches. But it's not updating the v23 branch.

**Comment by ZheSun88** [comment]
updated
