### ISSUE TITLE
Auto update Flow and Hilla tutorials

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2753]
### Describe your motivation

vaadin-bot should update the v14 and main branches of https://github.com/vaadin/flow-crm-tutorial.

It should also auto update the main branch of https://github.com/vaadin/hilla-crm-tutorial.

**Comment by ZheSun88** [comment]
Add to the starter update list.

**Comment by ZheSun88** [comment]
need to revisit for the hilla-crm-tutorial, this is using the hilla version instead of flow version.

**Comment by ZheSun88** [comment]
both starter have been added to starter update build
