### ISSUE TITLE
release notes contains wrong links

### ISSUE THREAD

**Issue by dominik42** [vaadin/platform#2762]
### Describe the bug

The release notes for the latest 23.0.0.beta4 and maybe any other contains wrong links for the some sub components:

- Collaboration Engine
- Spring add-on
- OSGi plugin 

### Reproduction

Go to https://github.com/vaadin/platform/releases/tag/23.0.0.beta4 and click the links for 

- Collaboration Engine
- Spring add-on
- OSGi plugin 

### System Info

Pre-release 23.0.0.beta4 - Vaadin 23 release notes 
https://github.com/vaadin/platform/releases/tag/23.0.0.beta4

**Comment by ZheSun88** [comment]
Thanks for letting us know i will correct the links for release note.  🙇

**Comment by dominik42** [comment]
The link for Collaboration Engine is still wrong

https://github.com/vaadin/platform/releases/tag/23.0.0.rc1 contains
https://github.com/vaadin/collaboration-engine/releases/tag/5.0.0.rc1 which is invalid.

**Comment by heruan** [comment]
Thank you @dominik42 for reporting this: now Collaboration Engine links are fixed for both releases.

**Comment by dominik42** [comment]
release notes for Vaadin 14.8.7 https://github.com/vaadin/platform/releases/tag/14.8.7
contains wrong link to https://github.com/vaadin/spring/releases/tag/12.4.3
