### ISSUE TITLE
Java API for Lumo utility classes

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2784]
## Description
Java API for [Lumo utility classes](https://vaadin.com/docs/latest/ds/foundation/utility-classes)

## Acceptance criteria
- [x] Added to `com.vaadin.flow.theme.lumo.Lumo` package
- [x] Separate enums for different categories of classes (`Background`, `BorderRadius`, `Shadow`, `Margin`, `Padding`, etc...)
- [x] Human-friendly names (e.g. `Padding.VERTICAL_XLARGE`* rather than `Padding.Y_XL`)

(* `XLARGE` is preferrable over `XL` as the former is consistent with theme variants like `AvatarVariant.LUMO_XLARGE`)

## General criteria
- [x] Documentation: https://vaadin.com/docs/latest/ds/foundation/utility-classes
- [x] UX/DX tests in Alpha 
- [x] How to test?

**Comment by anezthes** [comment]
Initial attempt here: https://github.com/vaadin/flow-components/pull/2787

Feedback welcome!

**Comment by jouni** [comment]
That would be completely manually maintained, right? I wonder if we should spend time in setting up some automation already, or do we trust to keep these manually in sync?

**Comment by knoobie** [comment]
Should the nested classes like right/left be renamed to PaddingRight and MarginRight to make sure you can see what it is inside the IDE directly without expanding the imports?

Example:

![image](https://user-images.githubusercontent.com/3968629/163668347-51f49061-f324-48b7-8ecc-df792f6ae266.png)

I've literally no idea (thanks to auto-import) what this Right class stands for on first glance (Spoiler: MarginRight)

**Comment by knoobie** [comment]
Note about the docs on mobile: looks kinda out of place :) 

![20E3BB5B-91DF-48F0-9D9E-5A622EAE5418](https://user-images.githubusercontent.com/3968629/163722958-004b1ff7-0dff-477a-873a-e8da0db17749.png)

**Comment by rolfsmeds** [comment]
> Should the nested classes like right/left be renamed to PaddingRight and MarginRight to make sure you can see what it is inside the IDE directly without expanding the imports?

We discussed this today and decided to leave the (java) class names as-is, as the developer can choose to spell out the full (or at least a _fuller_) class paths to make his code more clear, and also because we have utility classes like `FontSize.Breakpoint.Small.LARGE` that would need to be renamed to `FontSize.FontSizeBreakpoint.FontSizeBreakpointSmall.LARGE` (or at least to `FontSize.Breakpoint.FontSizeBreakpointSmall.LARGE`), which doesn't seem worth the added verbosity.

We might still re-evaluate later (and do the deprecation dance) this if we get contraindicative feedback once this API is in wider use.
