### ISSUE TITLE
Review vaadin-bot update of starters and examples

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2794]
Recently, we have decided to no longer use "main/master" as a branch name for our starters and examples. We, thus, renamed those branches in many starters to "v23".  So, it would be good to review that vaadin-bot will auto-update the starters appropriately.

Repos that have v14, v22, v23:
- skeleton-starter-flow-spring
- skeleton-starter-flow
- skeleton-starter-flow-cdi
- base-starter-spring-gradle
- base-starter-gradle
- base-starter-flow-osgi

Repos that have v22 and v23:
- base-starter-flow-quarkus
- vaadin-flow-karaf-example

Repos that have v14 and v23
- vaadin-database-example
- vaadin-localization-example
- vaadin-rest-example
- flow-crm-tutorial
- flow-quickstart-tutorial
- vaadin-form-example
- bookstore-example
- component-starter-flow
- addon-starter-flow

Hilla tutorials remain the same with a single main branch:
- hilla-basics-tutorial
- hilla-quickstart-tutorial
- hilla-crm-tutorial

**Comment by ZheSun88** [comment]
list has been checked. 
now let use the next releases to verify.

**Comment by ZheSun88** [comment]
now it is time to close this ticket
