### ISSUE TITLE
Auto update designer-tutorial repo

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#2812]
### Describe your motivation

Please auto update the branches of the https://github.com/vaadin/designer-tutorial repo.

The following branches should be updated to vLatest:

- [latest-initial](https://github.com/vaadin/designer-tutorial/tree/latest-initial)
- [latest-complete](https://github.com/vaadin/designer-tutorial)

The following branches should be updated to v14:

- [v14-initial](https://github.com/vaadin/designer-tutorial/tree/v14-initial)
- [v14-complete](https://github.com/vaadin/designer-tutorial/tree/v14-complete)

**Comment by ZheSun88** [comment]
added to the build
