### ISSUE TITLE
Grid feature: Freeze columns to the right

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2819]
## Description
Support for freezing Grid column to the right, so that they remain static when scrolling the Grid horizontally (in addition to the current support for freezing them to the left).

This is useful e.g. for row-action columns with buttons that invoke actions on the item, which are typically placed at the right end of the row, but suffer from discoverability issues if the user needs to scroll to see them.

Original feature request: https://github.com/vaadin/web-components/issues/2046

## Acceptance criteria
- [x] WC API for freezing columns to the right
- [x] Java API for freezing columns to the right
- [x] Simultaneously freezing different columns to the left and right does **not** need to be supported (but if not supported, the API should be designed in a way that makes that obvious)
- [x] Ensure other column features like resizing and dragging still work as expected

## General criteria
- [x] Documentation: https://vaadin.com/docs/latest/ds/components/grid/#column-freezing
- [x] APIs reviewed (will be evaluated as part of DX tests)
- [x] Performance (ensure Grid performance is not affected negatively) 
- [x] UX/DX tests in Alpha 
- [x] How to test? 
- [x] Limitations: Resizing end-frozen column only possible when overlaid other columns.

**Comment by knoobie** [comment]
@rolfsmeds this feels like https://github.com/vaadin/platform/issues/2786 :)

**Comment by rolfsmeds** [comment]
d'oh! 🙈

(closing that one, keeping this one)

**Comment by web-padawan** [comment]
A very old prototype: https://github.com/vaadin/web-components/issues/2046#issuecomment-245858821

**Comment by probert94** [comment]
Freezing columns is a nice feature, but it only works well, if the frozen column is either the first (or the last) or all previous columns are frozen too. Freezing a column in the middle of the grid is currently possible but usually doesn't make sense and looks pretty strage:
![image](https://user-images.githubusercontent.com/18258317/165935381-f04881c3-e23b-45f5-bab2-ada5184af8c0.png)

In my opinion, it would be even more usefull, if we could define "sticky" columns, that just don't scroll out of view on either side.
Related issue: vaadin/web-components#1481
