### ISSUE TITLE
Is Firefox ESR still supported?

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#2923]
### Describe your motivation

FIrefox ESR (often used in big companies) isn't listed as supported technology in the latest 23.0 Release (https://github.com/vaadin/platform/releases/tag/23.0.0)

### Describe the solution you'd like

Firefox ESR 91+ is supported by Vaadin.

**Comment by ZheSun88** [comment]
yeah, you are correct. I will update the release note.

Thanks for reporting this.
