### ISSUE TITLE
PiT v23.1

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#2982]
- [x] https://github.com/vaadin/skeleton-starter-flow-cdi/issues/406
- [x] https://github.com/vaadin/base-starter-flow-osgi/issues/161
- [x] https://github.com/vaadin/start/issues/1940
  - [x] https://github.com/vaadin/web-components/issues/3887
- [x] https://github.com/vaadin/start/issues/1939
- [x] https://github.com/vaadin/vaadin-flow-karaf-example/issues/97
- [x] https://github.com/vaadin/base-starter-flow-osgi/issues/222
- [x] https://github.com/vaadin/base-starter-flow-osgi/issues/224
- [x] https://github.com/vaadin/skeleton-starter-flow-cdi/issues/431

Although this [issue](https://github.com/vaadin/vaadin-flow-karaf-example/issues/100) was identified during the PiT process, is an old issue already present in 23.0, though not linking it as a task

**Comment by ZheSun88** [comment]
Karaf example has been fixed after bumping the karaf-plugin version and configuration. https://github.com/vaadin/vaadin-flow-karaf-example/pull/98
OSGi starter is working now after updating the license-checker-plugin. https://github.com/vaadin/base-starter-flow-osgi/pull/223
