### ISSUE TITLE
AC: License Checker: offline mode

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#2984]
## Description
Be able to work with Vaadin Prime products offline (working without an internet connection) or behind a firewall/proxy (when working in a corporate environment).

## Use cases
As a *developer*
I want Vaadin License Checker to use the license stored locally on my computer
So that I can download the license and then use Vaadin Prime features working offline or behind a firewall/proxy.

## Acceptance criteria
- [ ] Offline license key is downloaded from `vaadin.com` and stored locally on developer's computer in a dedicated folder
- [ ] When license check starts, if a normal license key is present locally, License Checker checks it, otherwise steps to offline checking
- [ ] Once normal key validation fails due to connection or other license server error, the License Checker looks into offline license key stored locally or given as a system property

## General criteria

- [ ] APIs reviewed 

- [ ] Design 

- [ ] Performance 

- [ ] UX/DX tests in Alpha 

- [ ] Documentation: 

- [ ] How to test? 

- [ ] Limitations:

**Comment by Artur-** [comment]
In 23.2, you can turn on the feature flag "Old license checker" to keep the project working until you have had time to fetch the offline license you need. The feature flag will be most likely be removed in 23.3
