### ISSUE TITLE
Create a script to generate vaadin/bower.json and vaadin-core/bower.json based on metadata

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#3]
Using the metadata file created in #2, generate one `bower.json` file for each section, containing the defined dependencies. `#version#` in the file should be replaced by the current release version, given as a parameter to the script. The generated `bower.json` should also contain all versions for all dependencies, e.g. lock down the used Polymer dependency to a specific version (2.0.2). Must also make sure that all generated `bower.json` files use the same Polymer version, i.e. `vaadin` cannot use Polymer 2.0.1 when `vaadin-core` uses 2.0.2 or vice versa

For each section
* clone the corresponding GitHub repository
* create a new temporary branch named `staging-#version#`
* commit the generated bower.json
* push the changes

**Comment by ripla** [comment]
This is working already.
