### ISSUE TITLE
V12-SNAPSHOT uses spring version 10.0-SNAPSHOT instead of 10.1-SNAPSHOT

### ISSUE THREAD

**Issue by mikotin** [vaadin/platform#303]
Used snapshot version of spring is v10 snapshot version, instead of right one.

Root of cause is in versioning of vaadin-spring not working with automatic snapshot -version generation.

**Comment by alvarezguille** [comment]
Will be fixed once vaadin-spring 10.1.x release or pre-release is included in `version.json`

**Comment by alvarezguille** [comment]
Fixed in #305
