### ISSUE TITLE
Grid MultiSort Priority Modes

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3052]
## Description
The Grid's multi-column sort feature currently behaves in a way that is very unintuitive and impractical for some users, in that whenever a column's sorting is added (i.e. an unsorted column is sorted) or modified (by changing the sort direction), that column becomes the primary sorting column. Since some users prefer the current behavior, APIs will be added for choosing between the current and new behavior, and a feature flag for controlling the default.

## Longer description

The _sort priority_ (visually indicated by numbers in column headers) determines the order in which the rows of a Grid are sorted, so that the column with priority 1 is evaluated first, followed by the column with priority 2, whereby any rows with the same value in the first sorted column are sorted amongst each other according to the second priority column.

As an example, a Grid multi-sorted by _First name_ (priority 1) and _Last name_ (priority 2), would first be sorted according to First name, ignoring other columns:

| First name¹ | Last name² |
| --- | --- |
| Anne | Smith |
| Anne | Larsen |
| Bob | Johnson |

Then it would be sorted by _Last name_, so that any rows with the same value in _First name_ are sorted _amongst each other_ according to _Last name_:

| First name¹ | Last name² |
| --- | --- |
| Anne | Larsen |
| Anne | Smith |
| Bob | Johnson |

### Current behavior

Whenever an unsorted column is sorted, or the sort-direction of a column is changed, that column gets sort priority 1. If you want to achieve the sorting described in the example above, you need to first sort _Last name_, and then _First name_.

### New behavior

The sort priorities of columns is never unless the user unsorts columns (i.e. removes them from the sort priority). Sorting an unsorted column adds it to the "end" of the sort priority (i.e. assigns it the lowest priority), and changing the sort direction of an already sorted column retains its previous sort priority. The sorting described above can be achieved by first sorting _First name_, then _Last name_.

### Flow
An overload is added to the setMultiSort(boolean multiSort) method, for providing the desired behavior, and an Enum is introduced for the two behavior options:
`setMultiSort(boolean multiSort, MultiSortPriority multiSortPriority)`
Usage:
`setMultiSort(true, MultiSortPriority.APPEND)` (new behavior)
`setMultiSort(true, MultiSortPriority.PREPEND)` (old behavior)
### Web Component
`<vaadin-grid multi-sort multi-sort-priority="append">` (new behavior)
`<vaadin-grid multi-sort multi-sort-priority="prepend">` (old behavior)

## Acceptance criteria
- [ ] New behavior details: see "New behavior" description above.
- [ ] WC API for setting the multisort-priority mode
- [ ] Flow API for setting the multisort-priority mode
- [ ] With no multisort-priority mode defined, the default behavior is used
- [ ] Default behavior controlled by feature flag: when flag enabled, new behavior is used.

## Open questions:
- [ ] Should the feature flag be enabled by default in the minor version in which this feature is introduced?

## General criteria
- [ ] APIs reviewed 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: 
- [ ] How to test? 
- [ ] Limitations:

**Comment by web-padawan** [comment]
Question about `multi-sort-priority="prepend"`: would it be better to use a boolean property for the web component?
I don't think we expect a third option here to be added in the future. My only concern in this case is the property name.

This is somehow similar to `primary-section="drawer"` and `primary-section="navbar"` in `vaadin-app-layout`.

**Comment by rolfsmeds** [comment]
We considered that, but a single boolean (like, say, `append-sort-columns`) wouldn't support reverting the behavior once it becomes the default, which we intend to do at some point, so we'd need _two_ boolean properties in that case.

API proposals are very welcome, however.

**Comment by Legioth** [comment]
> Since some users prefer the current behavior [...] a feature flag for controlling the default

I somehow get the impression that this feature flag would remain present "forever" as a way of allowing those who prefer the non-default setting to keep it as such? While we haven't explicitly defined exactly what to use feature flags for, I have at least been assuming that it's only for things that will eventually be removed since we would otherwise end up with an ever growing list of flags in the UI.

Might a static configuration option tied to the component's own namespace be more appropriate for a "permanent" flag?

**Comment by web-padawan** [comment]
> Might a static configuration option tied to the component's own namespace be more appropriate for a "permanent" flag?

We could consider a static method e.g. `Grid.setDefaultMultiSortyPriority(MultiSortPriority.APPEND))` instead.

However, it would most likely have the same implications as the recently added `Map.setUserProjection()`:

> This method should be called before creating any maps. Changing this setting does not affect existing maps, specifically the component does not convert coordinates configured in an existing map into the new projection. Instead, existing maps should be recreated after changing this setting.

If we agree to make it this way, I can update the web component to delay checking the default property value until the component instance is created. Then we would be able to remove the feature flag from Flow.

**Comment by Legioth** [comment]
Even with that timing gotcha, I would say that the static method is an acceptable tradeoff since it avoids the situation where our list of feature flags would gradually grow longer and longer.
