### ISSUE TITLE
Vaadin 8.3.3 drag and drop grid headers columns are not working on google chrome

### ISSUE THREAD

**Issue by rodrifmed** [vaadin/platform#307]
When you try to change header columns position, on google chrome you can drag to few positions, not all positions, seems to be blocked in some cases, really weird.

Same problem does not happen on firefox

**Comment by pleku** [comment]
Issue moved to [vaadin/framework #11186](https://github.com/vaadin/framework/issues/11186) via [**ZenHub**](https://www.zenhub.com/)
