### ISSUE TITLE
Missing `vaadin-versions.json` for dev.hilla:hilla

### ISSUE THREAD

**Issue by platosha** [vaadin/platform#3089]
### Describe the bug

After the platform pinned versions split, Flow frontend tasks take `vaadin-versions.json` or `vaadin-core-versions.json` resources into use. The `dev.hilla:hilla` artifact was not updated accordingly yet.

As a result, webpack fails to compile TypeScript views in a Hilla project because web components cannot be resolved.

### Expected-behavior

`dev.hilla:hilla` 1.2-SNAPSHOT has `vaadin-versions.json` resource.

Upon starting the development server with a Hilla project without prior `node_modules` installed, Vaadin components are automatically installed from npm.

### Reproduction

1. Start a new Hilla project using `1.2-SNAPSHOT` version of the Hilla platform dependency. Alternatively, remove `node_modules` in an existing up-to-date project.
1. Start the development server normally to run frontend `package.json` update and npm install tasks.

### System Info

Hilla 1.2-SNAPSHOT

**Comment by ZheSun88** [comment]
oh,i see.. this place needs to be modified after the recent split.. 
https://github.com/vaadin/platform/blob/master/hilla/pom.xml#L131

and one thing to mention here, do we need to separate the versions.json here too?
