### ISSUE TITLE
Auto update the Hilla branch of docs

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#3153]
### Describe your motivation

Please automatically update Vaadin and Hilla versions in the `pom.xml` of the docs' Hilla branch: https://github.com/vaadin/docs/tree/hilla.

The opened PRs should also include an updated `package.json` and `package-lock.json`.

**Comment by ZheSun88** [comment]
step has been added to the build.. let us see with the new 23.2 release.

**Comment by ZheSun88** [comment]
example PR. https://github.com/vaadin/docs/pull/1621

let us close this ticket
