### ISSUE TITLE
Hilla: add engine to platform artifacts

### ISSUE THREAD

**Issue by platosha** [vaadin/platform#3157]
Hilla platform artifacts require the following changes to ship the multi-module engine:

- `dev.hilla:hilla` should include the `engine-runtime`
- `dev.hilla:hilla-maven-plugin` should include `engine-maven-plugin`

**Comment by ZheSun88** [comment]
so this is pending  for 
- [ ] https://github.com/vaadin/hilla/issues/481 
- [ ] https://github.com/vaadin/hilla/issues/480
