### ISSUE TITLE
Vaadin uses old version of JSOUP which is binary incompatible with newer versions

### ISSUE THREAD

**Issue by benstpierre** [vaadin/platform#3187]
### Describe the bug

It appears that as of 23.1.6 Vaadin uses JSOUP 1.14.3.  In JSOUP 1.15.3 There was a breaking change where Whitelist was replaced with Safelist as the term "Whitelist" is considered racist.  https://jsoup.org/news/release-1.15.1

We cannot use the new version of JSOUP because vaadin depends on the old version and uses the Whitelist class.

This should be a pretty small fix for Vaadin.

### Reproduction

Try to uses JSOUP 1.15.1 in a Vaadin 23 app and it will break.

### System Info

Happens on all systems.

**Comment by knoobie** [comment]
The new jsoup version can be used with 23.2 by default. In 23.1 you have to do some more work to get it to work without breaking stuff.

**Comment by ZheSun88** [comment]
we are working on [a fix](https://github.com/vaadin/flow/pull/14448) to make the new jsoup version working with V23.1 and older vaadin versions

**Comment by nittka** [comment]
Timely fixes for Vaadin 8 and Vaadin 14 would be quite important as well. Do I understand correctly, that you may not update the dependency directly, but will make sure that your code will be compatible with 1.15.X, so that we can package an updated version safely?

**Comment by knoobie** [comment]
Vaadin (flow) releases 14-23.2 with a fix including the transitive dependency are already on the way. An update for v8 (8.17) as extended maintenance release is prepared by Tatu as well.

**Comment by ZheSun88** [comment]
Vaadin `23.2.0`, `23.0.16`, `14.8.17` and `8.17.0` have been released with the Jsoup version updates. 

soon there will be 23.1.9 and 10.0.21.
