### ISSUE TITLE
PiT 23.2 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#3199]
`23.2.0.beta1` has been released. 

the following issues need to be addressed. 

- hilla dependency versions have been wrongly upgrade in package.json in docs repo 
  - PR looks like [this](https://github.com/vaadin/docs/pull/1620/files) and thread has been opened [here](https://vaadin.slack.com/archives/CDNTYMS9H/p1660560913574079)
- skeleton-starter-spring update failed https://github.com/vaadin/skeleton-starter-flow-spring/pull/840
  - conversation is going on [here](https://vaadin.slack.com/archives/CACKS4075/p1660564957133189)
  - https://github.com/vaadin/flow/issues/14355

**Comment by manolo** [comment]
copied content in https://github.com/vaadin/platform/issues/3086
