### ISSUE TITLE
Auto update hard-coded Vaadin version in docs

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#3220]
### Describe your motivation

After https://github.com/vaadin/docs/pull/1654, we need the Vaadin bot to automatically update the hard-coded Vaadin version in the docs. This should happen for stable versions only (not pre-releases).

This is the file that should be updated: https://github.com/vaadin/docs/blob/latest/articles/_vaadin-version.adoc.

Please note that we now no longer need the bot to update `custom-theme-packaging.asciidoc` file (which it did in this [PR](https://github.com/vaadin/docs/pull/1647) for example). However, the bot should still continue to update `frontend/demo/upgrade-tool/upgrade-tool.ts` (which it did latest in this [PR](https://github.com/vaadin/docs/pull/1648)).

**Comment by ZheSun88** [comment]
updated the script used for version updating 
https://github.com/vaadin/docs/pull/1670
