### ISSUE TITLE
enhancement request - Integration of Vaadin with jHipster

### ISSUE THREAD

**Issue by jnsunkersett** [vaadin/platform#331]
Hello,

Spring Boot is only creating server side code (with or without Vaadin depending on the option selected).

So now people are adopting jHipster which gives a UI bundle as well. 
So suggesting Vaadin be integrated with jHipster and appropriate code  generated.

thanks
Jeevan

**Comment by ripla** [comment]
Hi! Thank you for your suggestion. Unfortunately, JHipster integration is not currently on our roadmap.

**Comment by pleku** [comment]
Out of curiosity, what type of UI would you want to create @jnsunkersett, Polymer based or Java based (using Vaadin Flow) ?

It is true that the start.spring.io doesn't create any example UI for you. But you can create an Vaadin Spring Boot project with https://vaadin.com/start/latest/project-base-spring and it will have a UI stub.
