### ISSUE TITLE
Funnel type charts do not work inside Vaadin Board

### ISSUE THREAD

**Issue by Wnt** [vaadin/platform#335]
Sometimes browser console displays error:
`TypeError: Cannot read property 'textOverflow' of undefined`
sometimes it just silently fails to render correctly.
![image](https://user-images.githubusercontent.com/886091/46681182-f8196600-cbea-11e8-8f9f-367ede246732.png)

Using Vaadin platform 11.0.1, vaadin-charts-flow-6.1.0 and vaadin-board-flow-2.0.2

```java
public class MainView extends VerticalLayout {

	public MainView() {
		DataSeries dataSeries = new DataSeries("Unique users");
		dataSeries.add(new DataSeriesItem("Website visits", 15654));

		Chart chart = new Chart();

		Configuration conf = chart.getConfiguration();

		conf.setTitle("Sales funnel");
		conf.getLegend().setEnabled(false);

		PlotOptionsFunnel options = new PlotOptionsFunnel();
		options.setReversed(false);
		options.setNeckWidth("30%");
		options.setNeckHeight("30%");

		options.setWidth("70%");

		dataSeries.setPlotOptions(options);
		conf.addSeries(dataSeries);

		Board board = new Board();
		board.addRow(new Span("asd"), chart);
		board.setSizeFull();
		add(board);
	}

}
```
```xml
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-board-flow</artifactId>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-charts-flow</artifactId>
        </dependency>
```

[minimal project to reproduce the problem](https://github.com/vaadin/platform/files/2461142/board_funnel_charts_render_problem.zip)

**Comment by alvarezguille** [comment]
Fixed in [vaadin-charts v6.2.0-alpha2](https://github.com/vaadin/vaadin-charts/releases/tag/v6.2.0-alpha2) and [vaadin-charts-flow 6.2.0.alpha3](https://github.com/vaadin/vaadin-charts-flow/releases/tag/6.2.0.alpha3)
