### ISSUE TITLE
AC: Azure Kit

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#3367]
## Description
The Azure Kit enables teams to seamlessly deploy and operate Vaadin Java-based applications built using Flow on Azure Cloud. The Kit helps teams quickly create Vaadin apps that are scalable, highly available, and user-friendly. The Kit is also based on Kubernetes to minimize the risk of cloud-provider lock-in. 

## Use cases
The Azure Kit aims to address the following objectives:
- **Cost:** reduce TCO by hosting our web apps in the cloud, while still being able to scale them up and down as needed to optimize costs
- **Staff productivity:** minimize time spent on managing infrastructure, allow teams to focus on building features and improving the product
Operational resilience: enhance the availability and usability of Vaadin apps
- **Business agility:** respond to changing business needs quickly by scaling up or down as needed, and by launching new features and products faster and with minimal downtime
- **Minimize risk of vendor lock-in:** be able to move web apps to another cloud provider if needed.

## Acceptance criteria
- [x] Provide a Kubernetes-based solution for deploying Vaadin-apps to Azure
- [x] Enable Vaadin apps to scale up and down in a non-disruptive manner. The scaling up/down events should preferably be seamless for the end user (i.e. the user shouldn't even realize that anything has happened). If that is not possible, the scaling up/down should be implemented in a non-disruptive way such that the end user would be notified and would have the time to save their current work and move to a new node for the scaling up/down to be completed.
- [x] Enable the updating of Vaadin apps with (a) zero downtime, and (b) without disrupting the workflow of users currently connected to the app. This practically means notifying the end user to save their work before moving to the updated version of the app. 
- [x] Provide Infrastructure-as-Code templates to help teams deploy Vaadin apps to Azure Cloud

## General criteria

- [x] APIs reviewed 

- [x] Design 

- [x] Performance 

- [x] Documentation: https://vaadin.com/docs/latest/tools/azure-cloud

**Comment by mrts** [comment]
>  Enable Vaadin apps to scale up and down in a non-disruptive manner. The scaling up/down events should preferably be seamless for the end user (i.e. the user shouldn't even realize that anything has happened). If that is not possible, the scaling up/down should be implemented in a non-disruptive way such that the end user would be notified and would have the time to save their current work and move to a new node for the scaling up/down to be completed.

How is session data replicated between the instances when the application is scaled up?

**Comment by tarekoraby** [comment]
Session data is to be replicated using some caching technology like Hazelcast or Redis.

**Comment by mrts** [comment]
> Session data is to be replicated using some caching technology like Hazelcast or Redis.

Excellent! Vaadin previously recommended sticky sessions, but replicated sessions can prevent data loss when one of the cluster nodes fails. Seems you leaning towards replicated sessions then?

**Comment by tarekoraby** [comment]
To clarify, the Kit that is currently under development will likely be using a combination of sticky sessions and session replication. Under normal circumstances, sticky sessions will be used to always route the same user to the same node/pod. Each node/pod will keep the user session in memory, and it will also asynchronously replicate the session to the cached store (say, hazelcast). Under normal circumstances, thus, the user experience shouldn't be affected as the session is retrieved from the internal memory of each node/pod.

However, when there is a scaling down event, or if there is an unexpected node/pod/network failure in the server the user is currently being connected to, then the user will be connected to a new healthy node/pod that will retrieve the session from the common cache. So for the end user, the experience will be seamless (they will not notice that anything has happened, except perhaps for a very slight delay when scaling down or a node failure event occurs).

**Comment by tarekoraby** [comment]
Delivered with Vaadin 23.3.0.
