### ISSUE TITLE
Unreachable URLs in cookbooks main navigation items

### ISSUE THREAD

**Issue by maxrasche** [vaadin/platform#3368]
### Describe the bug

When visiting the Vaadin cookbook you can't navigate to Vaadin Start or the "Contact Us"-Button target, the constructed URLs are not reachable.

### Reproduction

Visit [https://cookbook.vaadin.com/?](https://cookbook.vaadin.com/?) and navigate to Vaadin Start via the main navigation `Developers > Vaadin Start`. The target url [https://vaadin.comhttps://start.vaadin.com/](https://vaadin.comhttps://start.vaadin.com/) can not be resolved.

The same issue applies to the "Contact Us" button (href attribute is set to [https://vaadin.comhttps://pages.vaadin.com/contact](https://vaadin.comhttps://pages.vaadin.com/contact) when clicking it from [https://cookbook.vaadin.com/?](https://cookbook.vaadin.com/?).

### System Info

Browser: chrome 106.0.5249.119

**Comment by ZheSun88** [comment]
Thanks for reporting this issue. Our website team will handle it and hope we can fix it as soon as possible.

**Comment by maxrasche** [comment]
Thanks for the fix!
