### ISSUE TITLE
DatePicker 2-digit year parsing based on customizable reference date

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3483]
## Description
Make DatePicker's parsing of 2-digit years behave consistently and predictably, regardless of the formatting configuration.

(See https://github.com/vaadin/flow-components/issues/1107)

## Acceptance criteria
- [x] Change (non-Flow) `vaadin-date-picker` default parsing to select past/future based on reference date† instead of hardcoded 1950.
- [x] Change Flow `DatePicker` default parsing to select past/future based on reference date†.
- [x] Change Flow `DatePicker` custom date format based parsing to select past/future based on reference date†.
- [x] `vaadin-date-picker` and Flow `DatePicker`: if a 4 digit presentation format is used, pad years 0–999 with leading zeros, so that e.g. actual year 42 is displayed as `0042`, and actual year 765 is displayed as `0765`
- [x] *Reference date defaults to current date.
- [x] Add API to `DatePickerI18n` for setting & getting the reference date, e.g. `DatePickerI18n.setReferenceDate(LocalDate)` so that the reference date can be to something other than the current date if needed.

† 2-digit years are interpreted as being within a 100-year range whose midpoint is called the _reference date_. As an example, a reference date of 2000-01-01 means that the date entered is interpreted as being within the range 1950-01-01 – 2049-12-31, so the year ‘50’ is parsed to 1950 while ‘39’ is parsed to 2049.

**Breaking change:** The default parsing behavior of 2-digit year formats, and the 4-digit-year display of years<1000 is different compared to previous versions. The old parsing behavior can be reverted to by overriding the default reference date.

## General criteria
- [x] APIs reviewed 
- [ ] UX/DX tests in Alpha 
- [x] Documentation: https://vaadin.com/docs/latest/components/date-picker/#two-digit-year-formats
- [x] Limitations: 2-digit-year display format combined with 4-digit-year parsing format can still cause weirndess and should be avoided (this will be mentioned in docs)

**Comment by web-padawan** [comment]
Vaadin 23.3.0 is out, closing this issue as delivered.
