### ISSUE TITLE
Unresolved @vaadin imports in production and dev modes (24.0.0.alpha5)

### ISSUE THREAD

**Issue by kripsadin** [vaadin/platform#3537]
### Describe the bug

I am trying to run samples from start.vaadin.com, these samples work fine at Vaadin 23.2, but after upgrade to 24.0.0.alpha5, standart vaadin components are missing:
[24.log](https://github.com/vaadin/platform/files/10120127/24.log)

Could you provide some fix or instructions, how to add @vaadin resources manually?

### Expected-behavior

Application should start in dev mode and production modes

### Reproduction

Download and compile sample app with helloworld2, masterdetail2, for 24 vaadin version.

### System Info

Windows 10, jdk-17.0.3, Maven 3.8.1, Spring Boot 3.0, Vaadin 24.0.0.alpha5

**Comment by Artur-** [comment]
Are you starting from a 23.2 project and upgrading it to 24.0.0.alpha5? There are some breaking changes between 23 and 24 that you need to take into account. In this case it seems that the project is still using old style `@vaadin/vaadin-button` imports when it should be using `@vaadin/button` without the extra `vaadin-` in between

**Comment by kripsadin** [comment]
Thank you very much, Artur!
I have solved the issue. The problem was just in two views: hello-world2-view.ts and master-detail2-view.ts.
I have created 24 version samples from new browser session, but sources for these two files were for the 23 vaadin version.
