### ISSUE TITLE
AC: Vaadin “Express Build” mode

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#3554]
## Description

A new development mode enabling Vaadin Flow projects to start more quickly without installing Node.js and npm dependencies.

## Use cases
As a *user role (e.g. developer)*
I want to *do action (e.g. be notified about closing browser)*  
So that I can *expected results (e.g. free resources immediately)*  

As a developer
I want to evaluate Flow and start my Flow application quickly on my local without installing frontend build tools, like [Node.js](https://nodejs.org/en/), and a lot of npm packages and files (e.g., package.json) in my Flow app directory.

So that I got the up and running application faster and I don't need to think about why I need these frontend tools and frontend-related configuration files in my project, given that I aim to develop web apps 100% in Java, and my initial experience left me wondering if developing in Flow is going to be slow and cumbersome.

## Acceptance criteria
- [x] Vaadin Flow should have a mode called "Express Build mode", which doesn't require the following actions to happen:
   - Node.js installation
   - Installation of the npm modules defined in package.json
   - Start Vite, process the files in frontend directory and use files from `node_modules` into a suitable format so the browser can load them.
- [x] Express Build mode is turned ON with a feature flag.
- [x] Express Build mode should load frontend files from the pre-compiled frontend bundle:
   - A "default app bundle" which contains all Vaadin components. It is produced as part of the Vaadin platform build for each version and the JavaScript/resources are included in a jar. The default app bundle should be a part of the platform as a separate module and can added into a Flow application as a maven/jar dependency - then the resources from the bundle should be loaded and used from this jar (from classpath). A Flow application without frontend customisations, templates or add-ons (which do frontend customisations) can use this bundle directly for all development and never need any tooling for the frontend when developing.
    - A bundle that is maintained as part of the project and has a customisations.
- [x] The choose between what to use - the default app bundle or customised bundle, should be made based on:
    - extra dependencies or newer dependency versions added to the project,
    - extra frontend files contributed from add-ons or the frontend folder.
    If nothing extra - use the default bundle.
- [x] If the project includes an extra frontend files or dependency changes, Flow should check if there is already a pre-compiled bundle in the project.
- [x] Flow should provide a versioning mechanism for bundles, i.e. it should be possible to know if the bundle has been compiled with the same frontend files and dependencies that are currently in use.
- [x] Once the Flow detects the modifications and the bundle is not in sync with the frontend versions in the project, Flow should automatically remove the bundle, install frontend tooling (Node.js), re-compile/re-build a bundle and place it into a dedicated directory in the project, then use the new bundle in the application.
    Express build mode should automatically rebuild the bundle if:
    - An add-on dependency that includes JS is added
    - A JS file is directly added to the project, or if that file is edited afterwards
    - A theme targeting component's shadow DOM is added/edited. Theming in the light DOM (targeting views, or targeting components using the `::part` selector) should work without the need to rebuild the bundle.
- [x] The Flow's custom theme is currently processed as part of the frontend bundle. Custom theme should be processed separately from the bundle and modified/loaded without a frontend build, so no bundle re-compilation is needed: instead of injecting the CSS as JS into component's shadow DOM, we can handle CSS as static resources separately from bundle.
- [x] Packaged as a `JAR` custom theme should be also processed separately from the bundle and should trigger a new bundle generation only if it defines the assets to be added to the project (fonts, images, CSS).
- [x] Express build mode should be compatible both with a project downloaded from Vaadin Start ~and one downloaded from [start.spring.io](http://start.spring.io/)~, i.e. **Express build mode should be enabled by default in Flow applications**, so the first evaluation would have a better DX.

## Fallback to the default approach with the dev server
In case of a lots of frontend coding is needed, the Express Build mode is changed to the existing development mode using the dev server (Vite). However, having a JS/TS add-on dependency or some JS/TS sources in the project doesn't always mean that the Express Build mode can't be used. It means that the Flow should automatically detect this and rebuild the bundle to make the app work.

## General criteria

- [ ] Design 
   - https://docs.google.com/document/d/1bo4ejGFSckqVPXJgJzVui7ZEp01qSRnERxLzmqTqdnc/edit?usp=sharing
   - https://github.com/vaadin/flow/issues/14555

- [ ] Performance 

- [ ] UX/DX tests in Alpha 
https://docs.google.com/document/d/1TEYBtWKSazSYA-B7IFgQjIZrVWFLWHjRBsQgjTbrfVQ/edit?usp=sharing

- [ ] Documentation: 
https://github.com/vaadin/docs/pull/2018 (draft)

- [ ] How to test? 

- [ ] Limitations: 

## Security
- [ ] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by knoobie** [comment]
I like this feature a lot, but the name feels kinda misleading and I was first wondering if you guys wanna implement support for "Express(.js)" in Vaadin Flow.

**Comment by web-padawan** [comment]
How about "Vaadin Turbo dev mode"? Inspired by good old Opera 10 (it used to be quite fast back then) 🙂

**Comment by guttormvik2** [comment]
Just wanted to add two 👍 👍 for this.

For years with old vaadin I have checked in our generated widgetset so that developers could ignore it 99% of the time.
I have been annoyed and surprised by the need to download 27K files to node_modules in new java.

Just a couple of comments:

This is still very hidden. I discovered it due to the "express mode" checkbox in the vaadin starter, and found this issue when googling it. Since you have exposed it, I assume you want more people to try it out? If so, you should announce it someplace people will see it.

Downloading the starter and running it worked like a charm. Very nice.
Then I changed from alpha6 to alpha7 and built again. This downloaded node_modules, which was a bit surprising, but I see there are "acceptance criteria" that are still not ticked, so I guess that's to be expected. It updated dev-bundle, and ran fine. Then I deleted node_modules and it still ran fine, without re-downloading node_modules. Nice.

I do get a runtime error/warning though. I did not get this with the unmodified alpha6 starter:

`java.lang.IllegalStateException: Asset '/themes/myapp/line-awesome/dist/line-awesome/css/line-awesome.min.css' is not found neither in frontend/themes/theme-name/ nor in dev-bundle/assets/. Verify that either the asset is available in frontend/themes/theme-name/ folder or it is added in the 'assets' block in 'theme.json'.`

**Comment by Artur-** [comment]
After https://github.com/vaadin/flow/pull/15566 is merged and we make a new V24 alpha release, it should be ready for a bit wider testing

**Comment by knoobie** [comment]
Yes/No - See this AC. If you only use the build in stuff and no custom styling, yes - otherwise no, it's needed at some point.

**Comment by jouni** [comment]
> and no custom styling

That’s only partially true. You can still style your application with global CSS (Light DOM only). Only Shadow DOM injected styles are not supported if you use the pre-built frontend bundle.
