### ISSUE TITLE
APIs for applying CSS classnames to overlays

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3593]
## Description
Dedicated APIs for adding CSS class names to overlays in components (e.g. Combo Box dropdown)

## Use cases
As a developer
I want to apply a CSS classname to the overlay of a particular component instance
So that I can style it separately from other overlays

## Background
Components like Combo Box, Date Picker and Menu Bar do not propagate their CSS classnames to their overlays. The current way to apply identifiers to overlays is the `theme`/`themeName` API. This approach is problematic because it introduces a potentially confusing, Vaadin-specific concept, that is almost but not quite the same as CSS classes, with significantly less convenient CSS selectors (`[theme~="foo"]` instead of `.foo`). While this could be solved simply propagating all CSS classnames to overlays, it would also make it easy to inadvertently target overlays with CSS intended for the main component.

## Acceptance criteria
- [ ] API in Flow components with overlays* for adding CSS classnames to the component's overlay (proposal: `addOverlayClassNames(String...)`
- [ ] API in Web Components components* with overlays for adding CSS classnames to the component's overlay (proposal: `overlayClass` String property)
- [ ] Corresponding APIs for getting and removing overlay classnames.

### Components to which this API should be added
- [ ] ComboBox
- [ ] DatePicker
- [ ] TimePicker
- [ ] Select
- [ ] MenuBar
- [ ] AvatarGroup
- [ ] Tooltip

(Overlay-only Flow components Dialog, Confirm Dialog, ContextMenu and Notification do not need this as their CSS classnames are applied to the overlay.)

## General criteria
- [ ] APIs reviewed 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: will be added to the V24 theming documentation
- [ ] How to test? 
- [ ] Limitations: 

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by jouni** [comment]
For the web component, perhaps we could expose the overlay element directly on the host, e.g. `host.overlay` would return the HTML element. Now you can access it with `host.$.overlay`, which looks ugly and not really something one would rely on. 

Having an additional string property `host.overlayClass` seems fine at first glance, but I would assume most front-end devs are accustomed to the `classList` API, and all the convenience methods it has, like `add()`, `remove()`, and `toggle()`. If we expose the overlay element on the host, then it’s easy to access those APIs, e.g. `host.overlay.classList.add(...)`.

**Comment by web-padawan** [comment]
> I would assume most front-end devs are accustomed to the classList API

While this API would allow us to not add any dedicated property, it would also mean not being able to assign classes declaratively in HTML. And I'd say nowadays most front-end devs are actually accustomed to the Tailwind API 😕 

This would be especially problematic in case of `vaadin-context-menu-overlay` where we have nested sub-menus.

**Comment by jouni** [comment]
Can we proxy the overlay classList property to a property on the host?

**Comment by web-padawan** [comment]
IMO we should add `Tooltip` to the list and also add `overlayClass` there since it doesn't propagate class names in Flow.

**Comment by web-padawan** [comment]
Note: based on the internal discussions, we also implemented `overlayClass` API in overlay-only web components where we added support `HasStyle` in Vaadin 23, and updated Flow components. See https://github.com/vaadin/web-components/issues/5121#issuecomment-1400783875
