### ISSUE TITLE
Item-classname API for messages and menu items

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3594]
## Description
API to apply CSS class names to individual items in MessageList, MenuBar and ContextMenu components.

## Use cases
As a developer
I want to apply CSS classnames to individual messages or menu items
So that I can style them easily

## Background
These components currently have APIs for applying _theme names_ to items, but regular CSS classnames would be a more obvious and industry-standard way to target elements, and they have simpler selectors than theme attributes.

## Acceptance criteria
- [ ] API in MessageListItem for adding classnames (Flow: `MessageListItem::addClassNames(String...)`, WC: `class` property in `.items` json)
- [ ] API in MenuItem for adding classnames (Flow: MenuItem::addClassNames(String...), WC: `class` property in `.items` json)
- [ ] Corresponding methods for getting and removing classnames.

## General criteria
- [x] APIs reviewed 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: 
- [ ] How to test? 
- [ ] Limitations: 

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by vursen** [comment]
We've decided internally to prefer `className` to `class` as a property name because:

- It is aligned with React (we have Vaadin React components now).
- It simplifies destructuring (note, `class` is a reserved keyword in JavaScript, so the property cannot be destructured directly to a `class` variable.).

**Comment by rolfsmeds** [comment]
Closed by https://github.com/vaadin/platform/issues/4748
