### ISSUE TITLE
DataProvider API for refreshing items without clearing selection/value

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3640]
## Description
New API in `DataProvider` for refrehsing the items of a selection component (e.g. `Select` or `Checkbox Group`) without clearing the current selection (as opposed to the existing `DataProvider::refreshAll` which also clears the selection.

## Use cases
As a java developer
I want to refresh the items shown in a selection component (e.g. Checkbox Group) without clearing the selection
So that I can update the list without having to manually re-apply the selection afterwards

## Acceptance criteria
- [ ] `DataProvider` method for refreshing the set of items, without clearing selection (e.g. `refreshItems()`)
- [ ] The new method should _not_ fire a `ValueChangeEvent`, since the selection (i.e. value) is unaffected
- [ ] `DataProvider::refreshAll` API left unchanged to avoid breaking changes
- [ ] `DataProvider::refreshAll` should be deprecated with a recommendation to replace usages with the new API, possibly followed by HasValue::clear() if clearing the value is actually desired
- [ ] The new method should fire an event that is somehow distinguishable from a `refreshAll` to the components that consume it, so that they can update themselves accordingly (e.g. flag in existing event or new event type)

## Possible bonus features

- Parameter for also clearing the current selection/value (for convenience use when `refreshAll` is removed)
- Parameter for "pruning" the selection of items that are no longer in the list (not possible to reliably implement for lazy loading components like Combo Box)

## General criteria

- [ ] APIs reviewed 

- [ ] Design 

- [ ] Performance 

- [ ] UX/DX tests in Alpha 

- [ ] Documentation: 

- [ ] How to test? 

- [ ] Limitations: 

## Security
- [ ] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/platform/issues/4486
