### ISSUE TITLE
Documentation for License Checker is incorrect for Vaadin 14.9 

### ISSUE THREAD

**Issue by RhonanMS** [vaadin/platform#3717]
### Describe the bug

The [current Licensing FAQ](https://vaadin.com/licensing-faq-and-troubleshooting) is very confusing if building Vaadin applications in an offline CI/CD environment.
The FAQ states the following:
> Since Vaadin 23.2 server license keys can be used online and offline. Please follow the installation instructions in our official documentation.
> For Vaadin versions older than 23.2 server license keys can only be used online. 

This does not match with our experiences with a Vaadin 14.9.4 build on our (offline!) CI/CD servers  - here, the offlineKey generated for 23.2+ could be used in Vaadin 14.9, even though it is stated otherwise.
It seems that - e.g. according to GitHub issue https://github.com/vaadin/platform/issues/3322 - the License Checker was backported from 23.2 to 14.9. 
Because of this, it would be helpful to update to the documentation to reflect which Vaadin version supports which License Checker algorithm

### Expected-behavior

The Licensing FAQ and License Generator Page should be updated to reflect License Checker changes backported to Vaadin 14 LTS.

### Reproduction

-

### System Info

Windows 10
Vaadin 14.9.4 LTS
Firefox, Chrome, Edge (current versions)

**Comment by Artur-** [comment]
Thanks, this was indeed overlooked when releasing 14.9. The Licensing FAQ has been updated

**Comment by RhonanMS** [comment]
Thank you for the fast update - it definitely clarifies things!
