### ISSUE TITLE
Supported technologies for Vaadin 24

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#3720]
**Summary of changes since Vaadin 23**
- Java 17 or newer is required instead of 11
- Safari 14 support is dropped. All iOS devices can be upgraded from Safari 14 to 15
- Weblogic + TomEE is not supported or tested as there is no version available for Jakarta EE 10
- Karaf or OSGI is not supported as OSGi standards are still lacking servlet 6 support
- Portlets are not supported as portlet standards are still lacking servlet 6 support
- Some servers are still in beta with their Jakarta EE 10 support but are still tested
- Node.js support is raised to the current LTS (Node 18) to avoid future problems
- Gradle support is raised to the version (Gradle 7.5) required by [Spring Boot](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle)
- Spring Boot 2 is not supported

**Desktop browser**
Chrome (evergreen)
Firefox (evergreen)
Firefox Extended Support Release (ESR)
Safari 15 or later
Edge (Chromium, evergreen)

**Mobile browser**
Chrome (evergreen) for Android
Safari for iOS (15 or later)

**Java**
Version 17 or later of any JDK or JRE

**Maven**
Version 3.5 or later, though don't use [broken](https://maven.apache.org/docs/3.8.4/release-notes.html) 3.8.2 and 3.8.3

**Gradle**
Version 7.5 or later

**Application server**
Vaadin Flow requires Java Servlet API 6 and Java 17 or later. It is tested on:
- Apache Tomcat 10.1
- Open Liberty 23.0.0.1-beta
- RedHat JBoss EAP 8.0 beta
- WildFly 27
- Jetty 12 beta
- Payara Server 6
- Payara Micro 6

**Node.js**
Version 18 or later

**Spring Boot**
Version 3.0 or later

**Comment by knoobie** [comment]
> Java
> Version 17 of any JDK or JRE

Does that mean 18-xx are not official supported? For node.js or spring boot "or newer" is explicitly listed

**Comment by ZheSun88** [comment]
oh, no.. it should be supported as well.

**Comment by manolo** [comment]
Modified the comment to say 17 or newer

**Comment by knoobie** [comment]
Thanks for the clarification! 🙇‍♂️
