### ISSUE TITLE
com.vaadin.devbundle.BundleComponents must not be included

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#3763]
### Describe the bug

Because com.vaadin.devbundle.BundleComponents with its `@NpmPackage` annotations is included in all Vaadin 24 beta1 projects, `"@vaadin-component-factory/vcf-nav"` and `"line-awesome"` are currently Vaadin managed dependencies. They should not be.

This affects the starters and if you create a Hilla project, the mentioned dependencies are removed from the project and the Hilla project does not start

### Expected-behavior

The file is used for building the bundle but not included in the jar

### Reproduction

.

### System Info

Vaadin 24 beta 1

**Comment by web-padawan** [comment]
Could we consider getting rid of `line-awesome` altogether in the future? We have `@vaadin/icons` - let's use that.

**Comment by mshabarov** [comment]
Fixed by https://github.com/vaadin/platform/pull/3764 and https://github.com/vaadin/skeleton-starter-flow-spring/pull/937
