### ISSUE TITLE
APIs for setting aria-label and aria-labelledby

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3803]
## Description
APIs in Flow components for applying `aria-label` and `aria-labelledby` attributes to the correct elements in the components.

## Background
The WAI-ARIA attributes [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) and [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) are used to provide non-visual labels to components in order to make them identifiable for users of assistive technologies like screen readers, in cases where the components do not have corresponding visible labels.

Use cases include icon-only buttons, whose purpose sighted users can identify based on the icon, and input fields that are visually labelled by an element other than the component's built-in label (e.g. for layout purposes).

Although the Flow Element API makes it possible to set these attributes on components' root elements already today, many components – especially input fields – need to have the attribute set on the native input element rather than the component's root element in order to work correctly, and the components for which the root element is appropriate (like Button) would also benefit from a dedicated API.

## Components
- All input fields components
- Button
- Tab
- Menu Bar buttons (top-level items)

## Acceptance criteria
- [x] Setter & getter for `aria-label` to the components listed above via the existing `HasAriaLabel` interface, that applies the attribute to the correct element in the component (details in https://github.com/vaadin/flow-components/issues/2946)
- [x] Addition of an `aria-labelledby` get/set API to `HasAriaLabel` (e.g. `setAriaLabel(HasElement)` or `setAriaLabelledBy(HasElement)` that takes an element whose `id` is used as the attribute value)**
- [x] #3833
- [x] Setting a custom `aria-labelledby` through this API should probably remove the default `aria-labelledby`, if any, rather than append to it, in order to avoid unncessary duplicate announcements.

** The `setAriaLabel(HasElement)` option would have the benefit of making it obvious that both cannot be used simultaneously, as `aria-labelledby` as precedence over `aria-label` (which is effectively ignored if the former is set).

## General criteria
- [x] APIs reviewed 
- [x] UX/DX tests in Alpha 
- [x] Documentation: See _Basic Features_ > _External and Invisible Labels (ARIA)_ in input field component pages.
- [x] How to test? 
- [x] Limitations: For technical reasons, `CustomField` is excluded from these APIs and `DateTimePicker` only as `aria-label` API, not `aria-labelledby`.

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by vursen** [comment]
Blocker: https://github.com/vaadin/web-components/issues/5580

**Comment by yuriy-fix** [comment]
Let's further split the ticket to cover following components:
- Text-field + 6 field-based components
- Date Picker
- Time Picker
- Date Time Picker (two labels: for date and time separately)
- Combo Box + Multiselect Combo Box (single ticket for both)
- Select
- Button
- Tab
- Menu Bar buttons (top-level items)
- List Box + MultiSelect List Box (need to be confirmed)

Each point will take approximately 0.5 dev days, so in total 5 days + 1 day buffer = 6 days.

**Comment by web-padawan** [comment]
Related to #3814

**Comment by DiegoCardoso** [comment]
> The `setAriaLabel(HasElement)` option would have the benefit of making it obvious that both cannot be used simultaneously, as `aria-labelledby` as precedence over` aria-label` (which is effectively ignored if the former is set).

In that case, if someone uses `component.setAriaLabel(anotherComponent)`, what would be the value returned by `component.getAriaLabel()`? 🤔

**Comment by knoobie** [comment]
Looks like `RouterLink`is missing the `HasAriaLabel` interface

**Comment by rolfsmeds** [comment]
Indeed, this API has not been added to HTML element classes, as there is not much value in adding that as you can just `getElement.setAttribute("aria-label")` on them without caveats like getting it applied to a particular element and overriding default label-associations.

I suppose we could consider adding it if there's significant demand.
