### ISSUE TITLE
Webpack build failing due to updated @types/node dependency

### ISSUE THREAD

**Issue by reodt** [vaadin/platform#3849]
### Describe the bug

After `@types/nodes` version `18.14.1` (https://www.npmjs.com/package/@types/node/v/18.14.1) had been published on 2023-02-23, our Vaadin webpack build has been failing with:

```
Webpack build failed with errors:
ERROR in .../skeleton-starter-flow-spring-14/node_modules/@types/node/ts4.8/test.d.ts
[tsl] ERROR in .../skeleton-starter-flow-spring-14/node_modules/@types/node/ts4.8/test.d.ts(612,34)
      TS1005: '?' expected.
```
A similar problem has been reported here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/64472 (unrelated to Vaadin)

From what I understand, the updated type definitions are no longer compatible with the default typescript version Vaadin uses.

As a temporary work-around, we pinned `@types/node` to `18.14.0` (`npm install --save-dev @types/node@18.14.0`) and added `package.json` and `package-lock.json` to source control.

### Expected-behavior

The webpack build should not fail when using the `package.json`/`package-lock.json` generated by the `vaadin:prepare-frontend`task.

### Reproduction

Using the Vaadin 14 Spring Boot starter (https://vaadin.com/hello-world-starters):
- Import project
- Remove `package.json`, `package-lock.json`
- Regenerate `package.json`, `package-lock.json` (`vaadin:prepare-frontend` task)
- Run the app (`spring-boot:run`)
- Error is reported in console/browser

### System Info

Vaadin 14.x
Spring Boot

**Comment by Artur-** [comment]
This is fixed in https://github.com/vaadin/flow/pull/16052 but not yet released
