### ISSUE TITLE
vaadin-spring-boot-starter contains jakarta.websocket package twice

### ISSUE THREAD

**Issue by Frettman** [vaadin/platform#3898]
### Describe the bug

The `vaadin-spring-boot-starter` contains the `jakarta.websocket` Java package twice. This - so far - isn't a problem during compilation or execution, but Javadoc complains about it and it might be a problem later, if the versions of these packages ever diverge from each other.
`jakarta.websocket-api` and `jakarta.websocket-client-api` are included via `vaadin-core` -> `vaadin-dev` -> `vaadin-dev-server`.
`tomcat-embed-websocket` is included via `spring-boot-starter-web` -> `spring-boot-starter-tomcat`.

My first guess would be that `vaadin-spring-boot-starter` should exclude `jakarta.websocket-api` and `jakarta.websocket-client-api` from its `vaadin-core` dependency. `vaadin-core` is Spring-independent, so it would make sense that `vaadin-spring-boot-starter` would override these dependencies with its own versions. But maybe there a better way. (Like asking

Please note, that apps generated via https://start.vaadin.com/ also include `com.vaadin:vaadin`, which in turn would bring back `jakarta.websocket-api` and `jakarta.websocket-client-api` again. Since there's usually no Javadoc artifact for applications, there wouldn't be any build error, but having the same package twice on the classpath could still cause problems later.

### Expected-behavior

It would be nice if Vaadin add-ons using `vaadin-spring-boot-starter` could just have their Javadoc artifact built without having to tweak the dependencies.

### Reproduction

Opening any project created via https://start.vaadin.com/ should show the affected dependency tree.

### System Info

Vaadin 24
Java 17
Maven 3.8.7 (maven-javadoc-plugin:3.4.1)

**Comment by knoobie** [comment]
I would recommend to exclude vaadin-dev-* from your production build and artefacts nevertheless

**Comment by Frettman** [comment]
> I would recommend to exclude vaadin-dev-* from your production build and artefacts nevertheless

After having checked my projects, that exclusion is already part of the production profile :) Good advice nonetheless. Especially since the https://start.vaadin.com/ projects don't do that yet (hint hint).

**Comment by knoobie** [comment]
The ticket for the exclusion is here https://github.com/vaadin/flow/issues/15749

**Comment by mstahv** [comment]
Plain servlet starters seem to have some issues as well. Pretty much all jakarta namespaced stuff should only be in provides scope in vaadin dependencies:

<img width="1073" alt="Screenshot 2023-03-10 at 10 59 43" src="https://user-images.githubusercontent.com/1478052/224272143-ea0b2599-7d87-41ef-8d40-0abd1f2ae44c.png">

**Comment by Artur-** [comment]
> Especially since the https://start.vaadin.com/ projects don't do that yet (hint hint).

Doesn't this do it?
```
        <profile>
            <!-- Production mode is activated using -Pproduction -->
            <id>production</id>
            <dependencies>
                <!-- Exclude development dependencies from production -->
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core</artifactId>
                    <exclusions>
                        <exclusion>
                            <groupId>com.vaadin</groupId>
                            <artifactId>vaadin-dev</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
```

**Comment by Frettman** [comment]
> Doesn't this do it?

Ah, yes, this will do it of course. I had some fairly recent projects from shortly before the Vaadin 24 release (Vaadin 24 beta2) that didn't include this yet. So you were a bit faster than me :)

**Comment by Frettman** [comment]
> I only see the websocket api included once (it should be included 0 times) but not twice:

The Websocket API is also contained in `tomcat-embed-websocket`. Two different artifacts containing the same packages. That's always bound to get messy. But it makes me wonder, why `tomcat-embed-websocket` doesn't depend on `jakarta.websocket:jakarta.websocket-api` instead of including the same classes...

**Comment by Frettman** [comment]
The `provided` scope does not seem to make a difference for Javadoc (which made me aware of this in the first place). But I'll just exclude `vaadin-dev` in all Vaadin add-ons that are also Spring Boot add-ons.

**Comment by mstahv** [comment]
The PR by @Artur- only tackles to websocket APIs coming from dev server. Changed to scope of validation and annotation api's in #16223

Didn't build it locally, let's see what the tests say about that...

**Comment by mstahv** [comment]
And then there is still inject API left:
```
[INFO] |  |  |  +- com.vaadin:flow-push:jar:24.0.0:compile
[INFO] |  |  |  |  \- com.vaadin.external.atmosphere:atmosphere-runtime:jar:3.0.0.slf4jvaadin2:compile
[INFO] |  |  |  |     \- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
```

**Comment by mstahv** [comment]
@Frettman Good point about the add-ons. Probably all add-ons should now have the vaadin-dev excluded, not nice :-(

**Comment by mstahv** [comment]
Or have vaadin/vaadin-core in provided scope 🤷‍♂️

**Comment by Artur-** [comment]
If you do not set the vaadin or vaadin-core dependency to provided in an addon, you might cause version conflict problems for the users at some point

**Comment by mstahv** [comment]
If one only depends on an add-on there shouldn't be conflicts.

**Comment by mstahv** [comment]
atmosphere fix in https://github.com/Atmosphere/atmosphere/pull/2489 (coming in via vaadin-push, which includes a special build of atmostphere).
