### ISSUE TITLE
Vaadin 14.9.7 - Slow Compile for Production

### ISSUE THREAD

**Issue by giusdiluca** [vaadin/platform#3983]
### Describe the bug

I'm currently using Vaadin with Spring Boot and I've recently upgraded platform version from 14.8.18 to 14.9.7. Before the upgrade my artifact for production was built in approximately 90 seconds, while after the upgrade the same package is produced in 480 - 540 seconds. I've noticed that there is a repeatedly check for the pro license of all the pro components during the build, even if I have the license installed on my development workstation and really I don't use many of them in my source code. Anyway by checking the logs, it seems the build is stuck for many seconds in doing "Reading file /sys/devices/virtual/dmi/id/product_uuid" as per the log attached.

Is there a way to speed up the process? Why the build process slowed down by mean of the platform upgrade?

Many thanks, Giuseppe.

[build.log](https://github.com/vaadin/platform/files/11064224/build.log)

### Expected-behavior

compilation time as per the previous version of the framework (e.g. 90s)

### Reproduction

The issue is reproducible by performing a compilation with production option:

mvn -X clean package -DskipTests -Pproduction

### System Info

Red Hat EL 7.7

**Comment by Artur-** [comment]
Can you try license checker 1.12.3 and provide the same log?
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>license-checker</artifactId>
      <version>1.12.3</version>
    </dependency>
  </dependencies>
<dependencyManagement>
```

**Comment by manolo** [comment]
timestamps in logs would help, as well as if you can compile your project in different system (windows or mac) with the same network conditions

**Comment by giusdiluca** [comment]
[build_v1.12.3.log](https://github.com/vaadin/platform/files/11075622/build_v1.12.3.log)
Here attached is the log with license checker v 1.12.3 and the timestamps for the maven compilation. Unfortunately I've only this workstation and cannot compile on a different Operating System

**Comment by Artur-** [comment]
we are using the oshi project to get some system information and this is what an oshi maintainer suggested:

As a debugging step, you might try each of those sub-queries to inspect its results and see what's taking the time. The Java code calls and parses command line input so you could see which call here is slow:

dmidecode -t system
lshal
lshw -C system

**Comment by giusdiluca** [comment]
If I understood correctly the license checker, using the oshi library, is now performing for each license check a call (among the other tasks) to the underlying OS commands listed in your previous answer. It seems that the lshw call is very slow (about 15s as per the time the command in the previous logs seems to be stuck).

Is there a way to speed up this process?

time lshw -C system
WARNING: you should run this program as super-user.
polaris                     
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-pnp00:00
       product: PnP device PNP0b00
       physical id: 18e
       capabilities: pnp
       configuration: driver=rtc_cmos
  *-pnp00:01
       product: PnP device PNP0c02
       physical id: 18f
       capabilities: pnp
       configuration: driver=system
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

real	0m15.328s
user	0m14.700s
sys	0m0.620s

**Comment by Artur-** [comment]
I created an oshi issue here to see if the 15s can be reduced to something smaller: https://github.com/oshi/oshi/issues/2342

Then we need to see why the checker is invoking this multiple times. It is supposed to invoke it once, which means that it would take 15s and not 500s

**Comment by mcollovati** [comment]
Looking at the attached logs it seems that the old license checker version is still used
```
08:54:31 [INFO] --- vaadin-maven-plugin:14.9.7:prepare-frontend (default) @ CogecoUI ---
08:54:31 [DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=80436, ConflictMarker.markTime=73023, ConflictMarker.nodeCount=61, ConflictIdSorter.graphTime=43484, ConflictIdSorter.topsortTime=36454, ConflictIdSorter.conflictIdCount=40, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=638935, ConflictResolver.conflictItemCount=59, DefaultDependencyCollector.collectTime=86278813, DefaultDependencyCollector.transformTime=934333}
08:54:31 [DEBUG] com.vaadin:vaadin-maven-plugin:jar:14.9.7
...
08:54:31 [DEBUG]    com.vaadin:flow-maven-plugin:jar:2.8.6:compile
...
08:54:31 [DEBUG]       com.vaadin:license-checker:jar:1.11.2:compile (version managed from default)
...
08:54:31 [DEBUG] Created new class realm plugin>com.vaadin:vaadin-maven-plugin:14.9.7
08:54:31 [DEBUG] Importing foreign packages into class realm plugin>com.vaadin:vaadin-maven-plugin:14.9.7
08:54:31 [DEBUG]   Imported:  < maven.api
08:54:31 [DEBUG] Populating class realm plugin>com.vaadin:vaadin-maven-plugin:14.9.7
...
08:54:31 [DEBUG]   Included: com.vaadin:license-checker:jar:1.11.2
...
```

**Comment by Artur-** [comment]
It should be possible to override the plugin dependency by adding the dependency inside the plugin definition
```
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.vaadin</groupId>
                        <artifactId>license-checker</artifactId>
                        <version>1.12.3</version>
                    </dependency>
                </dependencies>
```

**Comment by giusdiluca** [comment]
Just tried with the dependency added to the plugin, it worked!
Now the build time is approx. 105s (15s more than the previous build with 14.8.18 because of the 15s added for the license checker with oshi call). Now the license has been checked only once and then all the following checks have been skipped.
Would you probably include this version of the license checker in the next version of the vaadin-maven-plugin ? (maybe still on-time for the 14.10.0 )

Thanks a lot for your support.

Giuseppe.

**Comment by Artur-** [comment]
The license checker update is in #3984. In addition to this I don't think we can do much, except if there is an improvement in oshi, we can upgrade to a newer version once available.
