### ISSUE TITLE
Generate a script to create Maven boms and poms based on the metadata file

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#4]
For each section in the metadata file, generate a Maven bom

Using the metadata file created in #2, generate one `section-bom.pom` using the section as the artifact id and a `<dependencyManagement>` tag with version information for all sub artifacts which define a `javaVersion`. Dependencies which exist in the metadata file itself (e.g. `vaadin-core`) should be marked as `<type>import</type>`

In addition to the bom file, a `section.pom` should be generated for each section. This imports the corresponding bom file and defines a `<dependencies>` section with all dependencies included in the bom.

Finally the generated boms and poms are pushed to a Sonatype staging repository for testing and release

**Comment by ripla** [comment]
This is working already.
