### ISSUE TITLE
@vaadin/router version inconsistency

### ISSUE THREAD

**Issue by oflege** [vaadin/platform#4024]
### Describe the bug

flow-server:23.3.7 has this in com/vaadin/flow/server/frontend/dependencies/default/package.json
`"@vaadin/router": "1.7.4"`

whereas vaadin-core:23.3.11 has this in META-INF/vaadin-core-versions.json
`"vaadin-router": {
     "jsVersion": "1.7.5",
`

`gradle vaadinPrepareFrontend` uses the former and puts version "1.7.4" into our project's package.json whereas `gradle vaadinBuildFrontend` uses the latter and changes the version to "1.7.5"

### Expected-behavior

version of @vaadin/router is consistent

### Reproduction

see bug description

### System Info

vaadin platform release 23.3.11

**Comment by SonReimer** [comment]
This leads to newly written package.json and pnpm-lock.yaml whenever application is started in ide.

**Comment by SonReimer** [comment]
This is awesome.
I thought the files should only change once, when starting application after vaadin:prepare-frontend,
but not on repeated starts fo the application.
