### ISSUE TITLE
Add Hilla Gradle Plugin

### ISSUE THREAD

**Issue by platosha** [vaadin/platform#4050]
Currently Vaadin has plugins for Maven and Gradle, whereas for Hilla platform only the Maven plugin exists.

After we add Engine Gradle Plugin in Hilla (see vaadn/hilla#900), let's add Hilla Gradle Plugin, similar with how Hilla Maven Plugin is released.

**Comment by cromoteca** [comment]
Will be probably implemented by adding the necessary tasks to the Gradle plugin in the Hilla project
