### ISSUE TITLE
Bug on Vaadin documentation - No validation for comments

### ISSUE THREAD

**Issue by eno-lc** [vaadin/platform#4063]
### Describe the bug

There is no validation for comments, each click on the comment button creates a request without validating the comment text field so that results in a lot of requests made and lots of unnecessary comments.

### Expected-behavior

Validate the input in the comment text field and then submit the request to the backend.

### Reproduction

Please do check the video below for the reproduction steps, ps. excuse the sound in the video background :)
https://user-images.githubusercontent.com/93098680/233570713-7f1210e9-6c0b-41dd-b011-a0fa3d39b895.mp4

### System Info

It is a documentation issue so it is the same in any system, browser or device. :)

**Comment by jouni** [comment]
Thanks for reporting this issue! I transferred it to the team that is responsible for the discussions module on vaadin.com (it’s a service which is external to the docs repository).
