### ISSUE TITLE
Warning Notification theme variant

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#4073]
## Description
Lumo style variant for warning notifications (that is distinct from the error variant)

## Use cases
As a user
I want to be able to visually distinguish warning notifications from other notifications
So that I can take the appropriate action

![Image](https://user-images.githubusercontent.com/4611559/233988385-6c5fc19e-8175-4216-873d-eba1f2b66295.png)

## Acceptance criteria
- [x] Warning-colored variant for Notifications (see #4072)
- [x] Java API: `NotificationVariant.LUMO_WARNING`
- [x] WC API: `theme="warning"`
- [x] Conforms to WCAG 2.1 level AA contrast criteria

## General criteria

- [x] APIs reviewed 

- [x] Design (see attached image)

- [x] Documentation: https://vaadin.com/docs/latest/components/notification/#warning

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by jouni** [comment]
Do we really need the border? How would it look like without it?

**Comment by rolfsmeds** [comment]
Would look nicer without it, but then it fails WCAG 2.1 AA non-text contrast requirements, and although technically, like buttons, the notification card doesn't _have_ to pass contrast requirements as long as the content inside it does, I feel that it probably _should_, so that it stands out sufficiently against the background.

(The light gray default variant would need to be correspondingly adjusted)

**Comment by jouni** [comment]
To me, it seems like a similar thing as borders for text inputs and buttons, and could be opt-in if you really want to increase the contrast more, not necessarily the default.

**Comment by jouni** [comment]
Just comparing to the other colored variants, and keeping it aligned with them. The yellow is lighter, so yeah, perhaps it could have a light border. But the one in the OP is too stark IMO.

<img width="458" alt="Screenshot 2023-05-02 at 17 37 15" src="https://user-images.githubusercontent.com/66382/235699189-944648b4-4380-4235-85c9-38baac26d18d.png">
