### ISSUE TITLE
GridContextMenu does not work properly in a Dialog on Vaadin24 (Works on Vaadin23)

### ISSUE THREAD

**Issue by TFyre** [vaadin/platform#4116]
### Describe the bug

Grid Context Menu does not show when you have a grid inside a dialog and you right click with a mouse.

When using Web Developer Tools and looking at the network tab, the events are sent from the server to the browser, but immediately cancelled on the next request (thus not showing client side)

### Expected-behavior

Right click on Grid inside a Dialog should work correctly

### Reproduction

https://github.com/TFyre/playground-quarkus-vaadin

README.md contains details on how to test for vaadin 23 & 24

Its using Quarkus as the application container

### System Info

Windows 10
Vaadin23: Works
Vaadin24: Does not work
Browser: Firefox 112.0.2 / Chrome 112.0.xxx

**Comment by knoobie** [comment]
See https://github.com/vaadin/flow-components/issues/4896 for more information.

**Comment by TFyre** [comment]
Adding the GridContextMenu to the dialog itself allows the popup to display after multiple right clicks, but something is still disconnected/detached, since the click then doesnt open the nested dialog.

Doing [this ](https://github.com/vaadin/flow-components/issues/4896#issuecomment-1536253221 )works, but is it correct?

```java
    private class MyDialog extends Dialog {

        @Override
        public boolean isModal() {
            return false;
        }

        @Override
        public void setModal(final boolean modal) {
            getElement().setProperty("modeless", !modal);
        }

    }

```

**Comment by sissbruecker** [comment]
See https://github.com/vaadin/flow-components/issues/5063#issuecomment-1551367694
