### ISSUE TITLE
Prod bundles doesn't include all components 

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#4262]
### Describe the bug

Prod bundle doesn't contain the CheckBoxGroup. 

See https://github.com/vaadin/platform/blob/3d68b52fdfc1d2b918c96af1311c1276fc9b09f9/vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java#L10

Discord discussion: https://discord.com/channels/732335336448852018/1119262757750054923

### Expected-behavior

Prod bundle contains all components.

### Reproduction

Should be seen with any prod bundle 

### System Info

V24.1

**Comment by Artur-** [comment]
It actually contains it... but it is only loaded as part of Spreadsheet

**Comment by knoobie** [comment]
@Artur- looks like there was another report about Splitpanel - even tho a little bit weird since it's within the eager load file already. 

https://discord.com/channels/732335336448852018/1123698930031538206
