### ISSUE TITLE
SBOM: All artefacts share the same description (of the parent pom)

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#4383]
### Example:

```json

      "group": "com.vaadin",
      "name": "vaadin-avatar-flow",
      "version": "24.2.0.alpha6",
      "description": "A parent POM for all artifacts by Vaadin Ltd.",
      "scope": "required"

```

### Expected-behavior

All artefacts have proper description so that an auditor can understand what those artefacts are used for.  

### Reproduction

Open any SBOM published by the platform build.

**Comment by ZheSun88** [comment]
this description seems coming from the `vaaidn-parent` project, which is the parent for all vaadin artifacts. 

for fix this properly, we should add the description tag to components modules (same with flow artifacts.)
