### ISSUE TITLE
PiT 24.2: there are some starters not being updated

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#4411]
### Describe the bug

The following starters are not updated when a new vaadin release is delivered

- spreasheet-demo
- business-app-starter-flow

**Comment by manolo** [comment]
we need still to configure TC build

**Comment by ZheSun88** [comment]
the following two starters have been added now. 
```
"business-app-starter-flow":{
        "branch": ["v24", "v23", "v14"]
    },
"spreadsheet-demo":{
        "branch": ["v24", "v23"]
    }
```
