### ISSUE TITLE
Common Java interface for input field components

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#4489]
## Description
A generic Java interface for input field components, combining all of the functional interfaces they have in common.

## Details
Input field components like TextField, ComboBox, RadioButtonGroup, etc, have a lot of features in common. Most of these features are defined in separate function-specific interfaces like `HasLabel`, `HasValue`, `HasEnabled`, etc. This has made it somewhat awkward to, for example, iterate over a set of input fields and perform common operations on them, as it has required casting each field either to the specific component class or one of the functional interfaces. The new `InputField` interface combines most of these separate interfaces into a single one, so that common field-component operations can be performed by casting only to that one interface. Example:
```java
this.getChildren().map(c->(InputField)c).forEach(field->{
    field.setEnabled(false);
    field.setWidthFull();
    field.setTooltipText(getTooltipFor(field));
});
```

## Use cases
As a developer
I want to iterate over input fields without casting them to specific interfaces
So that I can perform various common operations on them with less boilerplate code

## Acceptance criteria
- [x] InputField interface that extends
  - [x] HasEnabled
  - [x] HasLabel
  - [x] HasStyle
  - [x] HasTooltip
  - [x] HasSize
  - [x] HasValue
- [x] Refactoring of input field component classes to implement InputField instead of the separate functional interfaces.

## General criteria
- [x] APIs reviewed 

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by knoobie** [comment]
Note for future people seeing this: `HasHelper` is missing because `CheckBox` does not support it at the moment.
