### ISSUE TITLE
Unable to build project using JDK 21

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#4668]
### Describe the bug

```
[INFO] --- exec:3.0.0:exec (gradle) @ vaadin-gradle-plugin ---
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileTestKotlin'.
> Unknown Kotlin JVM target: 21

```

### Expected-behavior

Compiles

### Reproduction

`mvn install`

### System Info

mac

**Comment by ZheSun88** [comment]
that is strange.. which branch did you run into this issue?

with the latest branch. 
we have a JDK test build which runs JDK 21, 22 and 17.. all tests are passed. 

also by only calling `mvn install`, platform should not touch anything regarding gradle..

**Comment by ZheSun88** [comment]
can reproduce with running 

`./gradlew build` on **vaadin-gradle-plugin** module

**Comment by ZheSun88** [comment]
let us revisit this issue when the full support from gradle has been updated. https://docs.gradle.org/current/userguide/compatibility.html

**Comment by benstpierre** [comment]
@ZheSun88 Gradle 8.5 is out and supports JDK 21

**Comment by ZheSun88** [comment]
yes we have updated grade 8.5 https://github.com/vaadin/platform/pull/4753 
may i know which Vaadin version you are using?

**Comment by Legioth** [comment]
Assuming this has been fixed by now...
