### ISSUE TITLE
cannot add vaadin pro licence to docker build

### ISSUE THREAD

**Issue by tombosa** [vaadin/platform#4680]
### Describe the bug

The vaadin docs mention that in order to add a licence to a -P prod built you should add it to the machine that builds the production build in the ~/.vaadin/offlineKey folder. However, we changed our way of building projects and now we do that using the docker file. We build our dockerfiles on a number of virtual machines that are created an destroyed just to build it. Hence we cannot add the licence to this folder on the machines. Also dockerfiles don't just have access to the file system.

I tried: I downloaded a server key and added it to the docker file in the maven commands as is specified in the docs:
1) i created ~/.vaadin/offlineKey folder , if i do that and run a production build i get the followign error: "Unable to validate the license, please check your internet connection. If you need to work offline then please go to https://vaadin.com/pro/validate-license?getOfflineKey=mid-ef05ac4a-266d8512 to retrieve an offline key."

2) when i use a flag in my maven command i get the following error:  "Failed to execute goal com.vaadin:vaadin-maven-plugin:24.2.0:build-frontend (default) on project gdpr-frontend: Execution default of goal com.vaadin:vaadin-maven-plugin:24.2.0:build-frontend failed: Invalid offline key, please go to https://vaadin.com/pro/validate-license?getOfflineKey=mid-ef05ac4a-266d8512 to retrieve an offline key.
#15 81.03 [ERROR] For CI/CD build servers, you need to download a server license key, which can work offline to create production builds. You can download a server license key from https://vaadin.com/myaccount/licenses."

my maven commands in the docker file:
RUN mvn --batch-mode --settings maven-settings.xml -q dependency:go-offline
RUN mvn --batch-mode --settings maven-settings.xml versions:set -DnewVersion=${NEW_VERSION} \
    && mvn --batch-mode --settings maven-settings.xml clean package -Pproduction -Dvaadin.offlineKey=[myserverkey] && rm -rf ./target/*.original \
    && mvn --batch-mode --settings maven-settings.xml -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install -Pproduction org.jacoco:jacoco-maven-plugin:report

Could somebody help

### Expected-behavior

my production build should use the licence

### Reproduction

We use a two stage docker file, the first stage builds the project, and here we get stuc. The docker commands are :
RUN mvn --batch-mode --settings maven-settings.xml -q dependency:go-offline
RUN mvn --batch-mode --settings maven-settings.xml versions:set -DnewVersion=${NEW_VERSION} \
    && mvn --batch-mode --settings maven-settings.xml clean package -Pproduction -Dvaadin.offlineKey=[myserverkey] && rm -rf ./target/*.original \
    && mvn --batch-mode --settings maven-settings.xml -DskipTests org.jacoco:jacoco-maven-plugin:prepare-agent install -Pproduction org.jacoco:jacoco-maven-plugin:report

### System Info

docker using maven:3.9.5-eclipse-temurin-17 as base image

**Comment by Artur-** [comment]
In the first case it sounds like your file is not in the correct place and it is not found

In the second case it says ”invalid offline key” which indicates that something is passed as the offline key but it is corrupted in some way

**Comment by Artur-** [comment]
Make sure you are creating .vaadin folder in the homedir and not in a folder named ”~”

**Comment by tombosa** [comment]
Indeed, the folder should be /root/.vaadin and not ~/.vaadin, which is mentioned in the docs. Thank you, adding the folder works and my licence is used to build the project. Thanks for your help
