### ISSUE TITLE
Multi-Select Combo Box features

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#4682]

**Comment by silas229** [comment]
Please also add the ability to set a prefix as in the normal combo box

https://vaadin.com/docs/latest/components/combo-box#prefix

**Comment by rolfsmeds** [comment]
@silas229 could you please create a separate ticket about that in https://github.com/vaadin/web-components/issues ?

**Comment by silas229** [comment]
Here it is: https://github.com/vaadin/web-components/issues/6858
