### ISSUE TITLE
Auto-update Hilla repos

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#4720]
### Describe your motivation

It would be helpful if Vaadin bot would automatically update the **main branches** of Hilla repos (at least when new minors and patches of Hilla are released):

- https://github.com/vaadin/skeleton-starter-hilla-react
- https://github.com/vaadin/skeleton-starter-hilla-react-gradle
- https://github.com/vaadin/skeleton-starter-hilla-lit
- https://github.com/vaadin/skeleton-starter-hilla-lit-gradle
- https://github.com/vaadin/observability-kit-hilla-demo
- https://github.com/vaadin/hilla-crm-tutorial
- https://github.com/vaadin/hilla-quickstart-tutorial
- https://github.com/vaadin/hilla-basics-tutorial
- https://github.com/vaadin/hilla-multi-module

**Comment by ZheSun88** [comment]
- most of the repos have been added in the list. for hilla 2.4.0, the trigger was not added to hilla starter update build. now it is there.
- `observability-kit-hilla-demo` is the one created by us for other use. we will take care of it later. 
- `hilla-multi-module` :
  - i have rename the main branch to `v2`, to align the versions with other starter projects
  - this project is running hilla 2.0, probably need to manually do some code change, will check.

**Comment by ZheSun88** [comment]
done.

**Comment by tarekoraby** [comment]
@ZheSun88, many (or all) of the repos haven't been automatically updated to 2.5.0 or 2.5.1. For example

- https://github.com/vaadin/hilla-crm-tutorial
- https://github.com/vaadin/skeleton-starter-hilla-react
- https://github.com/vaadin/skeleton-starter-hilla-lit

**Comment by ZheSun88** [comment]
the issue is hilla 2.5.1 build has failed so the following build has not been triggered. 
i have trigger an update now..

**Comment by tarekoraby** [comment]
But 2.5.0 also didn't update properly (e.g., it didn't update https://github.com/vaadin/hilla-crm-tutorial).

**Comment by ZheSun88** [comment]
that one is because of the branch trigger has not been added to the build. 
i have fixed that too.
