### ISSUE TITLE
24.2.6 planed for this week?

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#4793]
### Describe your motivation

Annoying bugs that are already fixed / reverted to reduce problems in the wild.

### Describe the solution you'd like

A new release today or tomorrow :)

**Comment by web-padawan** [comment]
Thanks for the issue. Today most of the team is away due to the holiday in Finland. I'll remind about this tomorrow.

**Comment by ZheSun88** [comment]
what are the issues that you are referring? I can check and help with the release.

**Comment by ZheSun88** [comment]
the web-component issue has been released. so let us ask flow for the following actions on their side.. 
maybe just reverting the commit is not enough, so we might need to wait

**Comment by knoobie** [comment]
@ZheSun88 How is it going? :D Looking good or neh? :)

**Comment by knoobie** [comment]
No worries, I upgraded saturday to 24.3.0.rc1 in the meantime, we have an audit coming up therefore I had to push a release with fixes available

**Comment by ZheSun88** [comment]
24.2.6 has been released. the issue mentioned in this ticket has been included. 

there is a new flow version with DnD fixes coming, so Vaadin 24.2.7 will come next including those change. 

I am closing this ticket.
