### ISSUE TITLE
Auto-update Flow-Hilla hybrid

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/platform#4835]
### Describe your motivation

The [Flow-Hilla hybrid example](https://github.com/vaadin/flow-hilla-hybrid-example) should be updated with new versions of 

- Flow
- Hilla
- Spring Boot

**Comment by ZheSun88** [comment]
project has been added to both platform and hilla update build. 

also added the feature to bump spring boot parent project version, if they are available under the same minor.  it is not a good idea for major or minor updates, as normally, those will need code change by hand.
