### ISSUE TITLE
Create a test for checking snapshot versions

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#491]
Create a test that verifies that the maven dependency tree doesn't contain any snapshot versions. Run for every PR if possible.

**Comment by juhopiirainen** [comment]
Create a script 
- that checks if versions.json contain any SNAPSHOT references
- that checks if versions.json contains any alpha/beta/rc references
- parameter that turns alpha/beta/rc testing off (for platform pre-release versions)
Add script run to platform release

**Comment by juhopiirainen** [comment]
Closed by https://github.com/vaadin/platform/pull/1228

**Comment by ZheSun88** [comment]
Snapshot checking is done with using `maven-enforcer-plugin` in #1228 (need to be cherry-picked)
prerelease version checking has been done by adding script into release configuration. no separate parameter is needed, as we take existing `staging.profile` into account
