### ISSUE TITLE
Migrate Hilla modules to Platform

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#4926]
**Remove from Hilla repo**
hilla-spring-boot-starter
hilla-react-spring-boot-starter
hilla-maven-plugin ?

**Rename**
hilla to hilla-lit

**Update**
vaadin-core including hilla-react (what todo with hilla-lit if they are incompatible ?)
vaadin-spring-boot-starter including hilla-react-spring-boot-starter (what to do with the lit part ?)
vaadin-maven-plugin must consider hilla-maven-plugin actions somehow?
what about dev-server stuff?

**User Migration Path**
- Users of dev.hilla:hilla-react should migrate vaadin-maven-plugin and just com.vaadin:vaadin
- Users of dev.hilla:hilla should migrate to com.vaadin.hilla:hilla-lit (and vaadin-maven-plugin)
- Users of com.vaadin:vaadin should generally not migrate, and our aim is to include com.vaadin.hilla:hilla-react for them.
- Users of com.vaadin:vaadin that want to use hilla-lit they need to add com.vaadin.hilla:hilla-lit

**Comment by Artur-** [comment]
Why not create ”hilla” instead of separate ”hilla-react” and ”hilla-lit”?
