### ISSUE TITLE
Add Hilla module as a dependency to Platform

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#4934]
### Describe your motivation

Make `com.vaadin:vaadin` (or `vaadin-core` or `vaadin-spring-boot-starter`, to be discussed and researched) depend on the `com.vaadin.hilla:hilla` artifact, which includes the `endpoint` and `engine-runtime`, so if the `hilla` isn’t desired, one can exclude the whole `hilla` dependency.

### Additional context

Vaadin/Hilla 24.4

**Comment by knoobie** [comment]
Thanks for not adding it to `vaadin-core` :)

**Comment by mshabarov** [comment]
Well, just changed it to `vaadin-core` :)
But indeed I'm not sure 100% what would be the best place for it.
Let me highlight it in the ticket.

**Comment by knoobie** [comment]
5 seconds thought: Hilla requires Spring, therefore it should be in the spring starter as dependency? Vaadin and Vaadin Core does not require Spring

**Comment by mshabarov** [comment]
We cannot really add `hilla` to `vaadin-core` until we split `react-components` into core and all, as requested [https://github.com/vaadin/platform/issues/4936](here).
