### ISSUE TITLE
Add Vaadin react-component into version.json

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#4936]
### Describe your motivation

[Vaadin react-components](https://github.com/vaadin/react-components) currently have no split to "core" and "commercial" parts like [Vaadin web-components](https://github.com/vaadin/web-components) do.

That might lead to a problem of leaking commercial react components into an application that only imports `com.vaadin:vaadin-core` artifact.

**Acceptance Criteria:**
- [x] Add react-components into Platform's `version.json` with no split.
- [x] React-components has a split to "core" and "commercial" components possible in the same way as web-components do, e.g. by having the license entry in the `package.json`, see https://github.com/vaadin/react-components/issues/229
- [x] Add `react-components-core` (the name should be discussed, e.g. react-core-components or react-components-all) dependencies into Platform's `version-core.json`.
- [x] Flow then chooses between react or web-components package/dependency in generated `package.json` based on the `reactRouterEnabled` flag in Flow or auto-detection mechanism, see https://github.com/vaadin/flow/issues/18506.

### Additional context

Vaadin/Hilla 24.4.

**Comment by manolo** [comment]
There is a missing task in the description
- [ ] Remove the `vaadin-core-versions.json` files from `hilla` and `hilla-react` artifacts

platform `vaadin-core-versions.json` brings already `hilla-react-components` and flow should select the appropriate entries from here depending on the `reactRouterEnabled` flag or whatever
