### ISSUE TITLE
Grid API for conditional selectability

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#4956]
## Description
An API in Grid for dynamically setting whether the user can select or deselect an item (row) in the Grid.
(Similar e.g. to PartNameGenerator and TooltipGenerator)

## Use cases
As a user
I want to be able to select only those items that should be selectable
So that I can select valid items

## Acceptance criteria
- [ ] Java API for setting a selectability function `setItemSelectable(SerializableFunction<T,boolean> selectabilityFunction)`
- [ ] WC API `isItemSelectable` callback function
- [ ] Items for which the function returns false should be rendered with a disabled checkbox in multiselect row, not propagate a selection event, and the server should ignore selections on those items.
- [ ] Programmatically selecting or deselecting items is not affected by this
- [ ] Drag-select should skip unselectable items
- [ ] Part names should reflect non-selectability: `nonselectable-row` and `nonselectable-row-cell`
- [ ] Modify clientside single-select example to call the function to determine selectability.

(precise naming of API is open for suggestions, the above is just a proposal)

## General criteria

- [ ] APIs reviewed 

- [ ] Performance (let's test!) 

- [ ] UX/DX tests in Alpha 

- [ ] Documentation: (to be added to Grid docs) 

- [ ] How to test? 

- [ ] Limitations: 

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by knoobie** [comment]
>  Items for which the function returns false should be rendered with a disabled checkbox in multiselect row, and simply not allow selection

Should there be a tooltip / reason why the checkbox is disabled or should the checkbox not be rendered at all?

**Comment by rolfsmeds** [comment]
> Should there be a tooltip / reason why the checkbox is disabled or should the checkbox not be rendered at all?

I would expect that, in most use cases, the reasons for some items being disabled from selection would be fairly obvious from the context in which selection happens, and, even if it's not, the reason would probably be the same for _all_ items, in which case a text somewhere adjacent to the Grid would serve better than per-item tooltips.

We discussed whether the checkbox should be disabled or entirely hidden, but my hunch is that it's better to keep it visible but disabled so that users see that there _is_ selection in the Grid, even if all none of the items currently in the viewport can be selected. There are also use cases where some items can be selected _and_ disabled, i.e. un-deselectable, in which case we definitely need to show the checkbox.

**Comment by AndreGlauserAtWork** [comment]
> > Should there be a tooltip / reason why the checkbox is disabled or should the checkbox not be rendered at all?
> 
> I would expect that, in most use cases, the reasons for some items being disabled from selection would be fairly obvious from the context in which selection happens, and, even if it's not, the reason would probably be the same for _all_ items, in which case a 

If there were a list of people in a grid, where users that did not have an email address or phone number could not be selected. Of course, these users could be filtered out from the grid, but lets assume that all users are in the grid. I would need to show why this role could not be selected. Having a note or footer text which states "users with no phone number or email can not be selected" is possible but it seems more user friendly to me that a tooltip for that unselectable row would be clearer to the user? The reason could be more complex per row as a calculation from the data for example, then the tooltip would have a more complex description also.

**Comment by knoobie** [comment]
Vote for: Use this feature request / question as example in the docs to show that it is possible with the regular tooltip feature of the Grid. That also comes with the added benefit that the tooltip is visible on the whole row - and not just the single column / disabled checkbox.

**Comment by AndreGlauserAtWork** [comment]
@rolfsmeds I have a use case with a list of transactions in the grid and there are several ways that the transaction can be disabled for selection and the transaction data is used to calculate it differently for each row. So, in this case a reason for each row has to be on the row as a tooltip. I was not saying that a tooltip should be part of the task, just that the use case is not so uncommon.

Until this new API is available: I use the partNameGenerator to style the row differently, and a tooltip for the whole row to explain why that row is disabled. The first-column-cell gets disabled in CSS using the various partNames.
Maybe not the best UX for this, but I could not think of a better way yet.

**Comment by strailov** [comment]
Hello @rolfsmeds 
I find this feature very useful and I started using it. However once I apply my predicate for the grid using  `setItemSelectable` the checkbox for selecting all rows seems not present. 
Is this on purpose or is this a bug ? 
From my perspective you should still be able to select all the remaining rows which match the predicate.
