### ISSUE TITLE
New React hybrid application test module

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#4972]
### Describe your motivation

Add a new test module into platform and smoke tests for React hybrid application.

Existing Lit hybrid app can be used for a reference and also https://www.github.com/vaadin/flow-hilla-hybrid-example.

### Additional context

Vaadin 24.4.

**Comment by mshabarov** [comment]
[Hybrid Test module](https://github.com/vaadin/platform/tree/main/vaadin-platform-hybrid-test) in Platform has already some test views and one route.
These are the things that would be profitable to add:
1. FS-based routing views structure - @index.tsx and couple of views with a custom name
2. Hilla auto layout - @layout.tsx
3. Auto menus in @layout.tsx
4. Spring stateful security layer - ViewConfig for client views and annotations for server views
5. Flow main layout (can be in the same app, but with a separate url mapping)
6. Auto menus in MainLayout
7. Various navigation test cases - using React nav elements, RouterLinks, UI.navigate, forwardTo/redirectTo
8. Navigation lifecycle events handling on server: that event is triggered with expected number of times
9. Server-side API for browser navigation: `History::back/forward`, `History::pushState/replaceState`.

**Comment by caalador** [comment]
I would have security in a separate module.

**Comment by caalador** [comment]
Should add deep nested layouts to the non security mixed test after https://github.com/vaadin/hilla/pull/2853 is merged.
