### ISSUE TITLE
Rename jsVersion

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#499]
In `versions.json` there are two fields for frontend component versions: `jsVersion` and `npmVersion`. While the former was correct when there was only one version for frontend, it should be renamed for clarity.

Rename `jsVersion` to `bowerVersion`.

**Comment by ZheSun88** [comment]
- bowerVersion doesn't make sense after V14, as we are going to drop the support for bower.
- some vaadin elements have different versions for P2 and P3, and the P3 version name has been named `npmVersion`. so we need to solve this carefully.

**Comment by juhopiirainen** [comment]
We keep the current names.
