### ISSUE TITLE
Test snapshot versions with Java starters

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#501]
Create smoke-test level integration tests for each Java starter. (see https://github.com/vaadin/flow-starters for an example)

Then create a new daily build:

* Clone the latest versions of starters
* Update them to use the latest platform snapshot
* Build
* Run tests & report errors

**Comment by ZheSun88** [comment]
tests have been written for all the starters and snapshot validation has been running for all the starters. 
https://bender.vaadin.com/project.html?projectId=Flow_StarterTests&tab=projectOverview

ticket can be closed now
