### ISSUE TITLE
Test snapshot versions with Polymer starter

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#502]
Create smoke-test level integration tests for the Polymer frontend starter. 

Then create a new daily build:

* Clone the latest version of the starter
* Update it to use the latest platform snapshot
* Build
* Run tests & report errors

**Comment by web-padawan** [comment]
> Polymer frontend starter

The repo previously known as a "Polymer frontend starter" is now archived.

https://github.com/vaadin/generator-polymer-init-vaadin-elements-app

@juhopiirainen feel free to close.

**Comment by juhopiirainen** [comment]
Thanks @web-padawan
