### ISSUE TITLE
PiT 24.4: spring gs-crud-with-vaadin do not work in 24.4 in dev-mode

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#5041]
### Describe the bug

`pom.xml` file in the [spring guide](https://github.com/spring-guides/gs-crud-with-vaadin/blob/main/complete/pom.xml#L78) project does not have the vaadin-maven plugin in the `build` [block](https://github.com/spring-guides/gs-crud-with-vaadin/blob/main/complete/pom.xml#L63), though it has the plugin for the [production](https://github.com/spring-guides/gs-crud-with-vaadin/blob/main/complete/pom.xml#L78) mode.

It makes dev-mode fail since new vaadin maven plugin needs to execute `vaadin:configure` goal for hilla tasks

```
java.lang.IllegalStateException: com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine

```

The project should be updated by adding the plugin to the top level `build` block

### Expected-behavior

`vaadin:configure` works

### Reproduction

```
## Clone the project
git clone https://github.com/spring-guides/gs-crud-with-vaadin.git
cd gs-crud-with-vaadin/complete
## Change the vaadin version
perl -0777 -pi -e 's|(<vaadin.version>)([^\s]+)(</vaadin.version>)|${1}24.4.0.alpha3${3}|g' pom.xml
## Add pre-releases repos
perl -pi -e \
  's|(\s*)(</properties>)|$1$2\n$1<repositories><repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></repository></repositories>|' \
  pom.xml
perl -pi -e \
  's|(\s*)(</properties>)|$1$2\n$1<pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></pluginRepository></pluginRepositories>|' \
  pom.xml
## Run the project
./mvnw  spring-boot:run

```

### System Info

Vaadin 24.4.0.alpha3

**Comment by mcollovati** [comment]
The issue should probably be fixed by https://github.com/vaadin/hilla/pull/2031, without adding the plugin configuration
