### ISSUE TITLE
Upload not work after changing Vaadin version from 24.1.7 to 24.3.5

### ISSUE THREAD

**Issue by shar013** [vaadin/platform#5123]
### Describe the bug

Dropping a file on the upload control causes a java.lang.ClassNotFoundException: org.apache.commons.io.function.IOIterator
Reverting to 24.1.7 causes the upload to work as intended. I also changed the Spring Boot version from 3.1.3 to 3.2.2 in case that was the problem but that has no effect. It works okay with Vaadin 24.1.7 with either version of Spring Boot. Attached is a log snippet that shows it not working and then working agin.
[CopsWeb.log](https://github.com/vaadin/platform/files/14454434/CopsWeb.log)

The relevant (Kotlin) source code is:

		val buffer = MemoryBuffer()
		val upload = Upload(buffer)
		upload.setAcceptedFileTypes(".xls", ".xlsx")
		log.debug("[DispatchManifestViewLayout] upload folder: {}", copsService.spreadsheetFolderPath)
		upload.addStartedListener {
			log.debug("[DispatchManifestViewLayout] upload started: {}", it)
		}
		upload.addFinishedListener {
			log.debug("[DispatchManifestViewLayout] upload finished: {}", it)
		}
		upload.addSucceededListener { 
			val filename = it.fileName
			val mimeType = it.mimeType
			log.debug("[DispatchManifestViewLayout] uploaded: {} mimeType: {}", filename, mimeType)
			processUpload(filename, buffer.inputStream)
		}
		upload.addFailedListener { 
			val reason = it.reason
			log.error("upload failed (see stack trace", reason)
			notifyFailure(reason.localizedMessage)
		}

### Expected-behavior

Dropping a file on the upload control should cause it to upload the file.

### Reproduction

I can't help you with that. Sorry.

### System Info

Windows 11, Vaadin 24.3.5, Chrome Browser (same behaviour in Firefox) The IDE I'm using is Intellij. Same behaviour if I run the app  via the run button in the IDE or via the spring-boot:run goal.

**Comment by Artur-** [comment]
Sounds like you have a too old commons-io on the classpath. org.apache.commons.io.function.IOIterator was dded in 2.12.0

**Comment by shar013** [comment]
Yes that's right:
C:\Users\Steve\.m2\repository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar
Umm... How to fix?

**Comment by shar013** [comment]
Thanks. It's a dependency of org.apache.poi:poi-ooxml:5.2.2. I've changed that to 5.2.5 which has commons-io:commons-io:2.15.0.
Pressed the wrong button earlier.

**Comment by shar013** [comment]
Thanks. A test run confirms this is fixed.
