### ISSUE TITLE
Dialog content padding

### ISSUE THREAD

**Issue by francoRolandoQubika** [vaadin/platform#5197]
### Describe your motivation

If we want in runtime set different padding for dialog surface - based on the dialog content - we need to use different classnames and add it to the dialog.
it means if the dialog is small I want a padding of 12px 16px, but if it's big I want 32px 36px.
So we need to have at least 2 classes but if we want more variety we need more classes.

### Describe the solution you'd like

So I propose adding a method to add padding style to the dialog surface.

### Describe alternatives you've considered

I tried using getElement().getStyle().set("padding", "...") but does not work

### Additional context

Vaadin 24.2.0

**Comment by knoobie** [comment]
You could add the padding to the root element you are adding to your dialog. No need to further customize the outer layer.

**Comment by francoRolandoQubika** [comment]
But also I want to add padding to the header but sometimes will be 16 from top or 32

**Comment by knoobie** [comment]
I have high doubt that this is going to be changed in the future.. tho.. you need alternatives. 

Another approach could be to play around with a css variables in your css and customize that variable from the element API; but I doubt it's worth the hazzle in contrast to simply create 2-3 classes depending on your need - needing more sounds like bad UX design.

**Comment by francoRolandoQubika** [comment]
I just used variables and worked well. Looks like variables can only be assign through UI.getCurrent() instance.

 But yes IMO is also something weird with my UX designer.
