### ISSUE TITLE
Split react-components into core and pro parts

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#5204]
### Describe your motivation

Vaadin Core / open source users should be able to use core/free React components without Vaadin license.

### Describe the solution you'd like

Acceptance Criteria:
- [x] React components are split into `@vaadin/react-components` (free) and `@vaadin/react-components-pro` (commercial) npm packages, [this change](https://github.com/vaadin/react-components/pull/230) is re-applied
- [x] Platform [versions](https://github.com/vaadin/platform/blob/main/versions.json) has `react-components` in `core` and `react-components-pro` in `vaadin`
- [x] Flow adds `@vaadin/react-components-pro` package into `package.json` in `vaadin` dependency is used in a project. `@vaadin/react-components` are added for both `vaadin-core` and `vaadin`.

Note: this is planned between 24.4 beta and GA, so that these changes don't block beta release and beta testing.

### Additional context

Vaadin 24.4.

**Comment by web-padawan** [comment]
Created the React components split PR: https://github.com/vaadin/react-components/pull/242

**Comment by caalador** [comment]
Flow will pick/discard react components by the mode flag ("mode": "react") in the versions files and both `vaadin-core-versions.json` and `vaadin-versions.json` are always checked if available so for Flow there is nothing extra for step 3 to add.

Extended test to check this case explicitly: https://github.com/vaadin/flow/pull/19103

**Comment by mshabarov** [comment]
React-componets split https://github.com/vaadin/react-components/pull/242.

**Comment by ZheSun88** [comment]
i have pushed a branch in platform with the necessary changes. let us wait after beta 
https://github.com/vaadin/platform/tree/react-component-pro

**Comment by mshabarov** [comment]
Done. Tested with having `vaadin` and `vaadin-core`. Vaadin adds `react-components-pro` in the first case and does not in the second case.
