### ISSUE TITLE
Test Platform (24.4+) against the upcoming Spring Boot 3.3-rc.1+

### ISSUE THREAD

**Issue by knoobie** [vaadin/platform#5251]
### Describe your motivation

Title says it all :) 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes

**Comment by ZheSun88** [comment]
Now we should consider to spring boot 3.4 ;-), i will close this issue.

**Comment by knoobie** [comment]
I save myself the work to create one for 3.4 - I saw your PR in flow :) Thanks for it!
