### ISSUE TITLE
Vaadin Charts

### ISSUE THREAD

**Issue by cehorn** [vaadin/platform#5257]
### Describe the bug

none?

### Expected-behavior

I attend the University of Arkansas and use IntelliJ for a computing course. I have the student developer package, and to my understanding have access to Vaadin Pro utilities. When running my Vaadin, I have a button that is supposed to display a chart but displays this:
![Screenshot 2024-04-21 205551](https://github.com/vaadin/platform/assets/143007103/003244f9-f0cb-4f73-bcd9-0bd66111ec75)
I've done troubleshooting, clear cache, log in and out, and it does not seem to recognize my account to see the chart. Does the student developer package not allow to see charts? Or is there an issue with syncing the accounts?

### Reproduction

none?

### System Info

I am using a Dell Inspiron 14, running IntelliJ under a Vaadin Template and running the code, with pop up page in Google.

**Comment by ZheSun88** [comment]
Hi @cehorn , can you tell us which vaadin version are you using?(you can find it in your `pom.xml`)

**Comment by ZheSun88** [comment]
Hi again @cehorn, we have had one fix just got deployed. Can you retry your project and let us know?

**Comment by cehorn** [comment]
It stills says "no license found" and I can't access the chart.

**Comment by ZheSun88** [comment]
Hi @cehorn , a new fix regarding this issue has been applied, may i ask you to test again? thanks

**Comment by ZheSun88** [comment]
HI @cehorn  i am going to close this ticket due to long time no responds. 
feel free to reopen it if the issue still exists.
