### ISSUE TITLE
Lumo compact theme should have a proper Java abstraction

### ISSUE THREAD

**Issue by johannesh2** [vaadin/platform#535]
Instead of using `@HtmlImport`, I would like to see a proper Java abstraction. Most logical to me would be to use `@Theme` either with some additional mode like `compact = true`  or maybe better would be `@Theme(LumoCompact.class)`

**Comment by pleku** [comment]
Issue moved to [vaadin/flow #5029](https://github.com/vaadin/flow/issues/5029) via [**ZenHub**](https://www.zenhub.com/)
