### ISSUE TITLE
Use templating language for ShadyCSS?

### ISSUE THREAD

**Issue by ujoni** [vaadin/platform#542]
Currently `template-vaadin-bom.xml` uses pinned ShadyCSS version instead of template markup:

```
<!-- Shadycss 1.8.0 is the latest bower based release for shadycss -->
<dependency>
    <groupId>org.webjars.bowergithub.webcomponents</groupId>
    <artifactId>shadycss</artifactId>
    <version>1.8.0</version>
</dependency>
```

Is there a reason for this or should the version be changed to use template markup?

**Comment by ZheSun88** [comment]
shadycss has been known to cause issues when it is updated to a version that doesn't work for one reason or another. that is why we hard coded the version there and don't want to change it easily. 

by the way, even till now, the 1.8.0 is still the only version in 1.8.X and the project has been **archived** so I guess we can close this ticket.
