### ISSUE TITLE
Don't show components in Grid in Chrome.

### ISSUE THREAD

**Issue by evgenru** [vaadin/platform#557]
In versions 12.0.2 - 12.0.6
In 10.0.10 is ok.

![image](https://user-images.githubusercontent.com/3337004/52983034-ed79a380-340a-11e9-8239-53ae5bf44770.png)
after change width any column:
![image](https://user-images.githubusercontent.com/3337004/52983079-2580e680-340b-11e9-8f5e-2d335e6b7320.png)

`code:

        grid = Grid(InterviewEntity::class.java)
        grid.columns.forEach { grid.removeColumn(it) }
        grid.addColumn(InterviewEntity::id.name).setHeader("ID").setFlexGrow(0).width = "50px"
        grid.addColumn(InterviewEntity::name.name).setHeader(fieldNames[InterviewEntity::name])
                .setFlexGrow(10).setResizable(true).isSortable = true
        grid.addComponentColumn { Anchor("${Constants.PRIVATE_API_V1_PREFIX}/interview/${it.id}/report", "Отчет") }
                .setHeader("Отчет").setFlexGrow(10).setResizable(true).isSortable = true
        grid.addColumn { it.group?.name }.setHeader(fieldNames[InterviewEntity::group])
                .setFlexGrow(10).setResizable(true).isSortable = true
        grid.addColumn { it.template?.name }.setHeader(fieldNames[InterviewEntity::template])
                .setFlexGrow(10).setResizable(true).isSortable = true
`

and with combobox...
![image](https://user-images.githubusercontent.com/3337004/52983143-7abcf800-340b-11e9-94e0-f03d6b747fbf.png)
after change width any column:
![image](https://user-images.githubusercontent.com/3337004/52983174-a9d36980-340b-11e9-814d-68291027e9d0.png)

**Comment by evgenru** [comment]
Only in chrome.... :(

**Comment by alvarezguille** [comment]
Hi @evgenru, thanks for reporting this.
The chrome issue was originally reported in https://github.com/vaadin/vaadin-grid-flow/issues/502 and https://github.com/vaadin/flow/issues/5025 and fixed in https://github.com/vaadin/flow/pull/5060
The fix was released in flow [1.2.5](https://github.com/vaadin/flow/releases/tag/1.2.5) and will be included in next 12.0.x release

**Comment by alvarezguille** [comment]
Just for the record, the fix was also included in flow [1.0.9](https://github.com/vaadin/flow/releases/tag/1.0.9) to be included in next 10.0.x release.

**Comment by alvarezguille** [comment]
The fix for this was included in [12.0.7](https://github.com/vaadin/platform/releases/tag/12.0.7)
