### ISSUE TITLE
IE11 & Edge fail

### ISSUE THREAD

**Issue by adexerivera** [vaadin/platform#572]
We can't make work our vaadin application on IE11 or Edge. We are using vaadin version 10.0.11.

View image with webcomponent-lite.js error.

We use maven for dependencies, through some dependency we've this webcomponentsjs versions:

- org.webjars.bowergithub.webcomponents:webcomponentsjs:1.2.0
- org.webjars.bowergithub.webcomponents:webcomponentsjs:1.2.6

![errorsie11 edge01](https://user-images.githubusercontent.com/1585009/53641200-22b19d00-3c26-11e9-8728-fbd2f5a296fa.PNG)

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/flow #5207](https://github.com/vaadin/flow/issues/5207) via [**ZenHub**](https://www.zenhub.com/)
