### ISSUE TITLE
Compile list of changes per release

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/platform#576]
It would be handy if platform release notes contained (or linked) a list of all fixes and BFPs that are included since the last release.

**Comment by OlliTietavainenVaadin** [comment]
Even better if this was a curated list (omitting "boring" entries that don't affect the end user)

**Comment by juhopiirainen** [comment]
We have improved the human readable list of changes in the new and noteworthy section of the release notes. 
All the changed components per release are shown and all the changes made can be checked from there. A list of all the changes sounds a bit overkill in the release notes.

**Comment by OlliTietavainenVaadin** [comment]
@juhopiirainen could we at least have BFP fixes listed? Just to give them more visibility (and us a better way of check if a fix made it to a certain release or not, since that's something that's asked quite often).

**Comment by juhopiirainen** [comment]
Good point. We'll try to incorporate BFPs to individual modules release notes and pick the BFP marked changes to platform release notes.
