### ISSUE TITLE
PiT 24.4: remove deprecated API usage in starters

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#5831]
### Describe the bug

There are a bunch of starters that are using deprecated API in 24.4

- [x] business-app-starter-flow
Deprecated API:
```
src/test/java/com/vaadin/starter/business/it/AccountsIT.java:[28,47] attributeContains(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
```

- [x] bookstore-example
Deprecated API:
```
src/test/java/org/vaadin/example/crud/SampleCrudViewIT.java:[71,31] attribute(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
```

- [x] bookstore-example:rtl-demo
Deprecated API:
```
src/test/java/org/vaadin/example/crud/SampleCrudViewIT.java:[71,31] attribute(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
```

- [x] bakery-app-starter-flow-spring
Deprecated API:
```
src/test/java/com/vaadin/starter/bakery/testbench/elements/components/OrderCardElement.java:[11,56] attributeContains(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
src/test/java/com/vaadin/starter/bakery/testbench/elements/components/OrderCardElement.java:[18,36] attributeContains(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
src/test/java/com/vaadin/starter/bakery/testbench/elements/ui/OrderItemEditorElement.java:[27,59] attribute(java.lang.String,java.lang.String) in com.vaadin.testbench.ElementQuery has been deprecated
```

### Expected-behavior

no usage of deprecated

### Reproduction

.

### System Info

V 24.4.0.beta2

**Comment by ZheSun88** [comment]
this deprecation has been introduced since Vaadin testbench [9.3.0.alpha1](https://github.com/vaadin/testbench/releases/tag/9.3.0.alpha1) 

at this moment, we cannot update the starters' `v24` branch to use it, as they are still using Vaadin 24.3.x 
we will revisit those after v24.4.0 got released.

**Comment by ZheSun88** [comment]
https://github.com/vaadin/business-app-starter-flow/pull/364
https://github.com/vaadin/bookstore-example/pull/337
https://github.com/vaadin/bookstore-example/pull/338
https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1357

**Comment by ZheSun88** [comment]
merged PRs, tested one with https://github.com/vaadin/platform/actions/runs/9495138942
