### ISSUE TITLE
Components release notes in platforms release document

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/platform#625]
In the release notes of platform there is a title called "Changes since <last version>". The listing has all components that have changed. There is a hyperlink to release notes of that particular component. Could there be a list of all release notes of all components listed there, so you don't need to check every single hyperlink one-by-one.

Is this needed?

![kuva.png](https://images.zenhubusercontent.com/5ca5ff40db2165722f5b1e6b/512d06cc-2f2a-4bda-9652-26a53d36216c)

**Comment by ZheSun88** [comment]
there is one potential issue:
if one component got two updates in one release period, should we list both release note?

and one idea from Kari, we can list the version change, i.e. : `vaadin button (Flow integration 1.3.0 ->1.3.2, webcomponent v2.1.3 -> v2.1.5 )`

**Comment by juhopiirainen** [comment]
During the platform release we now create a separate file containing all the release notes of the changed modules. Releaser can pick-n-choose relevant parts to the platform release notes.
