### ISSUE TITLE
Simplify starters by adding a <defaultGoal>

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#646]
When pom.xml defines the default goal to use, any user can run the project as
```
mvn
```

**Comment by ZheSun88** [comment]
Default goal has been added to the following starters :

- [ ] beverage-starter-flow
- [ ] skeleton-starter-flow
- [ ] skeleton-starter-flow-spring
- [ ] skeleton-starter-flow-cdi
- [ ] bookstore-starter-flow
- [ ] bakery-app-starter-flow-spring
- [ ] component-starter-flow
- [ ] addon-starter-flow

the ticket can be closed now.
