### ISSUE TITLE
MAU stats collection doesn't fully work for 24.4 new parameters

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#6488]
### Describe the bug

Some of the parameters described [here](https://github.com/vaadin/platform/issues/6430) are not added into `~/vaadin/usage-statistics.json`, some of them even aren't added into registration array in the browser:

![image](https://github.com/vaadin/platform/assets/61410877/838a02b6-94e9-4065-9c75-94489b535fd0)

Apparently the stats collection for `usage-statistics.json` happens before the parameters are pushed into registration array.

### Expected-behavior

All parameters stats are recorded into `usage-statistics.json`.

### Reproduction

Any Vaadin 24.4 project with FS router, React in Flow, Flow in React.

### System Info

Vaadin 24.4.0.rc1

**Comment by mshabarov** [comment]
Re-tested with 24.4.0.rc2 and here is the results:

<img width="723" alt="Screenshot 2024-06-11 at 16 05 33" src="https://github.com/vaadin/platform/assets/61410877/d2e8cf56-0315-4912-8d96-15db16bfbd43">

last 4 parameters in the list are not reported in "usage-statistics.json" at all, `flow-router` is reported with snapshot version for some reason.

Other observation is that parameters like `has-flow-route`, which are recorded after navigation trigger, may not recorded immediately, but after next page reload, e.g. after live-reload or logout/login.

**Comment by mshabarov** [comment]
UPD: re-checked again the stats on the server and looks like all the new parameters stats reach the stats server normally.

We will monitor the stats and re-open this ticket or create a new one, if any anomaly is detected.

**Comment by jojule** [comment]
Tested again on
```
Hilla: 24.4.3
Flow: 24.4.4
Vaadin: 24.4.6
Copilot: 24.4.6
Copilot IDE Plugin: false
Java: Homebrew 21.0.3
Java Hotswap: false
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 14.5
Browser: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
```

Results on three projects created on start.vaadin.com:
- Flow view only, using precompiled bundle, works (just as before #19622)
- Hilla only, using hot deploy mode, does not work (just as before #19622)
- Both Flow and Hilla views, using hot deploy mode, does not work (just as before #19622)

Tested both on Safari and Chrome: `vaadin.statistics.basket` is not added to the local storage on either. Due to this, it will not get passed to `~/.vaadin/usage-statistics.json`.

**Comment by mshabarov** [comment]
Closing this issue in favour of https://github.com/vaadin/platform/issues/6720.
