### ISSUE TITLE
Vaadin 24 Hilla requires JPA

### ISSUE THREAD

**Issue by dwlabcube** [vaadin/platform#6508]
### Describe the bug

***************************
APPLICATION FAILED TO START
***************************

Description:

Field **em in com.vaadin.hilla.crud.JpaFilterConverter** required a bean of type 'jakarta.persistence.EntityManager' that could not be found.

### Reproduction

Spring boot 3.3.0
Vaadin 24.4.1

### System Info

Spring boot 3.3.0
Vaadin 24.4.1

**Comment by Artur-** [comment]
I don't see this when starting a new app so surely there is something more needed to run into this?

**Comment by dwlabcube** [comment]
You're right, sorry, i have a mess in my dependencies.
