### ISSUE TITLE
NPM Bundle needs different versions in Vaadin 24.4.4

### ISSUE THREAD

**Issue by subITCSS** [vaadin/platform#6549]
### Describe the bug

We discoverd another problem with the new version:
To create our sbom we check the npm references and getting this error:
```
npm error code ELSPROBLEMS
npm error invalid: @open-wc/dedupe-mixin@1.4.0 /node_modules/@open-wc/dedupe-mixin
```

The Issue we discovered is that the vaadin-bundles requires the fixed version of 1.3.1 for it
![image](https://github.com/vaadin/flow/assets/155952489/00c39b49-f9e5-4e15-8f4c-e9f0185d3c0d)

while all components require the ^1.3.0 and as there is an 1.4.0 the system updates the dependency to 1.4.0 which clashes with the upper fixed definition.
![image](https://github.com/vaadin/flow/assets/155952489/8bfff365-13b7-44fb-9b19-5d5988243219)

So based on this the Versions should be both fix or flexible using the ^.

### Expected-behavior

Both versions are defined identical

### Reproduction

Check the npm dependencies.

### System Info

Vaadin 24.4.4

**Comment by ZheSun88** [comment]
Thanks for the ticket.. i have applied the fix to vaadin/bundles.

**Comment by subITCSS** [comment]
When will this be solved/merged?

**Comment by ZheSun88** [comment]
vaadin 24.4.5 has been released a few while ago. Can you test again?

**Comment by ZheSun88** [comment]
ah, i see.. sorry for the inconvenience,  i will ask the team to merge those PRs and make another release ASAP

**Comment by ZheSun88** [comment]
Vaadin 24.4.6 has been released with the version fix in bundles
