### ISSUE TITLE
vaadin-maven-plugin starting from 24.4.X have lost m2e lifecycle-mapping-metadata.xml

### ISSUE THREAD

**Issue by xdenser** [vaadin/platform#6562]
### Describe the bug

I always get prod mode when try to run from Eclipse. I.e. goals are mapped incorrectly.

### Reproduction

Just use 24.4.4 in eclipse project that was working with 24.3.X.

### System Info

Vaadin 24.4.4, Windows 11, Eclipse 4.29

**Comment by Artur-** [comment]
How do you run the project in Eclipse?

**Comment by xdenser** [comment]
This is complicated - I have custom plugin that deploys and generates run configuration with everything needed on class path.
Actually it does not matter - because when I have something like this in my pom.xml
<plugin>
   <groupId>com.vaadin</groupId>
   <artifactId>vaadin-maven-plugin</artifactId>
   ...
 <goals>
   <prrepare-frontend>
   <build-fronted>
 </goals>
  ...
</plugin>
I already get warning in Eclipse about missing lifecycle mapping just by switching to 24.4.4
This was not the case with 24.3

**Comment by xdenser** [comment]
Yes now it works for me.
