### ISSUE TITLE
Incorrect flow-server dependency version in vaadin-maven-plugin

### ISSUE THREAD

**Issue by mcollovati** [vaadin/platform#6567]
### Describe the bug

vaadin-maven-plugin has a dependency to flow-server inherited by flow-maven-plugin through hilla-maven-plugin

This means that if hilla-maven-plugin is based on a flow version older than the one defined in platform there could be an incompatibility in the flow-server version.

### Expected-behavior

flow-server version used by vaadin-maven-plugin should be the same as in platform

### Reproduction

* Take a Vaadin project using version 24.4.3.
* Run `mvn dependency:tree -Dincludes=com.vaadin:flow-server`: flow-server version is `24.4.2`   
* Run `mvn dependency:resolve-plugins -DincludeGroupIds=com.vaadin`:  flow-server version is `24.4.1`

```
[INFO] --- maven-dependency-plugin:3.6.1:tree (default-cli) @ spring-skeleton ---
[INFO] com.example:spring-skeleton:jar:1.0-SNAPSHOT
[INFO] \- com.vaadin:vaadin-spring-boot-starter:jar:24.4.3:compile
[INFO]    \- com.vaadin:vaadin-spring:jar:24.4.2:compile
[INFO]       \- com.vaadin:flow-server:jar:24.4.2:compile
```

```
[INFO] --- maven-dependency-plugin:3.6.1:resolve-plugins (default-cli) @ spring-skeleton ---
[INFO] 
[INFO] The following plugins have been resolved:
[INFO]    com.vaadin:vaadin-maven-plugin:maven-plugin:24.4.3:runtime
[INFO]       com.vaadin:vaadin-maven-plugin:jar:24.4.3
[INFO]       com.vaadin:hilla-maven-plugin:jar:24.4.1
[INFO]       com.vaadin:flow-maven-plugin:jar:24.4.1
[INFO]       com.vaadin:flow-plugin-base:jar:24.4.1
....
[INFO]       com.vaadin:hilla-engine-core:jar:24.4.1
[INFO]       com.vaadin:flow-server:jar:24.4.1
[INFO]       com.vaadin:flow-push:jar:24.4.1
...
```

### System Info

Vaadin 24.4

**Comment by ZheSun88** [comment]
fixed in #6566
