### ISSUE TITLE
Exclude webjars in starters

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#659]
Bower webjars are only used by Bower mode. As all starters use npm, the could exclude all webjars. This decreases the WAR file size with 20MB, from 32MB to 12MB in a simple project.

What I used for exclusion is
```
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.webjars.bowergithub.vaadin</groupId>
			<artifactId>*</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.vaadin.webjar</groupId>
			<artifactId>*</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.webjars.bowergithub.polymerelements</groupId>
			<artifactId>*</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.webjars.bowergithub.polymer</groupId>
			<artifactId>*</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.webjars.bowergithub.webcomponents</groupId>
			<artifactId>*</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.webjars.bowergithub.insites</groupId>
			<artifactId>*</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

**Comment by knoobie** [comment]
Just a thought: 

releasing a vaadin-compatibility-package-v10-v14 to decrease the complexity that new projects have, that only want to run npm? So only projects that want to migrate or need bower have to explicitly add the additional dependency containing the needed stuff?

**Comment by ZheSun88** [comment]
The original issue has been solved, ticket closed.
