### ISSUE TITLE
slow building since switching from 24.3 to 24.4

### ISSUE THREAD

**Issue by d2k2-git** [vaadin/platform#6590]
### Describe the bug

since switching from vaadin 24.3.x to 24.4.x i have a huge performance problem in eclipse sts. every time a file is changed and saved something like "invoking 'Maven Project Builder'"  is triggered and blocking the IDE from any further actions for couple of seconds.

switching back to 24.3. solves the problem

![image](https://github.com/vaadin/platform/assets/6248041/0e811a2b-c96e-4a10-bb59-961a5ed6d035)

### Reproduction

use vaadin 24.4.x
change any file in eclipse (sts) and save the file. 

### System Info

Windows 10
Vaadin 24.4.6
Eclipse STS 4.23.1
Java 21

**Comment by mcollovati** [comment]
Most likely related to #6562

**Comment by mcollovati** [comment]
Should have been fixed in Vaadin 24.4.7 / Hilla 24.4.4.
@d2k2-git  could you please verify?
