### ISSUE TITLE
Need to upgrade Jakarta.servlet-api to latest version (6.x)

### ISSUE THREAD

**Issue by vivekjaiprakash** [vaadin/platform#6607]
## Description
We are using Karaf- 4.4.6 version in our project..While installing pax-web-features (9.0.16), it introduces dependency on Jakarta.servlet-api : 4.0.4.

**<bundle start-level="30" dependency="true">mvn:jakarta.servlet/jakarta.servlet-api/4.0.4</bundle>**

We use 6.x version of Jakarta.servlet-api in the project which creates a conflict causing the following error.

**org.ops4j.pax.web.pax-web-jetty [org.ops4j.pax.web.pax-web-jetty [71](R 71.0)] because it is exposed to package 'javax.servlet' from resources jakarta.servlet-api [jakarta.servlet-api [24](R 24.0)] and jakarta.servlet-api [jakarta.servlet-api [116](R 116.0)] via two dependency chains.**

Please suggest a way to get around this error? Is there plans of upgrading jakarta.servlet-api in next karat version?

**Comment by TatuLund** [comment]
Karaf is not a product of Vaadin. So we are not the right party for this request.

The issue tracer of Karaf is here: https://issues.apache.org/jira/projects/KARAF/issues

Vaadin 24 does not support OSGi yet, as many pieces of the infrastructure are missing, Karaf being one of them. The OSGi spec.

There is OSGi add-on for Vaadin 23 here: https://github.com/vaadin/osgi
