### ISSUE TITLE
Multi Button

### ISSUE THREAD

**Issue by dwlabcube** [vaadin/platform#6618]
### Describe your motivation

A Multi-Button can be Handmade with Menubar or equal things, but i'd like to have a base component for this.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/a0cdb006-80df-429c-afd6-288375fdfd5f)

### Describe alternatives you've considered

Handmade with Menubar

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/934
