### ISSUE TITLE
Eclipse errors in freshly downloaded "skeleton-starter-flow" project

### ISSUE THREAD

**Issue by neerup** [vaadin/platform#668]
Not sure this is the right place for this bug.
I just cloned the skeleton-starter-flow project, and after importing and building in Eclipse. I now get these 3 errors in eclipse (se picture). 
Am I doing something wrong? 
Is there some way to avoid these errors?

The project works, but it is annoying to have the errors showing on my project

![image](https://user-images.githubusercontent.com/4113036/58230661-41ab6100-7d35-11e9-8ef6-ac64f087e0c3.png)

**Comment by heruan** [comment]
For the plugin execution error, you can add this plugin configuration to the `build` section of your `pom.xml`:

```xml
<pluginManagement>
    <plugins>
        <plugin>
            <groupId>org.eclipse.m2e</groupId>
            <artifactId>lifecycle-mapping</artifactId>
            <version>1.0.0</version>
            <configuration>
                <lifecycleMappingMetadata>
                    <pluginExecutions>
                        <pluginExecution>
                            <pluginExecutionFilter>
                                <groupId>com.vaadin</groupId>
                                <artifactId>vaadin-maven-plugin</artifactId>
                                <versionRange>[1.0.0,)</versionRange>
                                <goals>
                                    <goal>validate</goal>
                                    <goal>build-frontend</goal>
                                </goals>
                            </pluginExecutionFilter>
                            <action>
                                <execute>
                                    <runOnIncremental>false</runOnIncremental>
                                </execute>
                            </action>
                        </pluginExecution>
                    </pluginExecutions>
                </lifecycleMappingMetadata>
            </configuration>
        </plugin>
    </plugins>
</pluginManagement>
```

About the other two errors, they are invalid JSON files inside the `node_modules` directory: one's from `vaadin-charts`, the other from `chrome-trace-event`; they should be fixed on the owning projects, but for now you can disable JSON validation in Eclipse going to "Preferences > Validation" and unchecking the JSON Validator build flag:

<img width="616" alt="Screenshot 2019-05-23 at 09 29 57" src="https://user-images.githubusercontent.com/851745/58233877-7cb19280-7d3d-11e9-9bfd-7524064a5dd4.png">

**Comment by neerup** [comment]
Thanks.... it works...
Found out that.. Instead of disabling validation of json files, just mark the folder as derived
![image](https://user-images.githubusercontent.com/4113036/58247710-97463480-7d5a-11e9-825b-5be3ee2561d1.png)
