### ISSUE TITLE
Vaadin 14 WebBrowser getTimeZoneId not available anymore

### ISSUE THREAD

**Issue by kolle1986** [vaadin/platform#678]
In Vaadin 14 there is no anymore getTimeZoneId() method in WebBrowser object. What is the proper way now to get time zone id from client?

**Comment by tulioag** [comment]
That method was moved to `ExtendedClientDetails`. You can get that information now doing something like this:

`UI.getCurrent().getPage().retrieveExtendedClientDetails(e -> System.out.println(e.getTimeZoneId()));`

**Comment by kolle1986** [comment]
@tulioag Thanks

**Comment by tulioag** [comment]
You're welcome.
