### ISSUE TITLE
24.5: Ui-tests generator should be released as an experimental feature

### ISSUE THREAD

**Issue by manolo** [vaadin/platform#6799]
### Description

It has been decided that ui-tests generator is released as a experimental feature in 24.5

- [ ] add experimental feature in flow
  - [ ] https://github.com/vaadin/flow/pull/19965
- [ ] make copilot enable/disable ui-tests panel based on the flag
- [ ] mention ui-tests in the docs [page](https://vaadin.com/docs/latest/tools/copilot#built-in-panels)
- [ ] add some wording to the panel explaining that it's experimental

**Comment by yuriy-fix** [comment]
We probably don’t need to add a feature flag entry for this one. The user can simply avoid clicking the button if they don't want to use it, and everything will still work as expected, even with the plugin enabled and visible.

However, within the plugin itself, we can add a note mentioning that it’s still experimental.
