### ISSUE TITLE
Vaadin Control Center unable to proceed to Dashboard if app has more than one role

### ISSUE THREAD

**Issue by AndriiRevaEpicor** [vaadin/platform#7014]
### Describe the bug

After creates a second role for the deployed application with enabled `Identity Management` feature and proceed to the `Dashboard` page then exception is thrown and unable to use `Dashboard` page for this application at all.

### Expected-behavior

I expect that after create more than one role for deployed application, the Dashboard page will be opened without a problem.

### Reproduction

1. Setup Control Center as usual;
2. Log-in to the Control Center;
3. Click the `Settings` button, next click on `Deploy` right-top button;
4. Fill all required fields, enable `Identity Management` feature and click `Deploy` right-bottom button;
5. Select deployed app from the `Select application` combobox;
6. On the `Dashboard` page click on the edit roles button;
7. Create the first role with any name;
8. Proceed to the `Dashboard` page of the same app and make sure that this page opened as should;
9. Create another role with any name and proceed to the `Dashboard` page again.
10. Make sure that `There was an exception while trying to navigate to 'app/<here will be your app's name>' with the root cause 'java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl'` exception is thrown.

### System Info

Windows 11
Vaadin Control Center 1.0.2
Chrome 130.0.6723.119

**Comment by heruan** [comment]
Thanks @AndriiRevaEpicor for the report, this is currently under investigation.

**Comment by heruan** [comment]
Fix has been merged and will be released in Control Center 1.0.3 coming out this week.
