### ISSUE TITLE
Create platform snapshot build with all dependencies being a snapshot ones

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/platform#71]
It is rather cumbersome to test some particular feature (bugfix) in the project that depends on a platform: you have to override lots of dependencies (especially when it comes to components) to get a working build.

Also, having a snapshot build will allow us to test things easily on any part of the platform being changed.

**Comment by Artur-** [comment]
https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/vaadin/10.0-SNAPSHOT/
