### ISSUE TITLE
mvn archetype instructions from release notes do not work (14.0.0.rc1)

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/platform#713]
Instructions from [release notes](https://github.com/vaadin/platform/releases/tag/14.0.0.rc1) do not work 
```
mvn -B archetype:generate \
                -DarchetypeGroupId=com.vaadin \
                -DarchetypeArtifactId=vaadin-archetype-application \
                -DarchetypeVersion=14.0.0.rc1\
                -DgroupId=org.test \
                -DartifactId=vaadin-app \
                -Dversion=1.0-SNAPSHOT
                && cd vaadin-app
                && mvn package jetty:run

```
Error is:
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.vaadin:vaadin-archetype-application:14.0.0.rc1) -> [Help 1]

**Comment by ZheSun88** [comment]
actually according to what i remember, we don't release archetype for alpha/beta/rc versions.. 
we should remove that part from release note

**Comment by alvarezguille** [comment]
what's the reason for not having pre releases of the archetypes?

**Comment by ZheSun88** [comment]
I think it was a marketing decision.. Brought this topic back to the slack channel to confirm

**Comment by juhopiirainen** [comment]
At this point Maven archetypes are not released for beta/RC versions of Vaadin, only for the stable versions. Instructions in the release notes should be removed when publishing beta/RC versions.

**Comment by rmuller** [comment]
Note that as of today (2019-08-10) this instruction is still present as reported by @alvarezguille  without any mention of the information provided in this ticket.
See https://github.com/vaadin/platform/releases/tag/14.0.0.rc9

**Comment by ZheSun88** [comment]
Hi @rmuller , Thanks for reminding us about this. The instruction for using maven archetypes has been removed from the release note-14.0.0.rc9 and we are going to have a discussion about a future release.

**Comment by alvarezguille** [comment]
Instructions for 14.0.0 don't work either, trailing backslash is missing in last two lines 
```
mvn -B archetype:generate \
                -DarchetypeGroupId=com.vaadin \
                -DarchetypeArtifactId=vaadin-archetype-application \
                -DarchetypeVersion=14.0.0\
                -DgroupId=org.test \
                -DartifactId=vaadin-app \
                -Dversion=1.0-SNAPSHOT
                && cd vaadin-app
                && mvn package jetty:run
```

**Comment by juhopiirainen** [comment]
Fixed for the future in https://github.com/vaadin/platform/pull/792
Also changed the current release notes for V14.0.0
