### ISSUE TITLE
Allow changing the custom element prefix of Vaadin components

### ISSUE THREAD

**Issue by jouni** [vaadin/platform#726]
What follows is a vague idea of a use case. Meaning, this need didn’t come from any actual user, but I instead came up with a solution for which I’m now trying to justify:

----

As a developer, I would like to create HTML templates that are more future-proof in that I can more easily control what components I’m using in my application.

I would like to avoid using 3rd party custom element names, in case I want to switch to another component in the future without the need to rewrite all templates.

I would also want to avoid extending/wrapping all 3rd party components, because of the potential DOM element overhead and the amount of boilerplate I need to write.

---

As a solution, I’m proposing the following:

The default way of using our components would stay the same (pseudo code, the imports are not named like this) – you would only be able to use one theme at a time, and the element prefix is always `vaadin`:
```html
<script type="module">
  // Importing all would result in an error (element already registered)
  import '@vaadin/button'; // -> <vaadin-button>
  import '@vaadin/button/themes/lumo'; // -> <vaadin-button>
  import '@vaadin/button/themes/material'; // -> <vaadin-button>
</script>
```

We could allow developers to customize the prefix used by our custom elements.
```html
<script>
  Vaadin.namespace = 'unstyled';
  Vaadin.Lumo.namespace = 'lumo';
  Vaadin.Material.namespace = 'mat';
</script>

<script type="module">
  import '@vaadin/button'; // -> <unstyled-button>
  import '@vaadin/button/themes/lumo'; // -> <lumo-button>
  import '@vaadin/button/themes/material'; // -> <mat-button>
</script>
```

This would also allow using multiple themes on the same page, which could be a benefit for demos.

----

The value prop of this is rather vague/slim. I’m basically opening this up for discussion, if any users actually have this need or if this otherwise seems feasible.

**Comment by web-padawan** [comment]
Overall I like the idea of splitting packages. 
https://github.com/web-padawan/lit-components is already using separate packages.

The namespace feature will have us to do some tweaks for templates etc but should be doable.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin #57](https://github.com/vaadin/vaadin/issues/57) via [**ZenHub**](https://www.zenhub.com/)
