### ISSUE TITLE
V14rc6  Addon starter for flow have  have version 14.0.0.beta1  and structure is not frontend friendly.

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/platform#754]
version of vaadin is 14.0.0.beta1 instead of 14.0.0RC6
structure is not frontend friendly:
* no web pack config
* no frontend folder
* no package.json file

**Comment by mehdi-vaadin** [comment]
It may be an issue with vaadincom. The GH project looks ok. See https://github.com/vaadin/component-starter-flow/. I reported it in the vaadincom slack channel [here](https://vaadin.slack.com/archives/C6QJ3J1PZ/p1563542826036000).

**Comment by ZheSun88** [comment]
reported to Vcom. they are going to take care of the downloaded contents.
