### ISSUE TITLE
V14rc6 Beverage Buddy App for Vaadin Flow HTML and Plan Java are same

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/platform#756]
HTML and Plan Java versions of starter Beverage Buddy App are the same. 

In case they should be same it is confusing... and then it should be only one version.

In case some version is overwritten by other, then it should be fixed.

Proof:
g-10-64-12-170:Downloads vladyslavgutsul$ diff -rq html plain-java 
Files html/.git/index and plain-java/.git/index differ
Files html/.git/logs/HEAD and plain-java/.git/logs/HEAD differ
Files html/.git/logs/refs/heads/master and plain-java/.git/logs/refs/heads/master differ
Files html/.git/logs/refs/remotes/origin/addon-dx and plain-java/.git/logs/refs/remotes/origin/addon-dx differ
Files html/.git/logs/refs/remotes/origin/bu/bump-grid-4.0 and plain-java/.git/logs/refs/remotes/origin/bu/bump-grid-4.0 differ
Files html/.git/logs/refs/remotes/origin/bu/npm/remove-bower-production and plain-java/.git/logs/refs/remotes/origin/bu/npm/remove-bower-production differ
Files html/.git/logs/refs/remotes/origin/exclude-webjars- and plain-java/.git/logs/refs/remotes/origin/exclude-webjars- differ
Files html/.git/logs/refs/remotes/origin/kb/check-unpinned-dependencies and plain-java/.git/logs/refs/remotes/origin/kb/check-unpinned-dependencies differ
Files html/.git/logs/refs/remotes/origin/master and plain-java/.git/logs/refs/remotes/origin/master differ
Files html/.git/logs/refs/remotes/origin/mcm/npm/clean-files and plain-java/.git/logs/refs/remotes/origin/mcm/npm/clean-files differ
Files html/.git/logs/refs/remotes/origin/mcm/npm/exec-fizzed and plain-java/.git/logs/refs/remotes/origin/mcm/npm/exec-fizzed differ
Files html/.git/logs/refs/remotes/origin/mcm/npm/npm-package-annotation and plain-java/.git/logs/refs/remotes/origin/mcm/npm/npm-package-annotation differ
Files html/.git/logs/refs/remotes/origin/mcm/npm/remove-closure-dep and plain-java/.git/logs/refs/remotes/origin/mcm/npm/remove-closure-dep differ
Files html/.git/logs/refs/remotes/origin/mcm/npm/remove-local-files and plain-java/.git/logs/refs/remotes/origin/mcm/npm/remove-local-files differ
Files html/.git/logs/refs/remotes/origin/mcm/proto/ccdm/v1 and plain-java/.git/logs/refs/remotes/origin/mcm/proto/ccdm/v1 differ
Files html/.git/logs/refs/remotes/origin/mcm-master-npm and plain-java/.git/logs/refs/remotes/origin/mcm-master-npm differ
Files html/.git/logs/refs/remotes/origin/npm/tomcat-spike and plain-java/.git/logs/refs/remotes/origin/npm/tomcat-spike differ
Files html/.git/logs/refs/remotes/origin/snapshots-for-production-mode and plain-java/.git/logs/refs/remotes/origin/snapshots-for-production-mode differ
Files html/.git/logs/refs/remotes/origin/tmp and plain-java/.git/logs/refs/remotes/origin/tmp differ
Files html/.git/logs/refs/remotes/origin/update_packagelock and plain-java/.git/logs/refs/remotes/origin/update_packagelock differ
Files html/.git/logs/refs/remotes/origin/v10 and plain-java/.git/logs/refs/remotes/origin/v10 differ
Files html/.git/logs/refs/remotes/origin/v11 and plain-java/.git/logs/refs/remotes/origin/v11 differ
Files html/.git/logs/refs/remotes/origin/v12 and plain-java/.git/logs/refs/remotes/origin/v12 differ
Files html/.git/logs/refs/remotes/origin/v13 and plain-java/.git/logs/refs/remotes/origin/v13 differ
Files html/.git/logs/refs/remotes/origin/vl/ccdm and plain-java/.git/logs/refs/remotes/origin/vl/ccdm differ
Files html/.git/logs/refs/remotes/origin/vl/ccdm-expected-state and plain-java/.git/logs/refs/remotes/origin/vl/ccdm-expected-state differ
Only in html/.idea/artifacts: html_war.xml
Only in html/.idea/artifacts: html_war_exploded.xml
Only in plain-java/.idea/artifacts: plain_java_war.xml
Only in plain-java/.idea/artifacts: plain_java_war_exploded.xml
Files html/.idea/compiler.xml and plain-java/.idea/compiler.xml differ
Files html/.idea/modules.xml and plain-java/.idea/modules.xml differ
Files html/.idea/workspace.xml and plain-java/.idea/workspace.xml differ
Only in html: html.iml
Only in plain-java: plain-java.iml
Files html/pom.xml and plain-java/pom.xml differ

g-10-64-12-170:Downloads vladyslavgutsul$ diff html/pom.xml plain-java/pom.xml 
4,5c4,5
<     <artifactId>html</artifactId>
<     <name>html</name>
---
>     <artifactId>plain-java</artifactId>
>     <name>plain-java</name>

**Comment by mehdi-vaadin** [comment]
Did you download them on vaadin.com/start? If yes, then it's a vaadincom issue which is reported [here in gitlab](https://gitlab.vaadin.com/vaadincom/webpage/issues/4690) and [here in slack](https://vaadin.slack.com/archives/C6QJ3J1PZ/p1562829487431500).

**Comment by Skrikjo** [comment]
yes from vaadin.com/start

**Comment by alvarezguille** [comment]
Issue 4690 is actually about description, screenshot and running instructions.
Right now there is another issue and the downloaded zip is always for beverage buddy, reported as 4741
