### ISSUE TITLE
Repository definitions using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/platform#766]
Recently, [it was discovered](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb) that many Java libraries are downloading dependencies over non-secured HTTP connections. This means that developers using these libraries are vulnerable to man-in-the-middle attacks. The attack is so easy to perform, that there's even an [example on GitHub](https://github.com/mveytsman/dilettante) that shows how to do it. [Vaadin is affected by this](https://github.com/search?q=org%3Avaadin+%22http%3A%2F%2Fmaven.vaadin.com%22&type=Code).

To solve the problem, we need to replace any repository definition that uses `http` with `https` in all of our maintained dependencies. The problem is not solved by merely fixing, for example, the `vaadin-core` or `vaadin` dependencies only since the repository definitions are transitive with Maven. Moreover, we should check third-party libraries used by Vaadin that may contain `http` repository definitions and take appropriate action.

Due to the severity of the issue the Spring team launched the [nohttp project](https://spring.io/blog/2019/06/10/announcing-nohttp) with [tools](https://github.com/spring-io/nohttp) that help ensuring https is used. Moreover, they have taken action not to include anything in their builds that uses http and misses that transitive "feature" of Maven.

**Comment by snicoll** [comment]
@alejandro-du thanks for initiating this and adding the reference to `nohttp`. I should add that adding a `repository` to published pom is considered a bad practice as Maven will use the repository to resolve any dependency. This is an issue for those who are behind corporate proxies or are willing to handle the list of repositories themselves.

On our side we use the `flatten-maven-plugin` to remove such build-specific information from published pom.

**Comment by ZheSun88** [comment]
Can we close this issue now?

**Comment by alejandro-du** [comment]
Vaadin 10 and 8, both supported versions, are still affected by this.

**Comment by ZheSun88** [comment]
Can you list them here, I can help with that.. 

I have seen the PR for vaadin 8, are there some other things missing?

**Comment by ZheSun88** [comment]
I have made some more fixes related to this issue. 

skipped a few repositories which are archived/haven't have any updates in 2019. 
this ticket can be closed after all the open PRs got merged.

**Comment by juhopiirainen** [comment]
Everything done, thanks everyone!
