### ISSUE TITLE
Maven plugin packaging ignores some files

### ISSUE THREAD

**Issue by Legioth** [vaadin/platform#776]
Starting from #670, the repackaged `vaadin-maven-plugin` is missing most of the static resources form `flow-maven-plugin`. This issue is hidden by the fact that `flow-maven-plugin` is included as a transitive dependency when the plugin is run, which means that the static resources from the `flow-maven-plugin` jar are used instead.

**Comment by ZheSun88** [comment]
![image](https://user-images.githubusercontent.com/31067185/68569254-5526c180-0466-11ea-85f9-4036e8d85e40.png)

**Comment by Legioth** [comment]
At least those. I don't remember whether there were also other files missing.

**Comment by ZheSun88** [comment]
I have compared the file numbers in the folders, all the others are the same. 
guess don't need to check the content. XD
