### ISSUE TITLE
Create a vaadin-compatibility-mode package and move webjar dependencies there

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#782]
Not that Flow is by default run in npm mode and Bower/compatbility mode is enabled by including a `flow-server-compatibility-mode` we can simplify webjar exclusion by adding a `vaadin-compatibility-mode` platform dependency which depends on
* `flow-server-compatibility-mode`
* webjars

Now you can set your app into compatibility mode without knowing the Flow version, using `vaadin-compatibility-mode` mode instead (version 14.0.0). We can also remove all exclusion rules from the starters and simplify them

**Comment by alvarezguille** [comment]
> Now you can set your app into compatibility mode without knowing the Flow version

Version is resolved by the BOM, no need to know it

> We can also remove all exclusion rules from the starters and simplify them

Most transitive webjars come from the flow components. To be able to remove exclusion rules from the starters we would need to add exclusions to `vaadin` and `vaadin-core` artifacts and add all those excluded dependencies to the new compatibility mode artifact. Which would be hard to maintain.

The only benefit I see in having an artifact for `vaadin-compatibility-mode` is not mentioning flow. Am I missing something?

**Comment by Artur-** [comment]
This only makes sense if we could exclude webjars. Let’s close it then
