### ISSUE TITLE
Provide simple and full change log of all vaadin-* artifacts per vaadin-platform release

### ISSUE THREAD

**Issue by retomerz** [vaadin/platform#785]
At the moment it is very hard to estimate the impact of a new release.
For my use, the current change log is not very helpful.

Example:
The v14rc7 change log [1] states that "Vaadin Confirm Dialog (PRO)" is updatet to "web component v1.1.4".
The v14rc6 change log [2] states that "Vaadin Confirm Dialog (PRO)" has used "web component v1.1.1".

So I have to go through the change logs of 1.1.2, 1.2.3 and 1.1.4 to see how these changes could impact my app if I update from rc6 to rc7.

Please provide a simple full change log per vaadin-platform release which includes all changes (at least bug fixes) of all vaadin components since the previous vaadin-platform release.
As an example see how Oracle provide bugfix list for a JDK 8 updates, it is very simple and clear:
https://www.oracle.com/technetwork/java/javase/2col/8u221-bugfixes-5480117.html

Thanks

[1] https://github.com/vaadin/platform/releases/tag/14.0.0.rc7
[2] https://github.com/vaadin/platform/releases/tag/14.0.0.rc6

**Comment by juhopiirainen** [comment]
Hi and thanks for the issue.

We are aware that the list of changes between releases is not quite there. We struggle between "too long" and "too short", since not everyone is interested about every change. We try to come up with something for everyone and adding a link to a full list of changes might work. Thank you for the suggestion!

**Comment by retomerz** [comment]
Just read the changelog of Vaadin 14.0.3 [1].

I like the new section "Issues fixed in this release".

Thanks!

[1] https://github.com/vaadin/platform/releases/tag/14.0.3
