### ISSUE TITLE
Incorrect XML file mentioned in server logs

### ISSUE THREAD

**Issue by paivisoinio** [vaadin/platform#787]
Download any project using start.vaadin.com and run them (V14 rc9). 
File web.xml mentioned in the server log texts does not exist, should it refer to pom.xml? 
In pom.xml `productionMode` is already set to `True`. This looks confusing to me. 

```
====================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
====================================================================
```

<img width="1058" alt="Screen Shot 2019-08-08 at 22 49 30" src="https://user-images.githubusercontent.com/36551733/62734836-986e3000-ba32-11e9-8af2-0805d1838cd7.png">

**Comment by gatanaso** [comment]
Same as: https://github.com/vaadin/flow/issues/6160

**Comment by juhopiirainen** [comment]
Closing as duplicate (thanks @gatanaso )
