### ISSUE TITLE
Maven archetypes with V13 and V14

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/platform#810]
Maven archetypes need be released for each stable (from V13 on) individually.
Now there is a branch selection is the build but it does nothing on behalf of the build.

**Comment by ZheSun88** [comment]
maven archetype has been released and tested. 
https://repo.maven.apache.org/maven2/com/vaadin/vaadin-archetype-application/13.0.13/

release configuration has been updated.
release checklist has been updated.

update note:
specify the branch under `run`-> `changes` tag. 

The issue can be closed now
