### ISSUE TITLE
Also update npm files when bumping version for V14 starters

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/platform#836]

**Comment by ZheSun88** [comment]
with a quick look, should be quite straightforward. 

update https://bender.vaadin.com/admin/editRunType.html?id=buildType:VaadinPlatform_UpdateMavenStarters&runnerId=RUNNER_343&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253AVaadinPlatform_UpdateMavenStarters%26init%3D1&cameFromTitle= 

probably after version setting,  do a `mvn clean install` and commit all the file.

**Comment by ZheSun88** [comment]
updated the script. need to test.

**Comment by ZheSun88** [comment]
currently, `mvn clean install` doesn't trigger the `npm install`, so it doesn't updated the npm file, especially the `package-lock.json`. https://github.com/vaadin/flow/issues/6428

**Comment by ZheSun88** [comment]
tested. this issue can be closed now
