### ISSUE TITLE
Automatically test that components do not have unintended dependencies

### ISSUE THREAD

**Issue by Legioth** [vaadin/platform#854]
Components and add-ons are supposed to use `<scope>provided</scope>` for all generic Flow dependencies.

None of our modules are supposed to have non-provided dependencies for e.g. the Servlet API or any specific SLF4J implementation.

This is something that could be good to test on the platform level since it's quite easy to accidentally include something with an inappropriate scope. As an example, see https://github.com/vaadin/vaadin-custom-field-flow/pull/38.

**Comment by manolo** [comment]
since flow components now are in the same repo `flow-components` and all `pom.xml` files for addons are generated by a script we can make the script force those deps as provided.
