### ISSUE TITLE
New templates for release notes

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/platform#872]
We need two new release notes templates to platform:
- Stable maintenance release notes, that is stripped from all the immutable things that are in the major release notes. Those are replaced with a link to the release notes of a major release.
- Pre-release version release notes that is stripped from everything that can change during alpha, beta and rc releases (browser and JDK support etc.). When we anticipate that this is the last beta/RC before a major release it can be released with release notes for the major.

**Comment by juhopiirainen** [comment]
https://github.com/vaadin/platform/pull/877

**Comment by ZheSun88** [comment]
Issue has been merged. so this ticket can be closed now.
