### ISSUE TITLE
Back up plan for broken release

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#874]
After we have made a broken release, what should we do? 

only **modify the release note to mention the broken part** is not enough, as users still can get the info about new release from Vcom. 

we need to prevent the version update on Vcom. If they are scanning the tag info from here, we probably need to delete the tag from platform repo.

**Comment by paulroemer** [comment]
Yes, exactly. And also for our users it is better to completly kill the release and tag from GH. What exactly prevents us from doing so. Short googling gave: https://www.abeautifulsite.net/how-to-delete-a-tag-on-github

**Comment by juhopiirainen** [comment]
Ok. So, we can delete a tag from GH, but it really is not a silver bullet here. It helps for that particular problem, that VCOM is pointing to a broken version. But, we would need to do way more than just to remove GH tag to get rid of the broken version. VCOM can use a dirty-dirty-hack to go around this problem (please consult your friendly local PO about this matter).

So, just removing GH is is not a feasible solution. Also, I prefer to play with a open hand: the latest release is broken for a couple days, we just need to stick with that and release new working version fast. If this would be a first GA - version, we would need to do more. A lot more.

**Comment by paulroemer** [comment]
> Ok. So, we can delete a tag from GH, but it really is not a silver bullet here. It helps for that particular problem, that VCOM is pointing to a broken version
No, it will also help people that just visit github.com/vaadin/platform/releases to check which is the latest release and will just use it without reading the release notes.

> But, we would need to do way more than just to remove GH tag to get rid of the broken version. 
Sure! Did not talk about de-Maven it.

> I prefer to play with a open hand
I totally agree, playing with open cards is always good - as we are doing right now. But I also want to make sure our users are not using a broken version. That's more important to me. We can keep the tag for clarification, I don't mind much. But I would appreciate if we could get rid of the release. Or make it at least a draft (but then I guess people might stil use it).

**Comment by paulroemer** [comment]
> Ok. So, we can delete a tag from GH, but it really is not a silver bullet here. It helps for that particular problem, that VCOM is pointing to a broken version

No, it will also help people that just visit github.com/vaadin/platform/releases to check which is the latest release and will just use it without reading the release notes.

> But, we would need to do way more than just to remove GH tag to get rid of the broken version.

Sure! Did not talk about de-Maven it.

> I prefer to play with a open hand

I totally agree, playing with open cards is always good - as we are doing right now. But I also want to make sure our users are not using a broken version. That's more important to me. We can keep the tag for clarification, I don't mind much. But I would appreciate if we could get rid of the release. Or make it at least a draft (but then I guess people might stil use it).

**Comment by juhopiirainen** [comment]
>But I would appreciate if we could get rid of the release. Or make it at least a draft (but then I guess people might stil use it).

<insert image of thundering high-five here>

So, we changed the release notes to "draft" and after some impressive VCOM-team footwork (thanks Artem!) VCOM started to down grade to 14.0.5! Just one fix to "how to update" - page and we seem to have a working solution. Excellent solution, thanks Paul!
