### ISSUE TITLE
Re-enable enforcer plugin in master

### ISSUE THREAD

**Issue by qtdzz** [vaadin/platform#944]
In #941, I removed the enforcer plugin to skip the check temporarily.
After resolving all the dependencies issues in flow and platform, we **should** enable the enforcer plugin again.

**Comment by haijian-vaadin** [comment]
put on hold for now, let's recheck this after the first beta is out.

**Comment by haijian-vaadin** [comment]
Let's close this one. The current assumption is that this plugin was used mostly for the webjars for bower, now they are not needed.
