### ISSUE TITLE
run test for platform under dev mode

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/platform#953]
Currently, platform tests are running in production mode only, we should test everything under two modes. 

as we have discovered the issue with running V14+ application on safari 10 under `dev` mode https://github.com/vaadin/flow/issues/6817 . after the issue got fixed, we can 
1) update the travis configuration to test under `dev` mode; (**on going**)
2) update platform snapshot version to test under `production` mode(**done**);
3) update platform JDK test running under `production` mode (**done**).
4)  Enable safari 10 test after flow issue got solved #956 (**on going**)

**Comment by ZheSun88** [comment]
**master** branch has been done;
**14.1** and **14.0** are coming.

**Comment by ZheSun88** [comment]
PRs have been made for 
master: https://github.com/vaadin/platform/pull/945
V14: https://github.com/vaadin/platform/pull/955
V14.1: https://github.com/vaadin/platform/pull/968

**Comment by ZheSun88** [comment]
All open PRs have been closed and merged. 

the mentioned `1` and `4` are still on going.

**Comment by manolo** [comment]
At the same time consider why we still need this : https://github.com/vaadin/platform/blob/7add7a36e3f6b5126be9bff7e39d7793bbe1f214/vaadin-platform-test/src/main/java/com/vaadin/platform/test/CustomServletDeployer.java#L50

**Comment by manolo** [comment]
Consider an extra step for running vaadin-platform-tests in dev-mode, probaly only for snapshots in order not to penalize validation times for PRs

**Comment by manolo** [comment]
done in #3788
