### ISSUE TITLE
New Microsoft Edge built on Chromium tests

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/platform#958]
Because the new Microsoft Edge is built on Chromium, it is fully compatible with popular automated testing frameworks like Selenium WebDriver and Puppeteer. With general availability coming in January, we recommend incorporating the new Microsoft Edge into your existing automated tests now – testing the Beta channel will give you six weeks advance notice of any potential issues that may impact your site.

**Comment by ZheSun88** [comment]
https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/#DopOHAXyY81091JC.97

**Comment by ZheSun88** [comment]
Our current tests have been running with Edge 80, the lastest Edge built on Chromium. https://app.saucelabs.com/tests/135a2f5131a143b2aebc0ab916eae218#4

so probably we can close this ticket.

one related question would be that do we need to test the original edge ?
