### ISSUE TITLE
Update node.js in Travis to 10.x

### ISSUE THREAD

**Issue by web-padawan** [vaadin/platform#990]
The 8.x version that is currently used reaches its end of line by the end of the year:
https://github.com/vaadin/platform/blob/4b80c3098f3b51d3a805e28c398d02908ac1bbaf/.travis.yml#L4

We should upgrade to 10.x LTS instead.

**Comment by ZheSun88** [comment]
in travis log:

```
Your installed 'node' version (8.9.1) is not supported but should still work. Supported versions are 10.0+
You can install a new one:
  - by following the https://nodejs.org/en/download/ guide to install it globally
  - or by running the frontend-maven-plugin goal to install it in this project:
  $ mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.13.0" 
You can disable the version check using -D[secure].ignoreVersionChecks=true
```

**Comment by web-padawan** [comment]
Yes, also noticed that. Somehow it is different 🤔

**Comment by ZheSun88** [comment]
in Travis, we have pre-installed node version: 4.X, 6.X. and 8.X.. apparently they are all too old now. We will need to find a way to install newer version in travis..

and on the other hand, we have the plan to move platform validation to teamcity.

**Comment by ZheSun88** [comment]
updated the node version to 12.13.0 (latest LTS) with PR https://github.com/vaadin/platform/pull/994

```
$ nvm install 12.13.0
Downloading and installing node v12.13.0...
Downloading https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v12.13.0 (npm v6.12.0)
```
